### ISSUE TITLE
New chainsaw item

### ISSUE THREAD

**Issue by metc** [Electrical-Age/ElectricalAge#1]
**Enhancement**
It would be nice to have a chainsaw item, like in Industrial-Craft (http://wiki.industrial-craft.net/index.php?title=Chainsaw). Here is also another "Advanced Chainsaw" (http://feed-the-beast.wikia.com/wiki/Advanced_Chainsaw).

The chainsaw may also be used as a weapon. It must be more or less rapid and robust, depending on the craft recipe.

**Comment by nickdutto** [comment]
Great idea buddy.

I will look into it, I am currently working on the mod as it has been handed over I'll get back to you soon.

**Comment by Dolu1990** [comment]
Done
