### ISSUE TITLE
Some blocks have same textures

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#10]
Some of the blocks, such as the 50V and 200V Compressors, have the same texture so the only way to visually differentiate exactly what you're looking at is with mods such as WAILA. 

![2014-03-12_17 11 10](https://f.cloud.github.com/assets/6238934/2400375/a281b524-aa09-11e3-8912-7205984e5412.png)

**Comment by Dolu1990** [comment]
Maybe a quick fix could be a color swap ? lick industrial blue ? it not the ulimate solution XD but why not ? acknoledge ? i swap color ?

**Comment by DrummingFish** [comment]
Either that or give the higher tier blocks trimmed edges? As long as there is something to tell them apart :).

**Comment by Dolu1990** [comment]
Oky, i make a color swap ^^

**Comment by DrummingFish** [comment]
I think this issue can be closed now :)

**Comment by Dolu1990** [comment]
Ackoledge ^^
