### ISSUE TITLE
Port on Cauldron

### ISSUE THREAD

**Issue by 0ln** [Electrical-Age/ElectricalAge#100]
Hi.

I post that here because I cannot contact the developers.
I would like to create a CraftBukkit server with your mod but it doesn't work with Cauldron.
You should port your mod on Cauldron.
http://cauldron.minecraftforge.net/

**Comment by Dolu1990** [comment]
Hi, 
I have already see some cauldron server working with the mod.
What is your issue log ? crash report ?

**Comment by 0ln** [comment]
That's the errors detected when I launch the server: http://pastebin.com/JZXrGv46.

**Comment by JPitman97** [comment]
Are you running you're server with any other mods?

**Comment by 0ln** [comment]
Nope. This is the only mod installed.

**Comment by JPitman97** [comment]
If you remove Electrical Age does the server load up because in you're crash report i cannot find any mentioning of Electrical Age causing the crash

**Comment by 0ln** [comment]
I removed the mod from de server and I got the same errors. It seems that a Java lib is missing.
This: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException.
