### ISSUE TITLE
[RESOLVED] BETA-1.8_r36 How to cover Wires with Blocks

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#102]
Hi a find a BIG problem with the new relase and it is with all of the components,and the problem is when I wanted to cover the cables or anything else I can't cover it whit blocks,I can not put block's on the ELN r36 components so that is a big problem :( 
I dont know is this my configuration file problem so I put this here to help you
A put the light life bigger and put false to the explosion
# Configuration file

compatibility {
    B:ComputerProbeEnable=true
    B:ElnToOtherEnergyConverterEnable=true
}

debug {
    B:enable=false
}

dictionary {
    B:tungsten=false
}

entity {
    I:replicatorId=-1
    B:replicatorPop=true
}

gameplay {
    B:explosion=false
}

general {
    B:versionCheckEnable=true
}

lamp {
    I:economicLifeInHours=3200
    I:incondescentLifeInHours=800
}

mapgenerate {
    B:cinnabar=true
    B:cooper=true
    B:forceOreRegen=false
    B:lead=true
    B:plumb=true
    B:tungsten=true
}

modbus {
    B:enable=false
}

simulation {
    I:electricalFrequancy=20
    I:electricalInterSystemOverSampling=50
    I:thermalFrequancy=400
}

xrayscannerconfig {
    B:addOtherModOreToXRay=true
    D:rangeInBloc=5.0
}

**Comment by JPitman97** [comment]
When you want to cover a block you have to hold C and then click the wire with the block :) This was added in r34 to stop people accidentally covering there wires.
  -Shadow

**Comment by tvk1372** [comment]
Ohh Thank you I forget this xd
