### ISSUE TITLE
config to hide/disable xrayscanner

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#103]
Will be possible add config option to completely disable or hide recipe and or item xrayscanner ?

**Comment by Dolu1990** [comment]
Actualy you can reduct his range to 1 block to make it useless but i can add a flag if you want ?

**Comment by ghost** [comment]
yes please add some config to disable this item

**Comment by Dolu1990** [comment]
it's added. come in next release (disable craft)
