### ISSUE TITLE
cofh.api.energy

### ISSUE THREAD

**Issue by ppappila** [Electrical-Age/ElectricalAge#104]
I was tracking down a mod sorting problem and I came across a post from Cofh. Are you going to be or are you compatible with Cofh? Because my problem disappeared when I eleminated from your mod the cofh.api call.
here is the link to the post.....might want to check it out. Oh I am using ElectricalAge_BETA-1.8_r36.

https://github.com/CoFH/ThermalExpansion/issues/49

**Comment by Dolu1990** [comment]
Hi, that seem a new feacturs with forge after 1180. actualy i think you problem must be solved if you use forge 1180. but in any case i must fix that :) thanks for issue

**Comment by Dolu1990** [comment]
(electrical age is compatible with RF API)

**Comment by Dolu1990** [comment]
Hmmm i must update the API.

**Comment by Dolu1990** [comment]
Hi,
I have release the r37, can you try with and give me a feed back if all is ok ? (i have update RF API)

**Comment by ppappila** [comment]
thanks that did the trick.....now does that mean you are thermal expansion compatible or is it a future thing???

Date: Fri, 15 Aug 2014 04:53:15 -0700

**Comment by Dolu1990** [comment]
Electrical age contain a ELN to Other xxxV converter. That alow to convert electrical energy to some other mod (IC2 experimental, RF, OpenComputer)
