### ISSUE TITLE
1.9 r37 wireless signal repeater problem

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#109]
Hi a find a problem with the wireless signal repeater, I can't name the chanell it does not open  to edit   :( :( 
And my maps crash when I put It somewhere close to my power station (There is a lot of furnaces and turbines and cables ~ 50 piece of turbine and furnace)
It always crash when I put the repeater that close to a furnace or a turbine, I dont know if is it crash whit other elements of the ELN mod but I get crash whit those !
![2014-08-17_22 27 02](https://cloud.githubusercontent.com/assets/8401485/3945662/29d20118-264d-11e4-8e74-c7df5b30dedc.png)

I get this crash report:

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2014.08.17. 22:04
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at mods.eln.sixnode.wirelesssignal.repeater.WirelessSignalRepeaterProcess.getTx(WirelessSignalRepeaterProcess.java:49)
    at mods.eln.sixnode.wirelesssignal.WirelessUtils.getTx(WirelessUtils.java:30)
    at mods.eln.sixnode.wirelesssignal.WirelessUtils.getTx(WirelessUtils.java:76)
    at mods.eln.sixnode.wirelesssignal.WirelessUtils.getTx(WirelessUtils.java:21)
    at mods.eln.sixnode.wirelesssignal.rx.WirelessSignalRxProcess.process(WirelessSignalRxProcess.java:39)
    at mods.eln.sim.Simulator.tick(Simulator.java:499)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_24_Simulator_tick_ServerTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:520)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 929653352 bytes (886 MB) / 1449656320 bytes (1382 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 550 (30800 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 Optifine OptiFine_1.7.2_HD_D3 17 mods loaded, 17 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.2.217.1147} [Forge Mod Loader](forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.12.2.1147} [Minecraft Forge](forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    TooManyItems{1.7.2} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    malisiscore{1.7.2-0.8} [Malisis Core](malisiscore-1.7.2-0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.5 [DEV R3] - MC 1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    SlimevoidLib{2.0.4.6} [Slimevoid Library](SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    DynamicTransport{0.1.1.0} [Dynamic Transport](DynamicTransport-0.1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Eln{37} [](ElectricalAge_BETA-1.9_r37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    examplemod{1.0} [examplemod](ExtraDoors-1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    extradoors{1.5} [Extra Doors](ExtraDoors-1.7.2-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    guilib{1.0.7.2} [GUI Library](Forge_GuiLibv1.0.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ImmibisCore{58.1.4} [Immibis Core](Immibis-Core-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    malisisdoors{1.7.2-0.9.1} [Malisis' Doors](malisisdoors-1.7.2-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    cfm{3.3.2} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.2%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    RedLogic{58.1.3} [RedLogic](RedLogic-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    MSC2{1.2.1} [Mob Spawn Controls 2](Forge_MSC2v1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 45 (2520 bytes; 0 MB) allocated, 6 (336 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['goku'/596, l='Electronic sience', x=2,51, y=237,00, z=57,46]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Dolu1990** [comment]
Hi,
Could you send me your map ? and coordonate ? (by this way i can reproduct this bug easly :)

**Comment by Dolu1990** [comment]
Hooo just, now repeter work with all channel
you don't need specify one

**Comment by Dolu1990** [comment]
Hmm i think it's ok, i have understood the problem that must be fixed in r39

**Comment by Dolu1990** [comment]
It's now fixed in r39, coulde you verify if all is ok in your case ? (normaly it's ok)
Thanks for issue : D

**Comment by tvk1372** [comment]
The repeater doesn't crash the map :)
Thnak you for the fast relase !
