### ISSUE TITLE
Mod name still using codename "Eln" and version needs updating

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#11]
The mod name is still using the codename "Eln" and should be changed to the actual name of the mod, Electrical Age.
This will make it easier for people using NEI to search for the mod and reduces confusion.
I didn't want to change it myself as there may be a reason you'd left it like that.

Also the mod version in eln.java is still "0.0.1" and should be changed to reflect the version it is currently or is heading towards which would be something like "BETA-1.0.4".

**Comment by Dolu1990** [comment]
True, i change now the mod annotation to : 
@ Mod(modid = "Eln", name = "Electrical age", version = "BETA-1.0.4")
I have verified with NEI, all is ok ^^
Thanks for issue : D i'm not sensitive to these thing XD but it's good to change that.

**Comment by Dolu1990** [comment]
i release the 1.0.4 when the portable ore scanner is totaly integrated

**Comment by Dolu1990** [comment]
Or maybe that jump to BETA-1.1.0 because 2 new element was added (portable ore scanner with in game raytracing display       +      suspended lamp that swing wih wind and weather)
