### ISSUE TITLE
Basic blocks on wires

### ISSUE THREAD

**Issue by inventorAdam5** [Electrical-Age/ElectricalAge#110]
You said you could place basic blocks like glass on things like wires, but when I try to, nothing happens

**Comment by Dolu1990** [comment]
From minecraft forum OP => 

In game controls
To open the integrated wiki it's key 'X'
To turn some small wall blocks it's Wrench item + right click OR "Wrench" key ('C' per default) + right click.
To interact with some items (flash light, xray scanner), just right click
To put blocks on wire it's "Wrench" key ('C' per default) + right click.
