### ISSUE TITLE
1.9 R39 beta sound issue ?

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#113]
I dont know if is this my pc problem or the beta relase problem,but the transformer and the 50v and 200v turbine sounds are like a sinus line,for 2 second I can here it and for 2 second its silent,but just in my maps,in the tutorial map is ok,so that is very weird! :(
In my maps you can find a lot of turbines and heat dissipators,but I dont think this is the problem,because I can fix this problem at the earlier beta's.  :(
When I restart minecraft it stoped at the 1.4... but in the new release it doesnt stop and it is a very horrible sound. :(

**Comment by Dolu1990** [comment]
Hi, I juste have tested it and all seem good. Maybe it's because your map is overloaded ? and the server has some lags and sournds loop fail ? Could you send me your map ? i'm very interrested in :)
What is your PC CPU ?

**Comment by tvk1372** [comment]
My pc:
cpu amd athlon II 760K (4x 3.8GHz)
ram: 8GB 2400MHz ( I configure minecraft to use 4GB of 8)
500GB sata 2 HDD 200GB free space
videocard : ati radeon r9 270x oc 
Here is the map I hope I uploaded the good way!
You can use any of those in the map in my minecraft all of those have bad sound :(
https://www.dropbox.com/s/93unhr79v6t2dhp/Electronic%20sience.rar

**Comment by Dolu1990** [comment]
So yes you server is over loaded, there reason is :
It's very heavy to simulate cable that are connected like  a checkerboard (grid) because that don't allow to simplify cable into serial resistance.

You can reduct server load by reducting in eln.the I:electricalInterSystemOverSampling flag to for example 10
