### ISSUE TITLE
50V light on 200V don't burn

### ISSUE THREAD

**Issue by harke69** [Electrical-Age/ElectricalAge#115]
les ampoules 50V fonctionne sur du 200V et plus (tester sur du 800V aussi... les 200V ne grille pas non plus)

**Comment by harke69** [comment]
a ba si c'est juste que ça met un certain temps

**Comment by Dolu1990** [comment]
Yep, remarque je pourrai faire que sa les fait péter dessuit.

**Comment by harke69** [comment]
ben techniquement c'est ce qui devrai effectivement se passer ^^ tien question vu que je ne trouve pas comment te contacter, comptez vous ajouter aussi du courant alternatif et les phases ? ^^

**Comment by Dolu1990** [comment]
C'est pas planifier, le but étant que le mod reste quand même accessible. Des chose on volontairement été simplifiée (Tout est DC).
Tu peut me contacter sur le forum minecraft au compte electrical age :
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104648-electrical-age-physics-electric-circuits-more

Je m'occupe maintenant de faire que sa pète tout de suite ^^ sa sera dans la r40
