### ISSUE TITLE
strange texture bug with relay

### ISSUE THREAD

**Issue by harke69** [Electrical-Age/ElectricalAge#116]
put a glowstone powder in slot 1, put a relay in another slot of the action bar, it will be all black

dans la barre d'action, mettez en premier slot a gauche une poudre de glowstone, puis un relais n'importe ou à sa droite, celui ci sera alors tout noir, de même quand on le déplace à la souris

**Comment by harke69** [comment]
tite vidéo : http://www.twitch.tv/kalras/b/560059215

**Comment by Dolu1990** [comment]
Yep c'est des bug de configuration open gl, c'est le gros bordel parce que rien n'est documenté avec le jeux, du coup faut y aller a taton XD
Il faut que je prenne le temps de le résoudre .

**Comment by harke69** [comment]
pas de soucis, ce n'est qu'esthétique, mais comme tu veux qu'on remonte les bugs ben on remonte ^^

**Comment by Dolu1990** [comment]
yep pas de soucis ^^
