### ISSUE TITLE
Nuclear energy in the future relases ?

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#118]
Hi!
I saw some youtube videos (industrial craft) using nuclear reactors blocks to generate power.
ELN mode have heat turbines and coolers to.
You guys do not want to make a nuclear reactor block to connect that with the heat turbines ? It would be so awesome.
But that would be an option to if you made some nuclear fuel to the old heat furnace,but I dont know...
Its your mod xd
It would be so damn cool to put a plutinium or Uranium rod to a modded furnace :)
If I upset you with this issue, then I'm sorry,but it would be so damn awesome and realistic ELN mod!

**Comment by Dolu1990** [comment]
Hi, Nuclear power is a lot of work because we don't want to juste make somthing to simple.
It's panned, but for unknow future :)
