### ISSUE TITLE
What is to do list in this year?

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#119]
I am so excited of your mod releases,because its impossible to consume,it has many way to use it.
And I am wondering what kind of new items,machines,new blocks will be released from now up to December in this year to ElectricalAge?
Just if its public! :)
(If you made a Wishlist some day to this site  I woud ask for a 800v heat turbine,and a nuclear reactor system) xd.
Sorry for the funny question,but I am so excited when you come out with new stuff,because I am a 26year old electrical Engineer from Hungary,and this mod is shake up my life when I play with it ! 
So THANKS guys to made this mod!!!

**Comment by Dolu1990** [comment]
Hi,
Actualy we are considerate cables and power transmition.
For the moment => 
50V is for starting in survival
200V is house / base big room
800V is for house / base big room interconnection.
but maybe there is missing high range voltage/cables. we are reconsiderate cable balances/max power.
There is a some discution about realism/simplification balance XD it's hard ^^
and we don't want release somthing that we want remove some month after.

From your point of view, what is the must wanted new content that must be added ?
Do you play in survival ?

**Comment by tvk1372** [comment]
Hi I play only in creative mod,because its a lot easy to build,and I always play alone the game.
From my point,I write you about the Nuclear power,because in my country (Hungary) we use cheap energy and that is nuclear power.And nuclear power gives you a lot of energy in turbines bigger than coal.But I know its a lot of time to render, a water pump,a giant turbine,and a reactor to.It take monts to write the program to those.But It would be so fun and realistic to work in a reactor in minecraft,that is my dream xd.
But I can se in your mod,this is the next level to the realism,but minecraft has some limits and that is bad.
Yesterday a figure out some mode in my head!
That was it:
![2014-08-23_13 15 55](https://cloud.githubusercontent.com/assets/8401485/4020423/1dbd1344-2ab8-11e4-99ef-947c3e9768ee.png)
![2014-08-23_13 16 35](https://cloud.githubusercontent.com/assets/8401485/4020425/24ae36ec-2ab8-11e4-9ef8-d265e670e2b6.png)
![2014-08-23_13 16 42](https://cloud.githubusercontent.com/assets/8401485/4020426/2a305ffa-2ab8-11e4-95ec-f17e48698769.png)
I modified the coal block and i rename it to Plutionium,Im so crazy xd.
And I was thinking about what would happen if I put under water the furnace and the thermal cables just like in a real reactor,and, that was the biggest mistake ever! The cables are  all blown up. xd.
But back to the topic,I think my must wanted thing for me now is a bigger turbine (4x4 block) with 2KW of out put power,and much stornger cables to handle the Amp.I think that would be enough juice for giant houses xd!

**Comment by harke69** [comment]
le nucléaire n'est pas une priorité pour moi surtout qu'on cherche plutôt à s'en débarrasser de nos jours. 
De nouvelles machine pour utiliser toutes cette énergie seraient plus intéressant, le tout est de trouver les quels ajouter.
quelques proposition : sonnette de porte, ascenseur, escalator, tondeuse électrique pour les moutons.

english: 
nuclear power is not a priority for me especially as we seek rather to get rid of today. 
New machine to use all that energy would be more interesting, the whole thing is to find what to add. 

some proposition: doorbell, elevator, escalator, electric clippers for sheep.

**Comment by tvk1372** [comment]
Hi harke69 please forgive me,I dont speak French!
I think the guys gona made bigger things than the miner machine in the next year so I think the nuclear reactor with the giant  steam turbine (~4x4 block) and giant {KW} generator,and muscle cables and a transformer to downgrade is a good way to think.And a big elevator and escalator needs big power,and if you want to produced that power you need bigger than a little 500W heat turbine,but I like your idea,I realy wanted that stuff to put in minecraft,but we need to power those,and a power station could easily handle 2  elevator,and 2  escalator,and other electric things  like lamps of KW of power in 1 house,and your power is still not drained,you have power to light up a big minecraft village,so it would be like to play Lego,and that is awesome.Thats my job in real life,(electrical Engineer)
Your idea of the machines is a great idea,because that's is the next level to the housing ! 
And  dolu said 200V-800V for houses,so power station voltage (talking about Kilovolt's) with a transformer to downgrade to normal housing voltage if you want maybe for big houses with high consumption machines like Tv,washing machine,freezer,...,and industrial use big machines like a plutonium maker machine or uranium collector machine or something,or a futuristic power eater machine like an ore sorting machine,mining laser,or something in the real world for public transport,like metro,TGV train xd
But these are only my futuristic dreams,so forgive me that!
(But I think nuclear power plant is more effective than other plants currently in some case)
If I upsett you guys than I am very sorry,please forgive me!

**Comment by harke69** [comment]
don't worry, i'm not upset ^^
