### ISSUE TITLE
Tutorial sign 1.7.2

### ISSUE THREAD

**Issue by atonidas** [Electrical-Age/ElectricalAge#120]
Hi there,
About "sign tutorial"
I tried it and it does not work, I entered text but still telling the message to override:
No text assosiated to this beacon.

I would like to know if is a bug or something else because I find a lot of information and I see nothing in the wiki.
Thanks for your time and very good mod: D exceeds industrialcraft is more realistic

**Comment by Dolu1990** [comment]
Hi, 
For example, into map save folder, there is a EA folder that contain a text file that contain all text and some balise.
That solve your question ?

**Comment by atonidas** [comment]
Hi, thanks for the help, but can not find the file you talk to me and I have already opened up a world, placed "tutorial signs" written on them.

**Comment by Dolu1990** [comment]
this file is not automaticaly created, you can find it into tutorialMap

**Comment by atonidas** [comment]
Hi, we have a server with mods, and have included your mod, the problem of protection in issue, use the prevention and grief does not protect the bulbs or the carrier, any player can change :)

Usually great mod, it goes very well even on servers.

PS: I still can not find the file to modify for sign tutorial

**Comment by cm0x4D** [comment]
To find or create the file, go to your game saves folder and inside the folder of your map, there is a subfolder "EA", if not create it. A file called "tutorialSign.txt" in that folder will contain the data.
![bildschirmfoto 2014-09-16 um 07 56 13](https://cloud.githubusercontent.com/assets/6661117/4282996/50797e60-3d66-11e4-9771-d42f96cbdd68.png)
