### ISSUE TITLE
New Issue in Electrical Age 1.9 r40

### ISSUE THREAD

**Issue by EduMC** [Electrical-Age/ElectricalAge#121]
Hi, I think that i have found a issue in the mod, when i try to hide all the cables i can't because i can't put any block in the cable. I don't know if I'm not doing well or it´s a bug. I'll be waiting for an answer.
Thanks you, i love this mod it's unbelievable.

**Comment by tvk1372** [comment]
Hi EduMC!
Button C is your answer for your problem! (when you want to cover a cable or any hideable item you have to push c and the right mouse button altogether) :)

**Comment by EduMC** [comment]
Thank you very much, and sorry for put that here when it wasn't a issue. :)
