### ISSUE TITLE
MFSU to ELN voltage?

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#122]
Hi!
Does ELN have,or gona have MFSU to ELN converter in the nearby releases?
It would be so helpful for me,because in some case in ic2 mod (Nuclear power) has great power generation and it could be useful for me.and the ELN to other converter is not backwards compatible :(

**Comment by Dolu1990** [comment]
Hi, for the moment there is no other to Eln converter, i must discut about that with the team ^^

**Comment by tvk1372** [comment]
Thanks Dolu!
I hope you can help me with that.

**Comment by JPitman97** [comment]
We will look into this when we have the time but sadly college and work means most of the team are busy most of the time.
