### ISSUE TITLE
Power problem with turbine in new relase!

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#124]
Hi!
I found a problem when I was using the 200v turbine.
I dont know why,but when I put a system together like these in the picture (a normal connection) the heat is sky rocking and the voltage is dropping crazy fast to 0 for something 
When I put the trimmer to 30% or higher and I use it in IDLE (nothing on the back) the voltage is normal ~200v,but when I start the testing with a 120w or or lower power light bulb the voltage goes to ~200v and than a few seconds later its dropping like crazy!I dont know why! (It doesent matter what do I put on the back,and how many turbines and furnaces put together,I tested it whit 16 furnace and 16 turbine together and I get the same dropping whith only 1 connected stuff,but I should get KW's of power of that configuration) 
Please fix the problem guys !
This is the description and the pricture of the setup (I dont know the 50V turbine is ok I didnt test it)
![2014-08-27_22 53 04](https://cloud.githubusercontent.com/assets/8401485/4067345/2be82814-2e2d-11e4-943c-3070343b8276.png)
![2014-08-27_22 59 16](https://cloud.githubusercontent.com/assets/8401485/4067360/3be3a8a6-2e2d-11e4-831d-c98fb0c02f9f.png)
![2014-08-27_22 59 23](https://cloud.githubusercontent.com/assets/8401485/4067364/4253e3f4-2e2d-11e4-8291-7aa4e54dae5e.png)
![2014-08-27_22 58 10](https://cloud.githubusercontent.com/assets/8401485/4067666/937f2d4e-2e30-11e4-8c29-a689f7a57305.png)
So these are the prictures,and you can see the turbine is a much-much cooler (91celsius,and 22V) than the furnace or the thermal cable.(456celsius) And its powering only a 120W light bulb.
And its doesent matter which connection tip I use I always get the same measurement of the Voltage,and voltage dropping.
I use coal,and combustion to heat that up.
Please test it for your self and fix the problem :(

**Comment by Dolu1990** [comment]
hi
There is no problem, the reason is :
When you don't load the system the cool side remain cool and the delta of temperature is high.
When you load the system, because the cool side is not cooled => temperature rise at cool side => delta temperature fall down, and voltage to :)

It's that no ? or i don't have understood the problem ?

**Comment by tvk1372** [comment]
Merci Sir!
You was right,the heat dissipator was the missing thing!
I have to cool the turbine it doesent mater how much power put to on it :)
You can close the issue
