### ISSUE TITLE
Some way to pay for the energy of the energy counter?

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#127]
You did a very good job with the energy counter, but... How to pay for the energy?

**Comment by Dolu1990** [comment]
Thanks,
There is 2 mod of usage, the counter mod (usual) and the prepay mod. 
You can use the prepay mod, and set a energy value. then when the counter reach zero, the counter shut down the power.
Additionaly with the password you can check that nobody else change the configuration.
It's that ok ?

![image](https://cloud.githubusercontent.com/assets/4832082/4189362/986756de-377b-11e4-998c-9e091ca819b7.png)

**Comment by ivangouba** [comment]
Yes, but I said about paying. For example, the credit card.

**Comment by Dolu1990** [comment]
Ahhhh
For the moment we don't have any credit card because that implies lot of new blocks to manage and make that coherent :)
So actualy, the electrician guy must come and put the password and fill the counter.

**Comment by ivangouba** [comment]
Ahh jaja, I'll wait :)
