### ISSUE TITLE
Water turbine glitches

### ISSUE THREAD

**Issue by OutcastZeroOne** [Electrical-Age/ElectricalAge#132]
As i already posted on the forum, and Dulu has said to have fixed in an unreleased update, the water turbines produce power when not in water. Simply place a turbine down and a piece of wire and you can measure full power off of it.

In the tutorial world the turbine is shown in flowing water. But if you place it on non-flowing water it will also start to turn. Not sure if this is a bug, just reporting my findings.

Power output of the turbines dont seem to change with weather either.

**Comment by cm0x4D** [comment]
I checked it and could not reproduce your findings. Be sure to use the always the latest release.
![2014-09-16_07 37 46](https://cloud.githubusercontent.com/assets/6661117/4282907/ab8949e0-3d64-11e4-9c1b-94ce05a75fea.png)
![2014-09-16_07 43 07](https://cloud.githubusercontent.com/assets/6661117/4282908/ab899454-3d64-11e4-8592-9adbaedfe563.png)
![2014-09-16_07 43 45](https://cloud.githubusercontent.com/assets/6661117/4282909/ab8a3f9e-3d64-11e4-8966-d955d4285725.png)
