### ISSUE TITLE
Conversion rate from W to EU/tick

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#134]
Do you know the conversion rate for how many EU/tick you get depending on the input power of the converter?

**Comment by cm0x4D** [comment]
All these values are configurable in **Eln.cfg** in minecraft's config folder.
![bildschirmfoto 2014-09-16 um 08 04 59](https://cloud.githubusercontent.com/assets/6661117/4283043/6992432c-3d67-11e4-982c-9b1b9a7c26f8.png)
I interpret the value as 1/3 EU/tick per Watt (which is the default).
