### ISSUE TITLE
¿Combining renewable energy with coal?

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#139]
Is there any way to have a system in which renewable energies have preference against coal, so I don't burn that much coal? Where wind, water and sun give all their available power and coal turbines add the rest of the power needed.

**Comment by bomdia** [comment]
you need an advanced circuit you can build it now only test a bit

**Comment by Dolu1990** [comment]
You can look into ElectricalAge_house map from https://github.com/Dolu1990/ElectricalAge/releases/download/BETA-1.9/ElectricalAge_tutorialMap_BETA-1.9_r41.zip
That solve your question ?

**Comment by bomdia** [comment]
an ot question dolu1990 but when u release new release i attend the fix and the turret :D

**Comment by Dolu1990** [comment]
For the moment i'm to mutch bussy on my graduate projet to switch some time to electrical age :(
I have some dead line to reach.
