### ISSUE TITLE
Typo on site's homepage

### ISSUE THREAD

**Issue by UntouchedWagons** [Electrical-Age/ElectricalAge#144]
At http://electrical-age.net/ there's a small typo:

> Cables, sensors, actuators, alarms, etc. can be placed on each face (outer and inner) of a cube, **witch** allows a significant reduction of the consumed space by electrical installations.

This should be

> Cables, sensors, actuators, alarms, etc. can be placed on each face (outer and inner) of a cube, **which** allows a significant reduction of the consumed space by electrical installations.

**Comment by metc** [comment]
Thanks for your report, this is now corrected.

And by the way @UntouchedWagons, our website is open source, check the repo here: https://github.com/Electrical-Age/electrical-age.github.io.
