### ISSUE TITLE
Ore Scanner (regenOreScannerFactors)

### ISSUE THREAD

**Issue by TheWhiteTyger** [Electrical-Age/ElectricalAge#146]
Hello! First I wish to say, I love this mod and I am happy to have it running on our server. Now for the sad news, here is a failure from the OreScanner. I tried to include everything I could find related to this crash, but the actual crash report does not contain any information related to the crash itself. I can provide the actual crash report, but here is what I was able to find. thank you for your time, and I do not expect a fix anytime soon, take your time and thanks again for all the hard work and love that was put into this mod.

http://pastebin.com/BHRgNcia

Using 1.7.10 Minecraft with Forge Minor version 1231 and Electrical Age Beta r43

**Comment by ltouroumov** [comment]
We are having this issue too, our log contains the exact same error.

**Comment by Dolu1990** [comment]
Thanks for the issue, that come fixed in next release
