### ISSUE TITLE
Update to OC API 1.4

### ISSUE THREAD

**Issue by fnuecke** [Electrical-Age/ElectricalAge#147]
OpenComputers 1.4 API should now be stable, so it'd be great if you could update to it.
A (more or less complete) list of changes can be found here: http://ocdoc.cil.li/tutorial:modding_onefour
(Looks scary, but you'll probably only need to adjust a few imports)

**Comment by Dolu1990** [comment]
Thanks for notification :)
I will do that soon : D

**Comment by DrummingFish** [comment]
Implemented some time ago.
