### ISSUE TITLE
Tree Resin Collectors can be placed on floors and ceilings

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#15]
It makes no logical sense that they can be placed on floors and ceilings as Tree Resin cannot be realistically collected that way.
![2014-03-21_18 32 27](https://f.cloud.github.com/assets/6238934/2486537/830dc9ec-b127-11e3-8298-de9117369da2.png)

**Comment by Dolu1990** [comment]
Fixed, thanks for issue ^^

**Comment by DrummingFish** [comment]
Don't forget to close the issue :)

**Comment by Dolu1990** [comment]
Ahhhhh i was sure that was closed XD 
I have release 1.1.1 with you change and a lot of little fix ;)

**Comment by DrummingFish** [comment]
Great :D
