### ISSUE TITLE
Text Displaying BUG

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#150]
If you are using Chinese Language (or another except English) or installed BetterFonts Mod, text displayed by the tutorial sign will become blurred.
Like this:  
![2014-11-06_20 28 18](https://cloud.githubusercontent.com/assets/3974330/4935806/4b554fcc-65b1-11e4-8909-d2bdc79c14f0.png)
It's hardly to read, fix it plz

// Sorry for the bad English :P

**Comment by lambdaShade** [comment]
I had a look on it : correcting the bug for higher density fonts adds bugs to the default common-used font with less density... and in this case, we have to rewrite the tutorial...
I don't have a good solution for the moment...
