### ISSUE TITLE
[Ideas] What I want to see in next mod update

### ISSUE THREAD

**Issue by Radviger** [Electrical-Age/ElectricalAge#151]
Hi, dear developers!
Your mod very nice and I have some ideas for it.
At once: In mod exists infinite power source, but hasn't infinite lights. Its very bad, because I cannot build spawn with permanent lighting with lamps from EA :C . Will be very nice if you added it =)
1) Webcam, that can translate video to datalogger or display in realtime.
2) Create protection system for teleporters. Like a non-owner cannot change current teleporter address.
3) Make wires and other devices compatible with FMP microblocks.
4) (Add for 3) Fix coloring bug with leaves and grass, placed on wire.
5) Fix texture bug on water turbine and battery chargers.
6) Add compact ore blocks for recipe compatibility (Like with BetterStorage :3).
7) More recipes in machines.
8) Fix tool(or all items) rendering bug (It is seems like a buggy flat thing in hand).
9) Any 3D model for flashlight =P (Will be very nice).
10) Any 3D model for E-Coal armor (EPIC!).
11) Other rendering in inv for things like transporter.
12) Add a computer or something like that (On future).
13) Add ability to place wires on the slabs.
14) Add more outputs to signal devices.
Thanks for reading my ideas =)

**Comment by lambdaShade** [comment]
"At once: In mod exists infinite power source, but hasn't infinite lights"
There is a command for avoid lamp aging :  "/eln lampaging <0/1>". But with time, we can probably add another lamp technology (such LEDs) - but it's not planned yet.

"1) Webcam, that can translate video to datalogger or display in realtime."
We already thought about that... but Minecraft graphical engine avoid it...

"2) Create protection system for teleporters. Like a non-owner cannot change current teleporter address."
Do you play with so evil players ? :-D

"3) Make wires and other devices compatible with FMP microblocks."
Impossible.

" 4) (Add for 3) Fix coloring bug with leaves and grass, placed on wire."
...possible.

 "5) Fix texture bug on water turbine and battery chargers."
Water turbine : I'll check that. It's already planned to replace the ugly and temporary model of the "Battery charger" ;-)

"6) Add compact ore blocks for recipe compatibility (Like with BetterStorage :3)."
It's already very hard to make a high quality mod with constantly extended content, so compatibility with others mods (especially closed-sources ones) is absolutely not planned. However, making compact ore blocks for storage/aesthetical use is possible... Noted.

 "7) More recipes in machines."
That's coming...

" 8) Fix tool(or all items) rendering bug (It is seems like a buggy flat thing in hand)."
That's a non reproductible bug at our side (with our hardware)... Intel graphic card ? We invite concerned users with sufficient Java skills to investigate on that issue. :-(

"9) Any 3D model for flashlight =P (Will be very nice)."
"10) Any 3D model for E-Coal armor (EPIC!)."
Not in top of the list... but why not. ;-)

"11) Other rendering in inv for things like transporter."
Not planned. From the solutions we have tested by the past, 3D rendering is the better one. ;-)

"13) Add ability to place wires on the slabs."
Slabs are an incredible hack... not sure we can do that without making some bad things at our turn...

" 14) Add more outputs to signal devices."
Not planned. And after all, this is a Minecraft characteristic. ;-)

Thank you and best regards !

**Comment by Radviger** [comment]
1. I seen mod (I think for 1.2.5 version of the game) that adds cams, but now it abandoned.
2. On my server installed protection plugin (worldguard) that protect regions from griefers and other bad boys, but I can't create stable warp system, because if I allow teleport using players can break this system by changing teleport address.
3. Why? The project red's wires compatible with ForgeMultipart, maybe you can lookup it's open source code?
4. Yes, I'm using Intel graphics card, can you create compatibility with it?
5. Against: mod named redstone paste can be placed under and upper of slab. And I think it open source.
   Thanks for your answers!
