### ISSUE TITLE
Resonant Rise 3 Testing.

### ISSUE THREAD

**Issue by Divineaspect** [Electrical-Age/ElectricalAge#155]
Any chance we could get an update? We're starting one week of intensive testing and are hoping we can find a star role for Electrical Age.

**Comment by cm0x4D** [comment]
Dolu, the main developer is quite busy at the time, and all other contributors (including me) do not have enough time to maintain the project - we are on stand by for the moment. So probably there are no updates in the very near future.

**Comment by Divineaspect** [comment]
Alright then, if we hit any snags with it I'll probably push it back to round 2 testing in Jan/Feb, and hope schedules clear up.
