### ISSUE TITLE
Electrical Age Conflict

### ISSUE THREAD

**Issue by lexastrom** [Electrical-Age/ElectricalAge#157]
Electrical Age for some reason has a conflict with BuildCraft. That's all.

**Comment by ivangouba** [comment]
That's true. When you try to open minecraft withe the new version of BuildCraft (6.2.2) it crashes. Please fix it.

**Comment by ivangouba** [comment]
I have discovered that if you disable ElnToOtherEnergyConverter in the config file, it fixes.

**Comment by Barhandar** [comment]
I do not experience this on r43. Also, new version of Buildcraft runs on RF alone, and presumably absence of MJ is what causing the crash.

**Comment by DrummingFish** [comment]
We no longer use the BC API.
