### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#158]
I see very little. The tutorial world never really explained how to place wires "in" blocks... it just said it can be done and showed it done with a signal button...

1st question: better docs?
2nd question: how do you place a wire through a block?

**Comment by penge1510** [comment]
1st question: A better docs would be great but until try just looking for some videos on YouTube. It worked for me. 
2st question: Put the wire on the block. Choose the block that you want to put on it, Hold the "R" key and click on the wire. For the case check the key bindings under the Electrical Age section.

**Comment by ghost** [comment]
Yeah, I tried videos... idk... didn't find very high quality videos... but... anyway

I see no key binding that lets me do that... on the latest version... trying "R" doesn't seem to work? probably just doing it wrong, but I don't see the keybinding in the options. 

EDIT: nevermind I got it

**Comment by Radviger** [comment]
Use C key instead.

**Comment by lambdaShade** [comment]
The in-game wiki will be enhanced soon : 
- Each object with a description text
- Translatable
