### ISSUE TITLE
The block save does not work in Forge.

### ISSUE THREAD

**Issue by penge1510** [Electrical-Age/ElectricalAge#160]
Hey Dolu1990!

I note this problem yesterday when I was loaded back my map. I placed a couple of things from Electrical Age mod and when I logged in these things were nowhere. I use Forge as server but the save is working in Single Player as well. Every time when I reboot my server the things are nowhere. It makes me sad... I was reading your comment about this. I tried to visit each dimension but I still have this problem. 
Could you help me in this problem?
I really want to build my first water mill but I can't because I'll loose in Multiplayer. :)

Thanks in advance!

**Comment by cm0x4D** [comment]
Probably fixed with new save system.
