### ISSUE TITLE
Trouble Finding Ores

### ISSUE THREAD

**Issue by Teshka** [Electrical-Age/ElectricalAge#163]
Hi, everyone. I have had EA installed for a bit, I'm in a world which I've been playing before installing Electrical Age, and I noticed I haven't been finding ore associated with the mod. I have found 2 copper ores, and I have smelted them, however, I have not found any other ore for a long time.

Am I supposed to be looking in certain places, or am I doing something wrong? Thanks!

**Comment by BroBeans** [comment]
This could be a bug. But for the time being, I would suggest using the X-Ray/Ore Scanner.

Link: http://wiki.electrical-age.net/index.php/X-Ray_Scanner

**Comment by DrummingFish** [comment]
Your problem is that you've loaded chunks before installing Electrical Age. You'll only find the ores in chunks that you haven't loaded yet (areas of the map you haven't visited). 

You should avoid adding mods that have worldgen after world creation.
