### ISSUE TITLE
Power cables explode randomly at Turbines & Lack of voltage in cables

### ISSUE THREAD

**Issue by Josh22799** [Electrical-Age/ElectricalAge#167]
Trying to make a mass power generator place, Cables keep exploding for unknown reasons. Also, Power has a very low voltage when I send it down a long cable, any way I can fix these problems?

**Comment by ghost** [comment]
Seria mais fácil se você mandasse um pritnscreen do seu sistema que esta explodindo e os números e informações do sistema mondado como tensão, potencia e corrente elétrica, e outros como a configuração do medidores. Ajudaria muito a resolver seu problema e descobrir o que é?
Mas em relação a sua pergunta, sim existe uma maneira de transmitir energia elétrica por longas distancias oky, utilizando transformadores e cabos de alta voltagem. Pretendo fazer um vídeo mostrando este sistema. Canal: youtube.com/user/whilebr

Obs: Ainda farei o vídeo.

**Comment by Josh22799** [comment]
![2014-12-18_11 27 09](https://cloud.githubusercontent.com/assets/7540519/5480214/0645ebee-86a9-11e4-9d54-4f6f895de734.png)

When I turn up the heat on the turbines the cables heat up and explode VERY quickly.

**Comment by Josh22799** [comment]
Also, When I link those three cables in the image above to other cables, Their temperature shoots up to 111 C

**Comment by cm0x4D** [comment]
You are using the wrong cables!
To wire a 50V turbine, you have to use a Low Voltage Cable, a Very High Voltage Cable supports a much higher voltage and thus a higher power (voltage*amperage), but much less electrical current and its serial resistance is quite high, so you have quite a big loss on the cables.
Use transformers to adapt the voltage to the used cables if you have to transport the energy over long distances (the higher the voltage, the better for long distances).
As a general rule, use Low Voltage Cables for 0V-50V, Medium Cables for voltages up to 200V, High Voltage Cables up to 1000V and Very High Voltage Cables from 1000V above.
Hope this helps.

**Comment by Josh22799** [comment]
Thanks, I will give it a shot.

**Comment by Josh22799** [comment]
![2014-12-18_12 20 10](https://cloud.githubusercontent.com/assets/7540519/5480995/55ff273e-86b0-11e4-9c73-2c4df98ef2c4.png)
These 3 cables still explode, No matter what I do. Heat furnaces where at 30%.

**Comment by ghost** [comment]
Você esta ligando duas turbinas em uma Thermal Dissipator, sem contar que da para ver que a também muitas turbinas ligadas, mas você não mostra a "cargas" que quer alimentar.
A regra geral é um Thermal Dissipator para cada turbina, e o calculo de potencia é muito importante pois o que produzir tem que ser igual ao consumo.
Calculo: Carga(Potencia) - Produção(Potencia) = 0 Aproximadamente margem de erro de 20%

**Comment by Josh22799** [comment]
Installed a extra row of Cooler's for my turbines. Everything works fine until I connect it to the main power line, Then everything blows up...

**Comment by ahaaaaa1234** [comment]
i was wiring a 3.20kv wire with creative cables and out of no where it just went BOOM after hooking to a breaker WHY?! (it blew up the generators hooked up to it) please help
