### ISSUE TITLE
Outdated BuildCraft API causing crashes

### ISSUE THREAD

**Issue by mezz** [Electrical-Age/ElectricalAge#168]
ElectricalAge is looking for an old version of the BuildCraft API and crashing when it can't find it.
Users are reporting the issue to Forestry, since we used to package the old API in our jar and recently updated it.

Here's a crashlog: https://gist.github.com/chloeprince/3df780e4de7ec7946357

Thanks!

**Comment by Dolu1990** [comment]
fixed in next release, thanks for issue.
