### ISSUE TITLE
Electrical Age does not work on a Server

### ISSUE THREAD

**Issue by tangoteamleader** [Electrical-Age/ElectricalAge#170]
I believe this might be similar to another issues post, but I wanted to add that Electrical Age does not appear to work on multiplier servers. I am currently running a (Modsauce 1.0.0.6) server, however, whenever the server is restart, all of the blocks disappear.

95% of the blocks disappear without leaving anything behind, however, I noticed that lamp posts "somewhat" remain - see attached image.  An error "Unamed Block, report to mod author." can be seen in the tool tip at the top of the image.

![2014-12-23_20 13 18_scc](https://cloud.githubusercontent.com/assets/7763932/5544929/2a154ab0-8ae1-11e4-9abc-d6f68d58851e.png)

**Comment by kayila** [comment]
I've managed to duplicate this on my server... Twice... The owner of which is a bit upset at their stuff disappearing not once, but twice.
