### ISSUE TITLE
[Crash]: Portable Scanner Crashes 

### ISSUE THREAD

**Issue by Lanse505** [Electrical-Age/ElectricalAge#173]
http://pastebin.com/5BQNTNYh
http://pastebin.com/wnhDvkNy

This is a crash some of our users using Electrical Age has been experiencing while playing RR3

Version: RR3 - 3.2.1.0
Mod Version: ELECTRICALAGE_BETA-1.9_R44

**Comment by Dolu1990** [comment]
Fixed in next release, thanks for issue
