### ISSUE TITLE
SUPER mod

### ISSUE THREAD

**Issue by astrixswayer** [Electrical-Age/ElectricalAge#176]
Je cherchais un mod qui soit plus réaliste que les autres modes comme  (IC2, enderIO)

Je trouve dommage que pour un francophone tu n'ai pas mis un mot en français sur ton site et sur le wiki  (s'est pas grave je me débrouille)

Un gros défaut est que il est trop réaliste par rapport au autre mod  (en réalité ces général) mais du coup sa fait peu de machine pour industrialisés notre mode minecraft 

Il faudrait que plus de monde boss avec toi et crée un industriel age, fluide age, transport age
se n'ai qu'une idée.

Si je peux t'aide s'est avec tout le plaisir du monde que je le ferai

**Comment by madshammy** [comment]
for those of you that don't know french

I was looking for a model that is more realistic than other modes such as (IC2 , enderIO )

I regret that for a francophone you did not put a word in French on your site and on the wiki ( will not matter I'm doing )

A big drawback is that it is too realistic compared to other mod (actually these general) but suddenly its been little machine for industrialized our way minecraft

We need more bosses world with you and creates an industrial age , age fluid transportation age
will have an idea.

If I can help you is with all the fun of the world that I will

**Comment by metc** [comment]
Merci pour votre message. Merci d'utiliser Github uniquement pour signer des bugs. Pour le reste, le post du [Forum Minecraft](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104648-electrical-age-physics-electric-circuits-more) est à disposition.
