### ISSUE TITLE
Can I continue?

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#181]
Hey Dolu, am I okay to continue cleaning up and contributing? Just thought I should ask first seen as I've been gone since April.

**Comment by BroBeans** [comment]
Hey, @DrummingFish 

I've talked to Dolu, and he is currently busy with school and work. I presume, that in the future he will continue work on Electrical Age.

**Comment by DrummingFish** [comment]
I've been the same recently. I just thought I'd get back to helping out and there's a few things I want to sort out as well as a ton of cleanup. Do you think you could ask him if it was okay for me to keep contributing?

**Comment by BroBeans** [comment]
I've been busy as well. And yes, I'll ask him. Just letting you know, it's always okay to continue contributing. Like I said before, I'm guessing that in the future he will resume work on Electrical Age. @DrummingFish

**Comment by BroBeans** [comment]
He said "yes" you should continue contributing. He also said "The mod is not dead". @DrummingFish

**Comment by DrummingFish** [comment]
Okay that's great, thanks :). And I am aware it's not dead haha. Nothing wrong with taking breaks.
