### ISSUE TITLE
Not using a "resources" directory for assets

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#182]
The "assets" folder should be changed to be a resources folder to allow .lang files and textures (as well as other things) to work properly without extra code.

However, I'm pretty sure this would require a lot of refactoring as the mod has been set up from the start in a different way than conventional Forge mods.

An example of the usual working structure would be here: https://github.com/DrummingFish/ExtraStuff

**Comment by cm0x4D** [comment]
At least switching to a gradle build sounds pretty interesting for me...

**Comment by DrummingFish** [comment]
Yeah exactly. I would try sort it but I'd rather Dolu did it himself.

**Comment by DrummingFish** [comment]
Would also make generating mod jars much easier.

**Comment by metc** [comment]
All mod releases are generated using the Gradle build system since the beginning of the project, but the build script is not published yet :blush:

**Comment by cm0x4D** [comment]
What I actually meant is to switch to gradle as main project format and in order to setup the dev environment too. 

Something like this would be definitely handy:

```
git clone https://github.com/Dolu1990/ElectricalAge.git
cd ElectricalAge
gradle runClient
```

This would make it much easier for those willing to contribute to get started...

**Comment by DrummingFish** [comment]
^this

No offence to Dolu but the mod needs a complete reshuffle. I'm going to work on sorting some areas eg. separating recipes from the main Eln.java and having them in their own space.

**Comment by Dolu1990** [comment]
i have created a new branch, 1.7.2-MNA-gradle. that move root of repository to the root of the forge directory. That contain the gradle script.
forge verssion => forge-1.7.10-10.13.2.1240-src

**Comment by metc** [comment]
Build script updated. See commit https://github.com/Dolu1990/ElectricalAge/commit/26030f29a7878adb7496c2b9e7adb4f885415a54.

You can now run the following command to start playing on the tutorial map.

``` sh
git clone https://github.com/Dolu1990/ElectricalAge.git
cd ElectricalAge
gradle unzipTutoMap runClient
```

**Comment by metc** [comment]
review by @cm0x4D

**Comment by cm0x4D** [comment]
Very cool, works like a charm. Thanks!

**Comment by metc** [comment]
The asset folder has moved to `src/main/resources`.

**Comment by metc** [comment]
The asset folder has moved to `src/main/resources`. See changes in https://github.com/Dolu1990/ElectricalAge/pull/219.
