### ISSUE TITLE
Wireless Buttons

### ISSUE THREAD

**Issue by zaidabuhijleh** [Electrical-Age/ElectricalAge#183]
I am having a hard time finding how to wire up a wireless system for my lights.  Can someone help?

**Comment by cm0x4D** [comment]
Please do not use this issue tracker to ask gameplay questions. It is intended to report bugs and feature requests-

There is a thread on the mincraft forum for such questions:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104648-electrical-age-physics-electric-circuits-more?page=46
