### ISSUE TITLE
Nuclear Reactor

### ISSUE THREAD

**Issue by pablotix20** [Electrical-Age/ElectricalAge#185]
Adding a nuclear reactor for creating energy would be great =)

**Comment by 4rz0** [comment]
Don't think this would fit, the step between thermal energy production trough burning solid fuel and solar/wind/water energy to nuclear energy is quite big.
I'd rather suggest adding more ways to make increase efficiency of low/mid tier technologies, like fuel refineries, multiblock coal burners, oil/gas as fuel, different engines first, and then technologies towards nuclear fission/fusion power.

**Comment by pablotix20** [comment]
But nuclear reaction is the best way of generating power in large scale projects, it would be just like now with a type of "funace" and a 3200v turbine with refrigerators of course

**Comment by cm0x4D** [comment]
We already discussed this topic more than once and it is on the long term list.

But we do not want make it as simple as adding new fuel and a new type of furnace. It should be closer to the reality including enrichment of radioactive materials with turbines, transportation containments, multi-block reactors, dedicated regulation controllers, ray protective suits, death by rays, different cooling mechanisms and of course thermonuclear catastrophes making big holes in your minecraft world in the case you mess up something with the reactor. 

You see, this is a serious amount of work and I guess for the moment we should rather add some additional consumers...

**Comment by 4rz0** [comment]
^that, exactly. Sounds pretty good!
I don't want ELN to be another BigReactor with place and forget technology.

**Comment by lambdaShade** [comment]
Effectively, nuclear reactor is not planned for soon. But some "smaller" electrical generators will be implemented in the next months :
- Bigger solar panels (2x2)
- Solar power plant
- Big wind turbine

**Comment by anar4732** [comment]
It would be perfect

**Comment by J09** [comment]
If you’d like to convert big reactors mod to electrical age power then use computercraft using eln probes and computer port from big reactors mod. Try creating your own computer craft program to convert big reactor energy to ELN. That’s what I did :)

**Comment by jrddunbr** [comment]
@J09: wut? How on earth does that work?

**Comment by J09** [comment]
View it on wiki

**Comment by J09** [comment]
@jrddunbr view it on the wiki :)

**Comment by jrddunbr** [comment]
Ah, you're converting signals. I thought you were transferring energy.

**Comment by J09** [comment]
Ya we are converting signals through computercraft

**Comment by Baughn** [comment]
Please don't use the bug tracker for support and general chat. That's what the discord is for: https://discord.gg/YjK2JAD
