### ISSUE TITLE
NullPointerException when calling registerPassiveComponent in dev environment

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#189]
This has been tested on two different PCs. 
It seems that 

``` java
obj.getObj("PowerElectricPrimitives"));
```

in Eln.java returns null for some reason.

Crash log: http://pastebin.com/kbxZr4h2

**Comment by DrummingFish** [comment]
This could possibly be an IDE problem but I'm unsure.

**Comment by Dolu1990** [comment]
It's strang. what the code at line 45 into src/main/java/mods/eln/sixnode/diode/DiodeDescriptor.java ?
For me it's this.cable = cable; and i don't know how that could create a exception XD

**Comment by DrummingFish** [comment]
Oh sorry I moved some code after that crash. It's supposed to be line 51.

``` java
base = obj.getPart("Base");
```

"obj" is null somehow.
