### ISSUE TITLE
Some Electrical Simulation Frozen, Causes TPS Loss

### ISSUE THREAD

**Issue by C222** [Electrical-Age/ElectricalAge#194]
On a SMP server I run, the players and I built a HV transmission line that ran about 1000 blocks.

System worked well for a few days, through a few restarts. After one restart the server was down to 1.5-ish TPS with no obvious cause.

We eventually discovered all the electrical equipment was frozen (voltages not changing value). The only way to get simulation running again was to remove all wire/breakers/transformers and place them back down.

An isolated section of HV cable spanning 7 blocks inside on one chunk would maintain about 900 V until removed. Adding a ground cable to the line would cause the whole line to explode continuously until a server restart.

**Comment by Dolu1990** [comment]
Hi,
Could you upload the map when the bug is present ? by this way i can take a look of why that happend.
version of ELN is ? version of minecraft ?

Thanks for issue

**Comment by C222** [comment]
World file: http://server.oshi7.tv/world.7z

Pack details: https://github.com/C222/LadPack

**Comment by C222** [comment]
Singleplayer: 12 TPS
Disabled Electrical Age / Forge removed all Electrical Age Blocks: 20 TPS
Re-Enabled Electrical Age (blocks still gone): 6 TPS

**Comment by Dolu1990** [comment]
Hi, thanks for files and info, i have experiment it and there is a real probleme, i track it.

**Comment by Dolu1990** [comment]
It's so funny, your map make minecraft loading it 2 time when the game boot. And he make it without destructing old loading <3<3<3
So, i have add somthing to avoid that. That seem ok now, That come in next release.
