### ISSUE TITLE
Electric Pump

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#198]
I think it would be great when you add a pump for different fluids like water. It should Need electricity to work,and when it gets overvoltage it just breaks instead of exploding and can be repaired with the wrench.

**Comment by anar4732** [comment]
nice idea.
but must be added to the fluid cable for that to happen.
and eat other modes support cable.

---

translated by google.
Original language: Turkish

**Comment by Leks543** [comment]
Is not it easier to make compatibility with other modifications?

translated by google. originilny Russian.

**Comment by anar4732** [comment]
certainly it is.

---

google translation: Turkish

**Comment by yannic312** [comment]
Other idea, maybe a red 800v turbine? voltage:800v , power:1000w , max.current:7,00A.

**Comment by anar4732** [comment]
@yannic312 
came in my mind.
for this
iron temperature should the stove.
