### ISSUE TITLE
issue building and running using Eclipse

### ISSUE THREAD

**Issue by jimidobson** [Electrical-Age/ElectricalAge#199]
Been trying unsuccessfully for a few hours to run the mod in eclipse. There's no documentation on the topic other than Forge documentation and from what I see this mod doesn't use a typical directory structure compared to other mods so I'm not sure how to solve this particular issue.

I've clone the project, run "gradlew setupDevWorkspace" and "gradlew eclipse". From there I imported the project into Eclipse. To get it running, I needed to add the following arguments to the run config:

--version 1.7.2 --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --accessToken FML --userProperties {}

However, from here, whenever I try to run, I always get the following error:

java.lang.NullPointerException: Initializing game
    at cpw.mods.fml.client.FMLClientHandler.getCurrentLanguage(FMLClientHandler.java:595)
    at cpw.mods.fml.common.FMLCommonHandler.getCurrentLanguage(FMLCommonHandler.java:521)
    at cpw.mods.fml.common.registry.LanguageRegistry.getStringLocalization(LanguageRegistry.java:60)
    at mods.eln.misc.I18N.getString(I18N.java:17)
    at mods.eln.Eln.preInit(Eln.java:451)

.......

I strongly suspect, from googling, that this is because my run config isn't able to find the language files, but the directory structure is a mess so I don't know where, or even if, I need to change my eclipse to point to the correct directory. 

If anyone could give me some pointers or input, I would really appreciate it. I'm afraid I'm stuck at the moment.

**Comment by DrummingFish** [comment]
"--version 1.7.2"

This mod runs on 1.7.10.

**Comment by jimidobson** [comment]
changed, but this hasn't solved my issue.

**Comment by DrummingFish** [comment]
I don't use Eclipse so I can't really help. Sorry.

**Comment by jimidobson** [comment]
Okay, thanks. Do you use another IDE or setup to build Electrical Age? I'm willing to try anything to resolve this problem.

**Comment by DrummingFish** [comment]
I use IntelliJ IDEA. I find it much better.

**Comment by jimidobson** [comment]
Funny you should say that, I've tried running Electrical Age in IntelliJ as well and have gotten the same problem (running causes a crash on startup, same crash and same cause):

-- Head --
Stacktrace:
    at cpw.mods.fml.client.FMLClientHandler.getCurrentLanguage(FMLClientHandler.java:595)
    at cpw.mods.fml.common.FMLCommonHandler.getCurrentLanguage(FMLCommonHandler.java:521)
    at cpw.mods.fml.common.registry.LanguageRegistry.getStringLocalization(LanguageRegistry.java:60)
    at mods.eln.misc.I18N.getString(I18N.java:17)
    at mods.eln.Eln.preInit(Eln.java:451)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by DrummingFish** [comment]
You must be setting it up wrong. Did you set up the client/server as a new application?

**Comment by jimidobson** [comment]
I believe so. Here is my build configureation:

Main Class: net.minecraft.launchwrapper.Launch
Program Arguments: --version 1.7.10 --tweakClass cpw.mods.fml.common.launcher.FMLTweaker --accessToken FML --userProperties {}
Working Directory: C:\MCModding\ElectricalAge\
Use Classpath of mod: ElectricalAge

I'm honestly not sure if I'm missing other config options I'm afraid.

**Comment by DrummingFish** [comment]
The main class is supposed to be GradleStart.

**Comment by jimidobson** [comment]
I don't have GradleStart in my project. Have I missed a download? For clarity, I've run "gradlew setupDevWorkspace" and "gradlew idea"

**Comment by metc** [comment]
The mod setup is not documented yet. Sorry for that.

Your gradle commands are correct. From Minecraft Forge `1.7.10`, simply use the `GradleStart` class as main class to start the client (or `GradleStartServer` to start the server).
You can use either Eclipse or IntelliJ:
- Eclipse: create the launch configuration manually. Enter `GradleStart` as main class. No program/VM arguments are required.
- IntelliJ: import the gradle project or use the `iml` project definition file. Application configurations are created automatically.
