### ISSUE TITLE
Crashes when using circuit breaker

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#2]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 14.02.14 13:45
Description: Rendering Tile Entity

java.lang.NullPointerException
    at mods.eln.cable.CableRender.connectionType(CableRender.java:319)
    at mods.eln.node.SixNodeElementRender.draw(SixNodeElementRender.java:65)
    at mods.eln.electricalbreaker.ElectricalBreakerRender.draw(ElectricalBreakerRender.java:51)
    at mods.eln.node.SixNodeRender.renderTileEntityAt(SixNodeRender.java:55)
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.renderTileEntityAt(TileEntityRenderer.java:172)
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.renderTileEntity(TileEntityRenderer.java:157)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:536)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1160)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1006)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:934)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:826)
    at net.minecraft.client.main.Main.main(Main.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mods.eln.cable.CableRender.connectionType(CableRender.java:319)
    at mods.eln.node.SixNodeElementRender.draw(SixNodeElementRender.java:65)
    at mods.eln.electricalbreaker.ElectricalBreakerRender.draw(ElectricalBreakerRender.java:51)
    at mods.eln.node.SixNodeRender.renderTileEntityAt(SixNodeRender.java:55)

-- Tile Entity Details --
Details:
    Name: SixNodeEntity // mods.eln.node.SixNodeEntity
    Block type: ID #221 (tile.NodeBlock // mods.eln.node.SixNodeBlock)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (212,106,280), Chunk: (at 4,6,8 in 13,17; contains blocks 208,0,272 to 223,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #221 (tile.NodeBlock // mods.eln.node.SixNodeBlock)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.renderTileEntityAt(TileEntityRenderer.java:172)
    at net.minecraft.client.renderer.tileentity.TileEntityRenderer.renderTileEntity(TileEntityRenderer.java:157)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:536)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1160)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['Player321'/309, l='MpServer', x=212,10, y=107,66, z=278,70]]
    Chunk stats: MultiplayerChunkCache: 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (256,64,232), Chunk: (at 0,4,8 in 16,14; contains blocks 256,0,224 to 271,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1419289 game time, 55519 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 116 total; [EntityBat['Bat'/49035, l='MpServer', x=196,69, y=17,10, z=340,66], EntityBat['Bat'/49028, l='MpServer', x=184,00, y=16,12, z=270,50], EntityZombie['Zombie'/45904, l='MpServer', x=152,63, y=17,00, z=244,47], EntityBat['Bat'/50106, l='MpServer', x=276,70, y=16,37, z=225,30], EntityBat['Bat'/50107, l='MpServer', x=272,25, y=20,10, z=224,56], EntityBat['Bat'/50108, l='MpServer', x=272,11, y=17,98, z=234,49], EntityPig['Pig'/263, l='MpServer', x=285,16, y=65,00, z=232,69], EntitySpider['Spider'/49311, l='MpServer', x=258,22, y=36,00, z=239,66], EntityBat['Bat'/49590, l='MpServer', x=217,72, y=50,10, z=214,44], EntityBat['Bat'/49585, l='MpServer', x=162,25, y=19,10, z=279,25], EntitySkeleton['Skeleton'/50074, l='MpServer', x=205,50, y=28,00, z=273,50], EntityCreeper['Creeper'/49801, l='MpServer', x=146,50, y=33,00, z=245,50], EntityCreeper['Creeper'/49802, l='MpServer', x=149,50, y=33,00, z=247,50], EntityBat['Bat'/49811, l='MpServer', x=151,56, y=18,17, z=242,76], EntityBat['Bat'/49812, l='MpServer', x=160,47, y=16,10, z=250,66], EntityBat['Bat'/49814, l='MpServer', x=161,33, y=19,00, z=248,30], EntityBat['Bat'/49815, l='MpServer', x=270,30, y=18,95, z=287,18], EntityCreeper['Creeper'/49338, l='MpServer', x=148,94, y=58,00, z=276,47], EntitySheep['Sheep'/76, l='MpServer', x=135,63, y=70,00, z=247,72], EntitySheep['Sheep'/77, l='MpServer', x=144,75, y=64,00, z=256,44], EntityCreeper['Creeper'/50174, l='MpServer', x=259,00, y=34,00, z=266,56], EntitySheep['Sheep'/78, l='MpServer', x=139,66, y=68,00, z=243,84], EntityItem['item.item.egg'/45092, l='MpServer', x=261,16, y=67,13, z=237,31], EntityCow['Cow'/75, l='MpServer', x=137,97, y=55,00, z=254,16], EntitySlime['Slime'/85, l='MpServer', x=141,31, y=36,06, z=279,31], EntitySlime['Slime'/84, l='MpServer', x=143,34, y=35,00, z=283,69], EntitySheep['Sheep'/86, l='MpServer', x=132,13, y=69,00, z=283,25], EntityClientPlayerMP['Player321'/309, l='MpServer', x=212,10, y=107,66, z=278,70], EntityZombie['Zombie'/49904, l='MpServer', x=271,50, y=24,00, z=210,50], EntitySlime['Slime'/83, l='MpServer', x=141,63, y=19,00, z=284,38], EntitySheep['Sheep'/82, l='MpServer', x=134,94, y=66,00, z=269,88], EntityChicken['Chicken'/91, l='MpServer', x=132,53, y=83,00, z=360,66], EntitySheep['Sheep'/90, l='MpServer', x=140,50, y=92,00, z=328,31], EntityCreeper['Creeper'/49128, l='MpServer', x=222,50, y=34,00, z=346,50], EntitySlime['Slime'/110, l='MpServer', x=151,69, y=37,00, z=266,31], EntitySlime['Slime'/111, l='MpServer', x=146,31, y=37,00, z=266,31], EntitySlime['Slime'/107, l='MpServer', x=154,80, y=11,00, z=269,20], EntitySkeleton['Skeleton'/50137, l='MpServer', x=143,50, y=20,00, z=306,50], EntitySkeleton['Skeleton'/46405, l='MpServer', x=167,50, y=28,00, z=360,50], EntitySlime['Slime'/119, l='MpServer', x=158,25, y=11,00, z=273,22], EntityCreeper['Creeper'/49150, l='MpServer', x=168,50, y=14,00, z=337,50], EntitySlime['Slime'/124, l='MpServer', x=152,78, y=20,00, z=287,78], EntitySlime['Slime'/123, l='MpServer', x=155,69, y=18,14, z=282,35], EntitySlime['Slime'/122, l='MpServer', x=153,78, y=18,00, z=275,22], EntityZombie['Zombie'/49404, l='MpServer', x=165,50, y=15,00, z=326,50], EntitySlime['Slime'/121, l='MpServer', x=154,69, y=15,69, z=278,68], EntitySlime['Slime'/120, l='MpServer', x=154,69, y=16,00, z=277,29], EntitySlime['Slime'/137, l='MpServer', x=155,78, y=22,60, z=297,34], EntityCow['Cow'/136, l='MpServer', x=155,63, y=69,00, z=272,41], EntityBat['Bat'/48179, l='MpServer', x=273,50, y=47,23, z=234,25], EntitySlime['Slime'/138, l='MpServer', x=159,31, y=20,00, z=297,69], EntitySheep['Sheep'/142, l='MpServer', x=146,16, y=85,00, z=333,63], EntityItem['item.item.egg'/49968, l='MpServer', x=241,83, y=63,08, z=226,09], EntitySkeleton['Skeleton'/49971, l='MpServer', x=271,50, y=28,00, z=237,50], EntitySlime['Slime'/131, l='MpServer', x=149,98, y=34,00, z=276,78], EntitySkeleton['Skeleton'/49970, l='MpServer', x=273,50, y=28,00, z=238,50], EntitySlime['Slime'/130, l='MpServer', x=152,78, y=35,00, z=276,78], EntitySkeleton['Skeleton'/49973, l='MpServer', x=274,50, y=28,00, z=229,50], EntitySkeleton['Skeleton'/49972, l='MpServer', x=273,50, y=28,00, z=229,50], EntitySheep['Sheep'/152, l='MpServer', x=168,59, y=88,00, z=268,03], EntitySheep['Sheep'/153, l='MpServer', x=171,34, y=98,00, z=269,22], EntitySheep['Sheep'/144, l='MpServer', x=157,50, y=91,00, z=336,34], EntitySkeleton['Skeleton'/49953, l='MpServer', x=219,50, y=37,00, z=217,50], EntitySheep['Sheep'/145, l='MpServer', x=154,13, y=89,00, z=352,16], EntityZombie['Zombie'/49712, l='MpServer', x=208,06, y=40,00, z=353,50], EntitySkeleton['Skeleton'/49718, l='MpServer', x=174,06, y=18,00, z=268,53], EntitySkeleton['Skeleton'/49717, l='MpServer', x=167,50, y=18,00, z=272,50], EntitySkeleton['Skeleton'/49409, l='MpServer', x=187,50, y=30,00, z=297,50], EntitySkeleton['Skeleton'/49947, l='MpServer', x=153,88, y=22,00, z=293,47], EntityZombie['Zombie'/50272, l='MpServer', x=130,50, y=20,00, z=308,50], EntityZombie['Zombie'/49948, l='MpServer', x=150,50, y=29,00, z=304,50], EntitySheep['Sheep'/161, l='MpServer', x=168,16, y=81,00, z=357,13], EntitySlime['Slime'/186, l='MpServer', x=195,69, y=26,00, z=344,73], EntitySlime['Slime'/185, l='MpServer', x=193,69, y=26,00, z=345,38], EntitySkeleton['Skeleton'/49922, l='MpServer', x=165,50, y=56,00, z=279,50], EntityZombie['Zombie'/49923, l='MpServer', x=160,50, y=56,00, z=271,50], EntityBat['Bat'/49446, l='MpServer', x=162,44, y=25,10, z=245,66], EntitySheep['Sheep'/176, l='MpServer', x=191,22, y=104,00, z=258,06], EntitySkeleton['Skeleton'/49921, l='MpServer', x=152,13, y=53,00, z=284,50], EntitySkeleton['Skeleton'/50302, l='MpServer', x=219,50, y=20,00, z=209,50], EntityZombie['Zombie'/49924, l='MpServer', x=162,50, y=54,00, z=272,91], EntitySlime['Slime'/180, l='MpServer', x=176,69, y=30,00, z=348,69], EntitySheep['Sheep'/181, l='MpServer', x=180,50, y=97,00, z=348,34], EntityPig['Pig'/207, l='MpServer', x=231,47, y=69,00, z=212,53], EntityZombie['Zombie'/50450, l='MpServer', x=226,50, y=41,00, z=329,50], EntityCreeper['Creeper'/49222, l='MpServer', x=198,50, y=20,00, z=356,50], EntityZombie['Zombie'/50438, l='MpServer', x=157,50, y=44,00, z=282,50], EntityBat['Bat'/49483, l='MpServer', x=139,77, y=53,03, z=274,75], EntityZombie['Zombie'/50204, l='MpServer', x=153,50, y=21,00, z=254,50], EntityPig['Pig'/208, l='MpServer', x=238,16, y=65,00, z=224,31], EntityPig['Pig'/209, l='MpServer', x=234,91, y=66,00, z=256,03], EntityZombie['Zombie'/50203, l='MpServer', x=152,00, y=21,00, z=255,56], EntityPig['Pig'/210, l='MpServer', x=246,72, y=72,00, z=279,59], EntityZombie['Zombie'/50202, l='MpServer', x=153,50, y=21,00, z=259,50], EntityCreeper['Creeper'/49535, l='MpServer', x=241,50, y=43,00, z=218,50], EntityPig['Pig'/233, l='MpServer', x=245,53, y=68,00, z=343,03], EntityPig['Pig'/231, l='MpServer', x=244,91, y=67,00, z=243,25], EntityCreeper['Creeper'/49001, l='MpServer', x=217,50, y=37,00, z=217,50], EntityEnderman['Enderman'/48220, l='MpServer', x=246,34, y=16,00, z=204,59], EntityChicken['Chicken'/228, l='MpServer', x=242,69, y=63,20, z=226,16], EntityChicken['Chicken'/227, l='MpServer', x=241,88, y=63,00, z=226,16], EntitySpider['Spider'/50001, l='MpServer', x=142,00, y=18,00, z=314,25], EntityPig['Pig'/254, l='MpServer', x=280,84, y=65,00, z=250,50], EntitySpider['Spider'/49999, l='MpServer', x=144,50, y=18,00, z=312,78], EntityPig['Pig'/252, l='MpServer', x=288,09, y=65,00, z=234,06], EntityPig['Pig'/253, l='MpServer', x=272,63, y=65,00, z=249,38], EntitySkeleton['Skeleton'/49753, l='MpServer', x=133,50, y=55,00, z=271,50], EntitySkeleton['Skeleton'/49752, l='MpServer', x=134,50, y=55,00, z=270,50], EntityZombie['Zombie'/49755, l='MpServer', x=174,50, y=59,00, z=279,50], EntityPig['Pig'/246, l='MpServer', x=268,91, y=64,00, z=258,47], EntityCreeper['Creeper'/49751, l='MpServer', x=163,41, y=60,00, z=263,31], EntityChicken['Chicken'/244, l='MpServer', x=260,56, y=67,00, z=238,41], EntityPig['Pig'/245, l='MpServer', x=264,91, y=65,00, z=244,06], EntityChicken['Chicken'/243, l='MpServer', x=257,47, y=65,00, z=225,44], EntitySpider['Spider'/50474, l='MpServer', x=275,17, y=25,00, z=286,50], EntitySkeleton['Skeleton'/50475, l='MpServer', x=276,66, y=25,00, z=286,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:440)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2298)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:844)
    at net.minecraft.client.main.Main.main(Main.java:93)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Mac OS X (x86_64) version 10.9.1
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 787987456 bytes (751 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
    AABB Pool Size: 2432 (136192 bytes; 0 MB) allocated, 2017 (112952 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 63
    FML: MCP v8.04 FML v6.2.19.789 Minecraft Forge 9.10.0.789 4 mods loaded, 4 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{6.2.19.789} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{9.10.0.789} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Eln{0.0.1} [Eln](bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.6
    LWJGL: 2.9.0
    OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-8.18.29, Intel Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 556 (31136 bytes; 0 MB) allocated, 282 (15792 bytes; 0 MB) used

**Comment by Dolu1990** [comment]
fixed <3
