### ISSUE TITLE
where to find the title and description to things and objects? for translation.

### ISSUE THREAD

**Issue by Leks543** [Electrical-Age/ElectricalAge#201]

**Comment by DrummingFish** [comment]
You don't want to start on that yet until the lang file stuff is sorted out. All the strings are scattered everywhere and there's no good way of translating them yet until the mod is sorted out.

**Comment by Leks543** [comment]
I tried to search for files, open them, which is reminiscent of the built-in wiki files can even translate it? translation modes become much more popular, I'm sure of it.

**Comment by DrummingFish** [comment]
I don't understand what you just said, sorry.

**Comment by Leks543** [comment]
built-in tutorial which files are? can even translate it?

**Comment by DrummingFish** [comment]
I can't remember which files but again there's no point really at this point in time until the lang system is set up.
