### ISSUE TITLE
Turkish

### ISSUE THREAD

**Issue by anar4732** [Electrical-Age/ElectricalAge#203]
Will it be translated Turkish?

**Comment by metc** [comment]
The mod is only available in English (items names, descriptions, etc.). For now, no "full" language files are available, so it cannot be translated to any other language.

**Comment by lambdaShade** [comment]
The mod is now partially translatable (block, items). GUIs will probably follow, if possible (because of text length issues).
Please note that we can't translate the game in Turkish (we don't speak that language)... but if you want, don't hesitate to do it !

**Comment by anar4732** [comment]
for some languages, you can get help from other mod makers?
Thank you for your interest
