### ISSUE TITLE
Typo in Eln.java

### ISSUE THREAD

**Issue by bloxgate** [Electrical-Age/ElectricalAge#207]
On line 334 of Eln.java:

``` java
public double electricalFrequancy, thermalFrequancy;
```

It should be Frequency, not Frequancy. Fairly minor, but it did stand out when I was fixing achievements. Probably a few other places that would need changing too.

**Comment by DrummingFish** [comment]
There are typos everywhere. It's not a problem. English isn't the original author's first language. Going through and fixing all of them would be pointless really as they don't affect anything.
