### ISSUE TITLE
High Power Receiver Antenna Recipe Conflict

### ISSUE THREAD

**Issue by Sanadorn** [Electrical-Age/ElectricalAge#217]
The High Power Receiver Antenna recipe conflicts with the Medium Power Receiver Antenna. They use the exact same resources in the same pattern according to the Mod Wiki (X Key) which makes the High Power Receiver antenna impossible to craft.

**Comment by Dolu1990** [comment]
Thanks for issue, i fix that now.

**Comment by metc** [comment]
Fixed in commit 8d4b9982f6eca74366d94d560e03f143440f96f2. Will be available in the next release.
The `High Power Receiver Antenna` recipe has changed and is now:

![craft](https://cloud.githubusercontent.com/assets/229670/7220465/439784ba-e6c8-11e4-93e6-21936763c113.png)
