### ISSUE TITLE
Solar, Wind, and Water generators producing voltage but not power

### ISSUE THREAD

**Issue by dandelion25** [Electrical-Age/ElectricalAge#221]
Resonant Rise 3 version 3.2.5.3, they're all generating the proper voltage and everything, but no power is being generated. I'm thinking there might be some incompatibilities, but I'm not completely sure.

**Comment by bloxgate** [comment]
Which machine are you trying to power. What is your voltage, wattage, and current?

**Comment by dandelion25** [comment]
I am trying to power 50 volt machines, and the resulting voltage is 59, while wattage and current are 0.

**Comment by dandelion25** [comment]
For solar panels, the voltage is 14.9, and for the rest, it's 0 & 0.

**Comment by cm0x4D** [comment]
This is a complete normal behavior of generators without any load. Are you sure that the machine is turned on (has some work to do), otherwise they do not consume energy, thus no current is drawn from the generator. Try a lamp to ensure that you have a load for your generator(s).

**Comment by dandelion25** [comment]
Yep, solved the problem. Thank you!
