### ISSUE TITLE
crash when trying to load world

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#222]
I can't Play my world anymore. when I try to load  it then minecraft crashes and I see this text in the launcher:  http://pastebin.com/3Pi4jtug
Other worlds are working without any Errors.
I tried removing ELN, but it still crashes :(

**Comment by nanakisan** [comment]
If you removed ELN and the world is still crashing. Then chances are it's actually IC2 as noted here
at ic2.core.TickHandler.onWorldTick(TickHandler.java:79)  
The energy converter block might be having a conflict with IC2. Chances are IC2 thinks the block still exists and is crashing cause of it.  

A simple fix (but might make you lose stuff) is to edit the forge.cfg file. There are two lines in it that you must set to true.  
Locate these lines and set false to true and run the world once. Then immediately close minecraft and change these back to false.

```
# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
B:removeErroringEntities=false

# Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
B:removeErroringTileEntities=false
```

That should theoretically erase the tile entities in your world that are causing the NPE.

**Comment by yannic312** [comment]
Thank you for that, it worked :)
