### ISSUE TITLE
adventure compatibility for map

### ISSUE THREAD

**Issue by anar4732** [Electrical-Age/ElectricalAge#224]
I'm a mod pack is in this mode into.
making an adventurous map hoped.

In an episode of "800V protection turret '' I use.
inaccessibility to the turret contains the adventure mode.
inaccessibility to enventer.
and
cables. buttons. switches. machines. like everything
It can not be broken in the adventurous mode.

I know I could use a lot of puzzles ape with these instruments.

---

Not this text was translated by google.

**Comment by lambdaShade** [comment]
...sorry, but Google Translator completely destroyed your original message :-(

**Comment by anar4732** [comment]
I'm making a mod pack and resides in this mode
an adventure map.
my problem is that the players know everything rent in Adventure mode.
in this mode cables,machines, and especially turrets
need to be broken in Adventure mode.

**Comment by AMIDIBOSS** [comment]
He means that eln stuff can be broken in adventure mode, right? And they shall be not.
Is that what you mean?
