### ISSUE TITLE
NEI crash when looking up recipes for Tungsten Ingot

### ISSUE THREAD

**Issue by Haggle1996** [Electrical-Age/ElectricalAge#226]
Client crash when trying to look up recipes for Electrical Age's Tungsten Ingot. 

http://pastebin.com/CngEmvZk

**Comment by bloxgate** [comment]
Does this happen when you use the in-game wiki?

**Comment by Haggle1996** [comment]
No. :) But most people explore a mod through NEI, particularly in my public pack. I know I'll get bug reports out the wazoo.

**Comment by bloxgate** [comment]
Just tested this with ELN 1.9 r47 and the latest versions of NEI + CodeChickenCore for 1.7.10, didn't crash and was able to see the recipe to smelt tungsten/ore dust into ingots. Unless you mean getting what the ingot is used in, just make sure that NEI and CodeChickenCore are both up to date.
