### ISSUE TITLE
DC/DC converter instead of transformer

### ISSUE THREAD

**Issue by serathius** [Electrical-Age/ElectricalAge#237]
I see that currently it's possible to transform DC using transformer, which should not be possible because to induce voltage in secondary coil alternative current is needed. So I propose more realistic fix DC/DC converters, they are pretty advanced electronics, compared to simple Transformer. Or maybe they will be useful for future grid type differentiation (DC/AC).

**Comment by Dolu1990** [comment]
You can create by yourself a DCDC by using relay (in H bridge configuration or something else, don't use diode, they don't work very in the mod)
Then add a inductor, a command logic to the H bridge, and it's done ^^
Do not hesitate to put 100 H inductor.

**Comment by serathius** [comment]
Cool, may try that.
But fact remains that transformer cheats!

**Comment by serathius** [comment]
Ok I made DC/DC Converter 200V/50V And it works :P.
Using signal processor I added ability to set output voltage.
Awesome.

**Comment by Dolu1990** [comment]
There is a lot of possiblilty by this way ;)
Do you have try bidirectional current regulation to manage battery ?

**Comment by serathius** [comment]
I used buck converter.

**Comment by cm0x4D** [comment]
I agree. The transformator feels a little alien in this DC world.
We could change the 3D model a little bit to match rather an industrial DC/DC converter, but still the number of installed cables determines the voltage levels. It would be sometimes even desirable to be able to convert by a factor greater than 4 for example to connect a 50V network to a 800V network directly without the need to place 2 transformators.

**Comment by MFernflower** [comment]
^ I agree fully the transformers should be replaced with DC/DC converters and the inductor within the converter board would determine the output.

**Comment by lambdaShade** [comment]
This symbolic and "preliminary" transformer model will be replaced by a DC/DC converter (with visible transformer) model in the next release.

**Comment by cm0x4D** [comment]
Done
