### ISSUE TITLE
Better oredict support

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#24]
ingotPlomb should be registered as ingotLead
different plates should be register as plateIron, plateSilicon and etc.
Mercury as quicksilver for TC4 
Rubber as itemRubber or ingotRubber for IC2

Use oredict in item recipes using stuffs above

Also you can automatically add ores to the xray scanner's list using their "ore" prefix

**Comment by nickdutto** [comment]
^ I agree.

**Comment by Dolu1990** [comment]
I do ^^

**Comment by Dolu1990** [comment]
Dictionnary fix are done.

but "Also you can automatically add ores to the xray scanner's list using their "ore" prefix" ?
You speak about the eln.config file ?

**Comment by wormzjl** [comment]
All types of ores are registered in the oredict as ore-something
You can let the mod to scan the ore dictionary to find out stuffs registered with such prefixe and add them to the scanner's list.

**Comment by Dolu1990** [comment]
Ahhh to find automaticaly others mod ore. Yes it's a enhancement, and now it implemented XD
I need to test it with a real mod ^^

**Comment by Dolu1990** [comment]
That work
