### ISSUE TITLE
Diode resistance

### ISSUE THREAD

**Issue by serathius** [Electrical-Age/ElectricalAge#241]
I have parallel circuit with one branch with conducting diode. 
It results in current split 233mA(without diode) 167 mA(with diode).
Without diode it would be 200mA 200mA.
Does diode has additional resistance not mentioned in tooltip?

**Comment by Dolu1990** [comment]
Yes diode add a additional resistance because in fact, i it's not a good idea to simulate component that doesn't have resistance, else it could create infinit current => overflow => NaN everywhere
