### ISSUE TITLE
Diode blows up when connected to full voltage

### ISSUE THREAD

**Issue by serathius** [Electrical-Age/ElectricalAge#242]
I have two cases with same circuit for diode 10A and diode 25A(didn't test signal):
source(50V), diode conducting, receiver(lamp 125 ohm)
Predicted current 400mA

When I set 50V from 0 on source diode explodes.
When I set first 1V from 0, and later 50V circuit remains stable, with correct current.

**Comment by serathius** [comment]
It's thermal exposion on diode. 
removing ThermalLoadWatchDog for diode helps.

**Comment by Dolu1990** [comment]
Hi,
Diode is something that don't work very well, because it's not a linear component, maybe i have to rework a little bit his comportement and move his beavoral into the iterative solver
