### ISSUE TITLE
why infinite voltage?

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#247]
There is infinite voltage in the mod, when you set 9999999999999999999 into electrical source it says this:
![2015-06-12_14 46 20](https://cloud.githubusercontent.com/assets/11148623/8130272/61caa3fe-1111-11e5-8462-4405eb7a6398.png)
why is this possible when no cable can hold that?

**Comment by Dolu1990** [comment]
Because of extrem value, the calcuation fail, and put infinity/nanKA
It's not a bug, it's just there is a range for every things ^^
