### ISSUE TITLE
Voltage Naming

### ISSUE THREAD

**Issue by serathius** [Electrical-Age/ElectricalAge#249]
Let's fix voltage naming

Network types by voltage:
- Extra Low Voltage - < 50V
- Low Voltage - 50V - 1kV
- Medium Voltage - 1kV - 60kV
- High Voltage - 60kV - 220kV
- Highest Voltage 220kV - 1100kV

**Comment by ghost** [comment]
Imho in real electronics 50V is not "low" voltage. I would call Low voltage <15V at most...

**Comment by Dolu1990** [comment]
The actual voltage scaling in electrical age is a part of legacy from the old simulation system.
Any way actual scaling add some gameplay with cable length and voltage drop on them.
The goal is to chalange the player to make a good network topology. If you insert things like 100 KV, it's just totaly "cheated"

All is a balance between power consumption, cable length challange, and fun :)

**Comment by Baughn** [comment]
Ah, I see you go by the Dwarf Fortress definition of "fun". :D

I don't have a problem with 3.2kV being the max, per se... but I do occasionally want to move more than 15kW.
