### ISSUE TITLE
NEI support for various machine recipes

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#25]
A build-in NEI support will allow player to find recipes more easily.
Specifically macerator, compressor, magnetizer and plate machine recipes

**Comment by Dolu1990** [comment]
Actualy a ingame helper "wiki" is coded, you can press x key to open it, But in any case a bult in NEI support is a good thing, it's juste i don't know how that work, and that need time ^^

What do you think about the x key ?

**Comment by wormzjl** [comment]
If you want to add an ingame wiki it's better to make a book instead of using a hotkey, since in a multimod environment there wouldn't be too much free keys avaliable.

**Comment by Dolu1990** [comment]
Ahhhh the book is not a bad idea ^^ i talk about that with other contributor :)

**Comment by DrummingFish** [comment]
Is this something that's being pursued?

**Comment by Baughn** [comment]
This currently works, so I guess...

**Comment by AMIDIBOSS** [comment]
Btw. Being honest the ingame wiki is kinda crap. We could use sth. like ingame wiki. (not like it's just as ez az copying IE)
