### ISSUE TITLE
Version 1.10-r48

### ISSUE THREAD

**Issue by BeerCav** [Electrical-Age/ElectricalAge#251]
Just updated to current beta version in my 6six6 tester instance and it seems to be saving all worlds like every 2 minutes. I've looked through all configs and can't seem to find any setting to reduce or even disable this.

**Comment by BeerCav** [comment]
Here, I made a pastebin so you can see what I mean. I copied from the initial world load to right before I died lol. I hope this comes in some sort of help for you guys.
http://pastebin.com/10Pn9mVM

**Comment by Dolu1990** [comment]
It's a normal beavoral :) just i had forget to remove printf XD

Thanks for issue ^^
