### ISSUE TITLE
Please, add compatibility with liquid fuels.

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#253]
It would be nice to have the ability to fuel the stone heat furnace with liquid fuels, especially with ethanol from Forestry.

**Comment by Dolu1990** [comment]
Hi,
Yes i agree, Is there a forge interface that allow me to identify them easly ?

**Comment by ivangouba** [comment]
Forge interface??

**Comment by Dolu1990** [comment]
Haa sorry, i asked about a common API to get if a item is fuel, i'm pretty sure there is :)

**Comment by ivangouba** [comment]
I don't know, sorry. I'm not very good with programming and all this things. Have you returned to the development of the mod?

**Comment by Dolu1990** [comment]
No problem, these time yes, a little bit ^^

**Comment by bloxgate** [comment]
Forge does have a liquid dictionary similar to the ore dictionary. Don't know how to use it though.

**Comment by Baughn** [comment]
Maybe Railcraft has an API for this?

EDIT: It does, https://github.com/CovertJaguar/Railcraft-API/blob/master/mods/railcraft/api/fuel/FuelManager.java

**Comment by bloxgate** [comment]
Well, considering each mod may define a fuel differently we'd have to use each mods API. You specifically requested Forestry and they do have a fuel manager API that contains a reference for each of its fuels.
Edit: Yep the API has a bunch of hash maps for the different fuel types, you could check if a fluid is say a generator fuel that way.

**Comment by Baughn** [comment]
If the goal is to e.g. "burn every fuel that a railcraft boiler will burn", then using Railcraft's API is just fine, but I guess it'd make sense to have a fallback hard-coded list so you can e.g. use Buildcraft fuel even without Railcraft installed. It's a rare tech-pack that doesn't have it, though.

That said, I think it'd make sense to reserve liquid fuels for larger (multiblock) turbines, just so there'd be some way to get more power; right now I'm using about 20kW continuous. An 800V turbine?

(Also, oil-cooled high-voltage lines. I'm actually fiddling a bit with the code, to see if I can implement some.)

**Comment by ivangouba** [comment]
Yeah, multiblock turbines would also be very good, but Dolu said that his team was too small to make that kind of things. Anyway, I would be thankfull if anybody could implement liquid fuels.

**Comment by Baughn** [comment]
@ivangouba 
Well, the mod is open-source. My time is limited, but we'll see what happens; I'm better at things like interfacing with MC/Forge than developing electrical network code anyway. :-)

Though now that I think about it, modifying Big Reactors' turbines to get an EA output option is probably my best choice. _That_ sounds like it could be done in a not-too-large amount of time.

**Comment by bloxgate** [comment]
@Baughn Big Reactors already outputs RF, and we have an ELN to Other Converter. It would probably be easier to make an other to ELN converter than to make Big Reactors output an entirely different type of power.

**Comment by bloxgate** [comment]
Going back to the specific example of forestry: as of ForestryMC/ForestryMC@9ade0b8 (so the latest experimental builds), it is possible to check whether or not forestry contains a fluid as a fuel.

``` java
if(FuelManager.generatorFuel.containsKey(fluid)){
    //do stuff
}
```

Then if that fluid is a generator fuel, we can get the GeneratorFuel for it which contains its burn rate and EU produced.

``` java
if(FuelManager.generatorFuel.containsKey(fluid)){
    GeneratorFuel fuel = FuelManager.generatorFuel.get(fluid);
    int rate = fuel.rate; //How many ticks it takes to consume 1u of fuel
    int eu = fuel.eu; //EU per tick
}
```

We could then do the conversion from EU to Watts(?) and output that from the furnace/turbine/whatever.

**Comment by Baughn** [comment]
@bloxgate I think that would neglect what attracted me to EA in the first place, namely its realism. RF power can never blow up; an other-to-ELN converter would presumably act roughly like the power receivers, but we can do better. The Big Reactors turbine has inertia, efficiency bands, really everything I'd expect from an ELN equivalent; by interfacing directly with it, I can make the BR-to-ELN block take the _entire_ power output of the turbine.

BR still has enough controls for that to be safe-ish, but you'll need to be clever about it. Which is exactly what I want. :)

**Comment by bloxgate** [comment]
@Baughn If I understand what your saying, you'd want big reactors to have an "EA Port" that outputs power in EA's units kind of like its existing output ports?

**Comment by Baughn** [comment]
@bloxgate Exactly. I'd need to think about the details a bit, but I'm imagining it working somewhat like the microwave power receivers.

**Comment by bloxgate** [comment]
@Baughn I see. Well, best of luck in figuring out how to do it.

**Comment by cm0x4D** [comment]
There will be a fuel heat furnace that is compatible with forge fluids: #550

**Comment by bookerthegeek** [comment]
In the thought of BR... Nuclear Craft would be a better fit, and should not be to hard to implement a block specifically to output ELN power.

**Comment by Baughn** [comment]
I think we can call this closed. :D

It'll be in the next release, which is coming this weekend.
