### ISSUE TITLE
Add Others to Volts(ELN) Converter

### ISSUE THREAD

**Issue by Levvy055** [Electrical-Age/ElectricalAge#264]
There is ELN to Others converter, but there is no Other to ELN converter.

**Comment by anar4732** [comment]
exactly!

**Comment by bloxgate** [comment]
Wasn't there an issue about this in the past where they said they intended to keep it this way?

**Comment by egeis** [comment]
Too overpowering to add other to eln.  Risk is removed in my experiance with a modded version of this mod.  If you dont like generators exploding then just play thermal expansion.  Add some rf lights if you want powered lighting.

**Comment by anar4732** [comment]
This option may be, may be set in the config.

**Comment by egeis** [comment]
i dont think its in the config to reverse the process. I worked with someone who had a version of this mod designed for use in TerraFirma craft that had Other mod power to ELN but it was two over powering, and cheap to setup.  Take a look through the forks, if you cant find one, if not the source is licensed under copyleft (LGPL) nothing stopping you from taking the existing converter classes, duplicating them and reversing the process, RF in to ELN out.

**Comment by Levvy055** [comment]
It woudn't be overpowered if we discuss RF or EU as power. There could be gui in convertet to change relation voltage / current. P=I_U.  To make it comparable there should be also factory value so the final pattern will be like that P=k_U*I
