### ISSUE TITLE
Dúvida de utilidade do item [Modbus RTU]

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#268]
Desenvolvedor deste mods eu não sei ate agora como funciona e utiliza o item -- Modbus RTU --
Poderia fazer um video ou explicar na wiki do mod este item de preferencia, para ter uma noção não entendo nem o funcionamento nem para que serve. Por favor gostaria muito saber a utilidade deste mod.

Tenho um canal no youtube e faço tutoriais deste mods em portugues(Brasil) eu não compreendi o item Modbus RTU

**Comment by bloxgate** [comment]
Google translate to English:

Developer of this mods I do not know so far how it works and uses the item - Modbus RTU -
Could make a video or explain the mod wiki this item preferably, to get a sense do not understand or operation or for serving. Please'd love to know the usefulness of this mod.

I have a youtube channel and make tutorials of this mods in Portuguese (Brazil) I did not understand the Modbus RTU item

**Comment by ghost** [comment]
Bloxgate poderia me ajudar a aprender e a utilizar o item -- Modbus RTU -- =D

**Comment by bloxgate** [comment]
Sorry, I don't know how the Modbus RTU works.

**Comment by ghost** [comment]
Oky =(, Item complicado, não? kkkk

**Comment by cm0x4D** [comment]
Modbus RTU is very very special...

It lets you interact with the Minecraft world using ModbusTCP, a mature and well supported field bus protocol. If you do not know Modbus, you probably won't want to use that block.
