### ISSUE TITLE
ForgeMultipart support for cables and components

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#27]
As the title suggests

**Comment by Dolu1990** [comment]
ForgeMultipart ? unknow word, ForgeMultipart  exploration is pushed in my task queue

**Comment by Dolu1990** [comment]
Ahhh, for multipart, it's actualy to late to wear stuff on ForgeMultipart. actualy all is done with SixNodeBlock. But in any case,  it was not a bad idea to show that ^^
