### ISSUE TITLE
connection missing

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#270]
At wind turbine, there is a small Piece of wire missing when you connect it.
![2015-07-20_12 05 58](https://cloud.githubusercontent.com/assets/11148623/8773776/50e2a738-2ed7-11e5-8a97-5052099ce3bc.png)

**Comment by ghost** [comment]
Cara isso só é um detalhe, da para relevar qual mod que não tem este tipo de erro.
