### ISSUE TITLE
Cross Compatibility

### ISSUE THREAD

**Issue by JDuskey** [Electrical-Age/ElectricalAge#273]
I would love to use this mod on my server (I especially love the energy meter!) but this mod really needs to be able to accept energy from other mods. Would that be available?

**Comment by egeis** [comment]
You can output energy from you system to other mods already.  No accepting other mods in is a design decission i believe i read on an earlier request.  I used a modified version that allowed RF to be coverted to volts and amps and you can bypass energy production with ease.  It was to over powering considering the converter would not over generate power and the power system generating the rf would never explode. The only mod id like to see get accepted as an input is rotarycraft.  A poorly designed system their can fail just as bad as EA.

**Comment by JDuskey** [comment]
Where was this modified version?
