### ISSUE TITLE
[Request] Turn off "life"

### ISSUE THREAD

**Issue by aschmois** [Electrical-Age/ElectricalAge#274]
If possible a simple boolean config for the life in batteries, bulbs, etc. would be amazing. The life in these objects is an annoyance when building adventure maps.

**Comment by yannic312** [comment]
you can Switch off things like battery life, lamp aging etc with /eln aging 0, you will
just have to type that into ingame Chat console.

**Comment by aschmois** [comment]
Ah ok, is this a permanent solution? I won't have to type that command every time I log into the server right?

**Comment by yannic312** [comment]
Yes, it should be permanent :)

**Comment by aschmois** [comment]
Thanks! One last question, is there a command list somewhere? /eln help doesn't print anything out.
