### ISSUE TITLE
Probes maybe not working

### ISSUE THREAD

**Issue by bwdysart** [Electrical-Age/ElectricalAge#275]
When I try to add a probe the wires won't connect through it. I don't know if I'm doing it wrong or if it's a bug. Here's a screenshot of it not working.
![2015-08-04_08 58 13](https://cloud.githubusercontent.com/assets/13643072/9061186/fac68218-3a87-11e5-8044-c4a08af42d7c.png)

**Comment by bloxgate** [comment]
Works fine for me, did you remember to put a low voltage cable into the slot IN the probe?

**Comment by cm0x4D** [comment]
This definitively works if a cable is in probe's slot.
