### ISSUE TITLE
[Bug] Cable disconnects on server restart (advanced energy meter)

### ISSUE THREAD

**Issue by aschmois** [Electrical-Age/ElectricalAge#278]
**Build r50**
Broken Connection:

![Broken Connection](http://i.imgur.com/27mU5RO.png)

Correct Connection:

![Correct Connection](http://i.imgur.com/C78kn8e.png)

Can be fixed by removing and adding the medium voltage cable in the meter's cable slot.

Un-hidden cables:
![Un-hidden Cables](http://i.imgur.com/dueKOQ1.png)

**Comment by aschmois** [comment]
Update: The problem seems to be colored cables only. All cables that connect with a non-colored cable or a machine get disconnected on server restart

**Comment by cm0x4D** [comment]
I could not reproduce the problem with the current version (1.13.0), so I close the issue, feel free to reopen it if you still have this issue with the actual version.
