### ISSUE TITLE
Strange config for xray scanner

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#28]
For example the default id for tungsten ore is 227:5 but in the config file it's shown as:
    I:EATungsten <
        20707
        20
     >
Is this a bug?

**Comment by Dolu1990** [comment]
it (5*4096 + 227) = 20707
that could be fix with a betther and more user friendly syntax like "227:5" string

The second integer is the yellow factor of this type of ore ^^
