### ISSUE TITLE
[Feature-Request] Fuses

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#283]
Can you add fuse component? It must be relatively cheap, and disappear on overload without explosion. This will be very useful for experimenting in survival mode!

![fuse](https://cloud.githubusercontent.com/assets/12214069/9423643/ced69f42-48d5-11e5-9a9d-0166d6af1624.jpg)

**Comment by ghost** [comment]
Boa ideia também apoio acho interessante e bem util.

**Comment by TheAmazingSpy** [comment]
Yes! But not just 'disappear', explode, with no damage, and some yellow sparks can come out and some light black smoke can come out.

**Comment by anar4732** [comment]
good idea

**Comment by cm0x4D** [comment]
Done in develop.
