### ISSUE TITLE
Seems like life in hours is missing for the Carbon Incandescent lamp in the config?

### ISSUE THREAD

**Issue by pharaun** [Electrical-Age/ElectricalAge#289]
I bumped the lifetime on some of the incandescent lamps to 24h and the economic lamps to 96h, yet in game the carbon version of incandescent lamp shows up as 8h while the other 2 lamp types will show up as 24h and 96h is this intentional?

**Comment by ghost** [comment]
Isso não é bem um problema ele só não disponibilizou a configuração. Mas concordo espero que ele add. =D

**Comment by lambdaShade** [comment]
Done : https://github.com/Electrical-Age/ElectricalAge/commit/a98225ea5d64fe4d95e0ecd58b833fc3c3b2d5d7.
