### ISSUE TITLE
Crash when used on a server

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#29]
Seems to be calling a client side class
http://pastebin.com/sffgDxaY

**Comment by Dolu1990** [comment]
Hi, i have the same bug, I don't have use server from long time ago XD
Thanks for feed back, i give you information when it's fixed and upload a new release.

**Comment by Dolu1990** [comment]
There is the root of apocalypse !

``` java
    public static double clientDistanceTo(Entity e) {
        if(e == null) return 100000000.0;
        Entity c = Minecraft.getMinecraft().thePlayer;
        double x = (c.posX-e.posX),y = (c.posY-e.posY),z = (c.posZ-e.posZ);
        return Math.sqrt(x*x+y*y+z*z);
    }
```

BUUUUUURN

**Comment by Dolu1990** [comment]
Back, New release that fix that is on https://github.com/Dolu1990/ElectricalAge/releases/tag/BETA-1.1.2
i have tested in eclipse, normaly all is ok. can you test it ? If any other or same issue pop, Give me feed back : D
