### ISSUE TITLE
Pelton wheel

### ISSUE THREAD

**Issue by metc** [Electrical-Age/ElectricalAge#3]
Add a Pelton wheel item in the game mod to produce power using the water.
In Minecraft the water is an infinite "resource", so the weel must not produce to much energy.

**Comment by Dolu1990** [comment]
Added in 1.1.2

**Comment by cm0x4D** [comment]
![2014-04-30_14 00 01](https://cloud.githubusercontent.com/assets/6661117/2840941/1d0a51ae-d05f-11e3-9f86-985c35a49dba.png)

**Comment by Dolu1990** [comment]
enjoyable ^^

**Comment by metc** [comment]
:+1:
