### ISSUE TITLE
Moving AutoMiner tile entities crashes server

### ISSUE THREAD

**Issue by perkinslr** [Electrical-Age/ElectricalAge#305]
When I try using RemainInMotion's frames to move an AutoMiner, I get a ClassCastException.  It seems that ELN no longer properly saves its entities to NBT, I assume this is related to ELN now saving its state independently from the normal save/load system, but while I understand how it works well enough to fix the crash, the tile entities vanish during the motion.

https://gist.github.com/perkinslr/79982dff867c4349d227

**Comment by Baughn** [comment]
This probably cannot be fixed, short of using separate tile-entities for each block.

Which is something I was planning to do anyway, eventually. I'm not sure it'll even be fixed then, though.

For the moment, I recommend you blacklist Eln blocks in the RIM config.

**Comment by perkinslr** [comment]
I have it frusteratingly close to working...  If you move a line of wire, only the last one in line doesn't survive the trip.  If there's a SixNode already at the destination, everything's happy.  Something is setting the block to air and defying my attempts to reset it, and it's not DelayedBlockRemove, so I don't know what's happening...  I'll keep poking at it.

**Comment by perkinslr** [comment]
So, I have it partially working, SimpleNodes survive the trip.  The issue isn't from the multiple node types all using the same block, it comes from the custom save system used by ELN.  As far as I can find, there's no good way to save the node, calling writeToNBT doesn't cut it.  I think I'll see if I can reverse the commits that moved to a non-standard save and see what happens.
