### ISSUE TITLE
Datalogger/oscilloscope thing's gui is bugged (1.10 r50)

### ISSUE THREAD

**Issue by MFernflower** [Electrical-Age/ElectricalAge#309]
![](https://cloud.githubusercontent.com/assets/3164942/10474535/b93ea31a-7205-11e5-8a8c-823991372b5d.png)

**Comment by ajthemacboy** [comment]
I think I saw a similar issue on the SKCraft launcher: https://github.com/SKCraft/Launcher/issues/95

A possible solution is found in a reply. This could be completely different though.

**Comment by lambdaShade** [comment]
The static GUIs in Minecraft.....
I'll correct that, thank you a lot.

**Comment by lambdaShade** [comment]
Done + slightly enhanced : https://github.com/Electrical-Age/ElectricalAge/commit/8a764da01a6ace8ee73bb78fb54a95c3f6bea88a
