### ISSUE TITLE
Add sounds

### ISSUE THREAD

**Issue by lambdaShade** [Electrical-Age/ElectricalAge#31]
TODO : Produce some sound files for some electrical/mechanical objects...

**Comment by BroBeans** [comment]
That's actually, a pretty good idea! I'll get stared on developing some sounds, present them to Dolu, and see what he thinks.

**Comment by Dolu1990** [comment]
Yes XD Sound could be greate, and not hard to add ingame ^^

**Comment by Dolu1990** [comment]
Sournd added to relay switch breaker

**Comment by cm0x4D** [comment]
https://www.freesound.org
Check out this site, free sounds licensed under Creative Commons...

**Comment by cm0x4D** [comment]
Missing sounds ordered by priority:
- Macerator
- Compressor
- Plate Machine
- Auto Miner
- Transporter
- Transformer (high load)
- Electrical Furnace
- X-Ray Scanner
- Electric Timer
- Modbus RTU (error beep)

I will start on this list, comment if I forget any element that needs sound effects...

**Comment by Dolu1990** [comment]
Neon blinking ! <3 (AGsys tm)

**Comment by cm0x4D** [comment]
Good one!
