### ISSUE TITLE
Crash in GenericItemUsingDamage.getDisplayName() -> Bootloop

### ISSUE THREAD

**Issue by NEckes** [Electrical-Age/ElectricalAge#319]
The server world crashed while noone was online. 
Maybe while item despawning. 
Using the modpack DifficultRealism. 
Mods in stacktrace:
- MobiusCore
- FastCraft

First crash report: http://pastebin.com/2jbPsumm
Crash reports created in bootloop: http://pastebin.com/T3db5n9e

**Comment by bloxgate** [comment]
Can you try to start the server without FastCraft?

**Comment by NEckes** [comment]
Still the same error. But maybe now the world is corrupt...

**Comment by bloxgate** [comment]
I suppose that's always a possibility.

**Comment by bloxgate** [comment]
Hmm, I just checked and GenericItemUsingDamage doesn't have a getDisplayName() method. I guess MobiusCore and FastCraft aren't checking for this possibility.

**Comment by Baughn** [comment]
IIRC, it subclasses a class from base Minecraft which does have that method?

**Comment by bloxgate** [comment]
Not sure, I think its returning null or something that's breaking MobiusCore or FastCraft.

**Comment by cm0x4D** [comment]
Info has been removed
