### ISSUE TITLE
Some blocks can only be placed facing one direction

### ISSUE THREAD

**Issue by ajthemacboy** [Electrical-Age/ElectricalAge#323]
First, let me say this is the best mod I've ever seen. The realism, the sounds, the animations are all perfect.

Some blocks can only be placed facing one direction, such as data loggers, voltage probes, voltage switches, signal processors (although that's a minor issue for what the block does), and probably others I don't know about.

You can rotate them with a wrench, but they should be rotated based on the direction you're facing when placed.

Aside from that I'd like to make a suggestion for conveyor belts, which I think would be awesome for production.

**Comment by cm0x4D** [comment]
Fixed in develop branch, probably included in next release
