### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by ajthemacboy** [Electrical-Age/ElectricalAge#324]
I'm getting this crash: https://gist.github.com/ajthemacboy/a2fe48f96d263fd4367b

I thought I read somewhere that EE isn't compatible with either Mod Tweaker or Mine Tweaker, but that doesn't seem to be the problem since I removed both.

**Comment by bloxgate** [comment]
From what I can tell it appears that you might've build Electrical Age from source, as you're using r51 which hasn't been released yet. Can you try running gradlew build --refresh-dependencies please?

**Comment by ajthemacboy** [comment]
I did indeed compile from source, since the last release was fairly old. --refresh-dependencies fixed the problem, thanks!
