### ISSUE TITLE
Fusable cables

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#325]
An idea I thought sounded nice...

Fusable wires. They work like breakers, but are single-usage.
- The recipe is (cable - <uninsulated copper cable> - cable), for LV and MV fusable cables. No (V)HV version.
- SixNode, of course. Custom model, with the fused/broken state visible as a broken wire. Heat can be made visible in the same manner as the large rheostat. (Um... did I merge that yet? ^^;)
- Can be reset by right-clicking with a piece of uninsulated copper cable. This consumes the cable.

I'll look at implementing this whenever, probably January.

**Comment by cm0x4D** [comment]
Simple lead fuses have been added, feel free to reopen the issue if you still like this kind of fuses
