### ISSUE TITLE
Battery 

### ISSUE THREAD

**Issue by CarolAnthony** [Electrical-Age/ElectricalAge#327]
I have problem with batterys im using an ground cable electrical source and cost battery when i search in youtube i found a tutorial video so i used it but it dint work its a bug ??? or something the battery will decrease his energy and it will explode

**Comment by Baughn** [comment]
It's a little difficult to tell what you're doing, so a screenshot would be helpful, but in general--

If you connect anything with capacitance (that's batteries, capacitors, transformers, inductors to a degree...) to a very different potential (voltage), it'll overload and probably explode. Connecting a battery directly to a ground cable (on both sides) will certainly make it explode.

There's a reasonable tutorial at http://wiki.electrical-age.net/index.php/Tuto_electrical.

If you have further questions, please visit the IRC channel, #electricalage on irc.rizon.net.

**Comment by CarolAnthony** [comment]
Ok thanks for fast responding :+1:
