### ISSUE TITLE
Server console spam

### ISSUE THREAD

**Issue by wormzjl** [Electrical-Age/ElectricalAge#33]
After installing this mod on the server I got the following console spam

09.05 12:10:01 [Server] INFO ticks 30 us  E 15  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:10:01 [Server] INFO ticks 31 us  E 15  T 3  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:10:00 [Server] INFO ticks 29 us  E 15  T 2  S 6    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:10:00 [Server] INFO ticks 27 us  E 14  T 2  S 6    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:59 [Server] INFO ticks 33 us  E 17  T 2  S 8    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:59 [Server] INFO ticks 35 us  E 16  T 2  S 10    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:58 [Server] INFO ticks 30 us  E 16  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:58 [Server] INFO ticks 29 us  E 15  T 2  S 6    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:57 [Server] INFO ticks 31 us  E 16  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:57 [Server] INFO ticks 31 us  E 16  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:56 [Server] INFO ticks 31 us  E 15  T 2  S 8    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:56 [Server] INFO ticks 31 us  E 17  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:55 [Server] INFO ticks 33 us  E 17  T 2  S 8    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:55 [Server] INFO ticks 35 us  E 17  T 3  S 9    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:54 [Server] INFO ticks 35 us  E 17  T 2  S 9    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:54 [Server] INFO ticks 28 us  E 14  T 2  S 6    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP
09.05 12:09:53 [Server] INFO ticks 33 us  E 17  T 2  S 7    0 EB    0 EL    0 WL    0 EC    0 WC    0 EP    0 TL    0 TC    0 TP    2 SP

**Comment by Dolu1990** [comment]
I must add a boolean into configuration file of mode to enable/disable that ^^
default is disable of course

**Comment by Dolu1990** [comment]
done, in next release
