### ISSUE TITLE
Maior Produção de Energia

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#333]
Ola, criador do Mod Electrical Age,
Gostaria de sugeri uma melhoria para seu mod.
Gosto bastante do seu mod, alem de ser bem realista e muito bom de jogar, adiciono em varios dos meus modpack e gravo videos e serie em meu canal: https://www.youtube.com/user/whilebr.

Sugiro que melhore a produção de energia isso para todas as formas de produção na sua devida proporção, sim aumente. Porque é muito pouco o que este mod produz para um nivel de mod tecnico como este. Alem disso as transmissão de energia a grandes distância se torna muito complicada, por mais que seja empregada a tecnica de aumentar a Tensão(Volts) atravez de transformadores distancias como 16, 32 blocos se torna inviável ficar utilizando sempre transformadores, comparando com outros mods como Industrialcraft, mekanism, thermalExpansion, e entre outros.

Por favor, ajuste a produção de energia e a distância de transmissão.

Com esta melhora este mod ficaria mais competitivo e nos niveis dos mods citados porque por em quando ele não esta tão util assim em energia como os outros.

Uma Sugestão para melhorar o mod porque adorei este mod e sigo ele desde a primeira versão e gostaria de ajudar no desenvolvimento testando ele =D

**Comment by ghost** [comment]
Você sabe que o criador do mod não fala português né?
Speak English, man!

**Comment by lambdaShade** [comment]
Can be now tuned through "Eln.cfg" (see key "cableRsFactor").
(Since https://github.com/Electrical-Age/ElectricalAge/commit/3bdcedb218f23a81053566ef6ec5cc3b594c96f1, for release r51)
