### ISSUE TITLE
WAILA integration adds mandatory mod dependencies

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#336]
```
[21:56:42] [Client thread/ERROR]: The mod NotEnoughItems (Not Enough Items) requires mod versions [CodeChickenCore@[1.0.6,)] to be available
```

![bildschirmfoto 2015-12-08 um 22 00 08](https://cloud.githubusercontent.com/assets/6661117/11668396/45b688a4-9df7-11e5-9c50-bb1e4f02c8a1.png)

It seems that the WAILA integration adds a non optional dependency to other mods. Would it be possible to make that dependency optional?

**Comment by bloxgate** [comment]
EDIT: Scratch that, appears to be a version mismatch in what version of CCCore NEI is grabbing.

**Comment by Baughn** [comment]
Okay, I've spent two hours on this, and I'll admit it: I have no idea what's going on. The closest I got to a working 'gradle runserver' was while adding explicit deps on NEI and CCC, and it still doesn't actually work.

I'm going to revert the whole patchset. @bloxgate, you can figure this out later.

**Comment by bloxgate** [comment]
It seems that due to the way the POM file for WAILA was written it updated to a newer NEI version but not a new CodeChicken Core version. I'm checking if the next available version has the issue fixed right now.

**Comment by bloxgate** [comment]
The problem looks to have been fixed in newer WAILA versions, but they require newer versions of forge. For now I'm going to try specifically requiring the needed versions of code chicken.
