### ISSUE TITLE
Update Forge Version

### ISSUE THREAD

**Issue by bloxgate** [Electrical-Age/ElectricalAge#339]
The features in #338 require at least Forge 10.13.3 in order to work with the current versions of the mods in the build.gradle file. I've spoken to @Baughn and was told that its a 1 line change to build.gradle, and didn't cause any issues for him on one of his testing branches, so I'm hopeful that this won't be too difficult.

**Comment by pharaun** [comment]
I've bumped forge to 1448+  personally and I haven't ran into an issue with the bump yet.

**Comment by Baughn** [comment]
We have been running with an EA compiled against current-recommended Forge on Erisia for the past couple of months, with no issues whatsoever. I'd say just do it.

**Comment by cm0x4D** [comment]
develop branch is at 10.13.4.1566, so we can close this issue.
