### ISSUE TITLE
See Battery End of charge voltages when holding shift

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#340]
I have a question about the batteries, the wiki don't help to get an answer for the questions.

What is the end of Charge voltage of the Capacity Oriented Battery? The voltage by arround 40%-50% is about 12.6V 12.7V can you give me a table with the End of charge Voltages for every Batttype, in the wiki it will be helpfull and in the shift menu too.
So i can cutoff the charge when this Voltage is reached

**Comment by Baughn** [comment]
This is what the batteryCharge function in the signal processor is for. See http://wiki.electrical-age.net/index.php/Signal_Processor#Functions_2

**Comment by Baughn** [comment]
Mind you, the sort of circuit you're trying to make will get _interesting_. I know, because I did the same thing.

In particular you need to adjust for open-circuit vs. closed-circuit battery voltage. By all means, ping me on IRC; I'll be happy to talk about it. It just isn't a bug. ;-)
