### ISSUE TITLE
Question about localisation

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#343]
So, I was in my way to redoing the portuguese translations, and I couldn't help but noticing that some .lang files have and underscore preceding the file's name. Is there any reason for that? Should I put one in my file, too?

**Comment by cm0x4D** [comment]
The language files starting with an underscore are not complete, so not used.

**Comment by metc** [comment]
@LorenzoDCC we made some progress with the translations. If you are interested, please create an account on Transiflex and help us to translate the mod in your language.
See https://www.transifex.com/electrical-age/eln/

**Comment by ghost** [comment]
Thanks for the tip! I'll surely drop by and get to work on this :)
