### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#348]
We could deploy the latest HEAD build to bintray using travis CI. @metc what do you think?

**Comment by Baughn** [comment]
I won't object, but can we please reconsider moving to an organisation structure before setting up too much more like this?

**Comment by metc** [comment]
I am not familiar with the current release process.
We can probably automate the job using Travis, but I do not know if this is necessary because we do not publish releases very often.

**Comment by cm0x4D** [comment]
I guess there are people willing to test bug fixes or even experimental items and I would like to enable them to do so without actually installing gradle and building the mod themselves.

@Baughn: Totally agree. I had once a chat with @Dolu1990 about that and he seems open to the option to move the official repo to the EA organization. What would be the implications of moving the repository aside the fact that developers have to change the origin remote URL?

**Comment by Baughn** [comment]
@cm0x4D I'm not familiar enough with GitHub to really be sure, but I expect that existing tool integration will break. Which is why it's better done sooner, rather than later.

**Comment by metc** [comment]
I already have transfer a private repo to an organisation. The remote URL is redirected automatically by GitHub when a repo is transferring, see https://help.github.com/articles/transferring-a-repository/#redirects-and-git-remotes. We _must_ use the transfer features available on GitHub. We should be sure that issue are transferred correctly and assigned to the correct user (user permissions must be setup correctly on the @Electrical-Age organisation).

We already speak about transferring the repo in https://github.com/Dolu1990/ElectricalAge/issues/337. Many links in forums and YouTube movies will be probably 404... I do not see other implications yet.

I vote :+1: for transferring the repo to the @Electrical-Age organisation.

**Comment by metc** [comment]
@Baughn and @DrummingFish I sent you an invitation to be part of the @Electrical-Age/devs group. Do I forget someone ?

**Comment by Domi1993** [comment]
I have no problems with the Git and Gradle it's important that you launch Gitbash as Admin in Win 10 in normal mode it have no permission

**Comment by Dolu1990** [comment]
I'm ok for transferring  the repo ^^
 +1

**Comment by lambdaShade** [comment]
OK to move the repo to the ELN organization.
Anyway, be sure the repo transfer is a complete success before trying to delete the current. ;-)

**Comment by metc** [comment]
This is a transfer from a user to an organization ([as described here](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization)), so there is nothing to delete ;)

**Comment by Domi1993** [comment]
Is the next release coming soon?

**Comment by metc** [comment]
We have to update the group ID of all packages in order to publish it in maven Central.
It is defined here: https://github.com/Dolu1990/ElectricalAge/blob/504fa9a5662ac7b2d632d12744f031b46509246c/gradle.properties#L1
Shoudl we use `net.electrical-age` ?

**Comment by metc** [comment]
We could also deploy on Bintray or demo map.
I will change the demo map URL [define here ](https://github.com/Dolu1990/ElectricalAge/blob/504fa9a5662ac7b2d632d12744f031b46509246c/gradle.properties#L4) when we move the repo to the organisation.

**Comment by Domi1993** [comment]
Is there a download for the Map, that is on the picture slideshow on the main wenpage

**Comment by Domi1993** [comment]
*Webpage

**Comment by cm0x4D** [comment]
@metc: Does it makes really sense to publish it to maven central? I guess publishing it to bintray would be sufficient

**Comment by lambdaShade** [comment]
@Domi1993 This map will be extended and released with the r51.

**Comment by Domi1993** [comment]
There is no server with ELN?

**Comment by metc** [comment]
@cm0x4D Agree, jCenter is fine.
We could create a generic repository to publish the demo map as a zip file and another for the mod releases published as a jar file.

**Comment by metc** [comment]
The repo has been transfered.
Please update your remote URL using this command:

``` sh
git remote set-url origin https://github.com/Electrical-Age/ElectricalAge.git
```

**Comment by metc** [comment]
@lambdaShade You keep the forum post updated, so could you please update the links of the repo [on the forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104648-electrical-age-physics-electric-circuits-more) ?

All links still works, but Dolu1990 has now changed to Electrical-Age.

**Comment by Baughn** [comment]
If you need a server, you can borrow mine; the machine running Erisia would be exceedingly overpowered for the purpose, and there's plenty of spare capacity.

Though it's a dedicated machine, so not as reliable as a multi-zoned VM. If all you need is to serve some files, there are easier options.

**Comment by Domi1993** [comment]
I just serach a server thats running on ELN, do build with you as example do you not have a server for testing the mod in Multiplayer?

**Comment by lambdaShade** [comment]
@metc Forum main post corrected with the new links.

**Comment by metc** [comment]
Great, thanks.

**Comment by Domi1993** [comment]
When comes the new version?

**Comment by lambdaShade** [comment]
Deadline: 30 March 2016, so probably before.
