### ISSUE TITLE
Instructions for Mac Users

### ISSUE THREAD

**Issue by TheAmazingSpy** [Electrical-Age/ElectricalAge#350]
I was annoyed when I saw that there is no instructions for mac users to build the mod, but I did work out: In terminal, cd to the electrical age folder from when you downloaded it, now do sudo ./gradlew build and wait for it to happen, then go to the 'build' folder, then into 'libs' and get the jar file out and then...

```
        MAGIC!!!!
```

**Comment by Baughn** [comment]
You shouldn't need sudo. Otherwise, those are the same instructions as for everyone else...

**Comment by metc** [comment]
If you want to build and run the client from the latest `1.7.10-MNA`, use the following commands described in the `README` file. You can use the same commands on every platforms to build the mod using Gradle:

``` sh
$ git clone https://github.com/Dolu1990/ElectricalAge.git
$ cd ElectricalAge
$ gradle unzipTutoMap runClient
```

The mod release jar file is available here: `build/libs/ElectricalAge_BETA-1.9_r51.jar`. Then, you can:
1. Manually copy the mod to the `.minecraft` folder.
2. Use the `runClient` Gradle task to run the client automatically.

You can use the following command to download the tutorial map (available in the `run/saves` folder):

``` sh
$ ./gradlew unzipTutoMap
```

**Comment by TheAmazingSpy** [comment]
Wrong, it does not work, it is absolutely difficult to install grade on mac, you are thinking it VERY wrong

**Comment by metc** [comment]
It is not more difficult to install Gradle on Mac than on Linux or on other platforms.
1. You can install `Gradle` using [Homebrew](http://brew.sh/) (must be installed first):

```
$ brew install gradle
```
1. Or using [MacPorts](https://www.macports.org/):

```
$ port install gradle
```

These links should also help (or just ask Google ;)):
- http://www.jayway.com/2013/05/12/getting-started-with-gradle/
- http://stackoverflow.com/questions/28928106/install-gradle-on-mac-os-x
- http://blog.diniscruz.com/2013/12/installing-gradle-on-osx.html

Once Gradle is correctlly installed, run the commands in my previous comment to install the ELN mod.

**Comment by TheAmazingSpy** [comment]
Fine metc-1 Spy-0, you win me there. But it does get a bit confusing, if you over complicate it ;)

**Comment by metc** [comment]
@TheAmazingSpy you said it was absolutely difficult, not me :smiley:

**Comment by TheAmazingSpy** [comment]
Are you a fellow mac user?
And I'm just compiling the latest build ;)
