### ISSUE TITLE
Cleanup assets and jar META-INF

### ISSUE THREAD

**Issue by metc** [Electrical-Age/ElectricalAge#351]
I made this issue regarding the commit ebba414 from @lambdaShade. The `asset` folder included in the mod realase `jar` maybe need some cleanup. IMO, it looks ok now.

I think the size of the release `jar` file is not a really big issue... The `assets/eln` folder contains 619 files (~ 4Mo). Currently, every models are included in the release file, event if they are not used in the game.

I check the asset folder content. here are some open questions:
1. Is the `model\_Common` needed ?
2. Is the file https://github.com/Dolu1990/ElectricalAge/blob/1.7.10-MNA/src/main/resources/assets/eln/model/ElectricalSensor/myTex%20-%20Copie.png need ?
3. Some files are mixed between `relay800` and `RelayBig`
4. Is the file `replicator/replicator.tcn` used ?
5. Which Blender files are required for the `stoneCache` model ?
6. Is the file `TemperatureSensor/myTex - Copie.png` needed ?
7. Is the file `VoltageSensor/myTex - Copie.png` needed ?
8. Files `export_block.png`, `export_cable.png` and `export_sixNodeWall.png` should not be included in the release jar, correct ?
   1. Are the files `items/miaou.png` and `items/tiningot.png` needed ?

As proposed by @cm0x4D, I will setup a new filter for the asset folder. Only `.png`, `obj`, `mtl`, `txt` files must be included for the models, `ogg` for the sounds, `lang` for languages and `png` for all textures and sprites.

**Comment by metc** [comment]
The manifest file of the release Jar must also be updated in order to publish the mode to Maven Central.

**Comment by cm0x4D** [comment]
We should first define a folder layout and then rearrange the files to that scheme and after that we can create a useful inclusion filter. The gradle script should not just copy folders into the jar, we could define different rules for different kinds of files and for example move all models into the same target folder.

Another thing that bothers me is that we have to list each model to load in Eln.java. If we have an intelligent data scheme, we could just load all models from a folder at startup. Would be much easier IMHO.

**Comment by lambdaShade** [comment]
I think we have to discuss of this point all together in a meeting...
