### ISSUE TITLE
Battery Life

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#352]
I've seen that the battery life cannot go below 10% i found a (if newlife < 0.1) code in BatterySlowprocess.class i modified the values to 0.001 instead of 0.1 to get the Battery can go to 0.1% life, i'm now trying this what happens to the Battery at 0.1% Life i will tell you if the Battery survive it or if it blow up, this can eventually be changed and a Option to repair Batteries added (Anvil) i think 10% minimal life is too much because the batteries can used with 10% life but i want that batteries are weared and must repaired.
I will test it now with the 240kJ Battery and will test with the 40kJ Battery if it explodes.

**Comment by Domi1993** [comment]
Ok it works when the battery life is at 0.1% but check that the Battery dont get too much power, i will suggest it too change this to 0.01 and add the Repair function for batterys like battery and a ingot for batterys in crafting table and it will get life back (20% per ingot)

**Comment by MaHuJa** [comment]
That OP has two full stops. This is probably why it's fairly incomprehensible. Spending 30 minutes on it, I believe you want to say:
1) Currently batteries have a minimum life of 10% of original capacity.
2) You want them to fall even further, to a point (0.1%) where they are properly useless. Based on your test, you suggested using 1% as the minimum.
3) And you want option to repair them.

What happened to the battery at 0.1% that made you talk about not giving it too much power?
If their tolerance for power input/output changes too much, this could break stuff and make it impossible to have confidence in a system based on previous behavior.

Would it really be worth repairing over simply replacing them?
(IRL I believe not many will repair their batteries. Or maybe that's just this part of the world. At least eln is not using Lithium batteries.)

**Comment by Domi1993** [comment]
Where you should put this weared batteries
Simply in the workbench and a Material thats used for it and then it will get back a part of its life.

IRL: you can Repare a Battery if you can and want to do it!
Minecraft isn't reallife so ELN brings electricty in this world thats works like the real one. and no one will live in a world with tons of dead Batteries diposed in the forest
