### ISSUE TITLE
Lamp channels don't block UI from closing

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#36]
I tried to set the channel "Test Lighting" in a Lamp Supply, but because my custom controls setup uses I to open/close the inventory, any time I hit I the UI closes.

**Comment by Dolu1990** [comment]
I fix that.
Be fixed in next release.
Thanks for feed back : D

**Comment by Dolu1990** [comment]
Hi, 
Normaly it's ok into 1.4.5 that was release few minute ago. If the bug perssiste, re open this issue :)
