### ISSUE TITLE
Important! Unknown crash with ELN.

### ISSUE THREAD

**Issue by Radviger** [Electrical-Age/ElectricalAge#362]
http://pastebin.com/ab8gYxVe

**Comment by cm0x4D** [comment]
It seems to be actually a memory problem. There is no more memory left to allocate or the garbage collector becomes ineffective due to a lot of allocations/deallocations. You can try to rise the memory limit (maybe 2GB instead of 1GB) for the JVM when using such a big number of mods.

The fact that the exception has been thrown in an Electrical Age method is by pure chance, it can happen next time in any other method of the game as the garbage collector runs asynchronous in the background.

**Comment by Radviger** [comment]
It's happened against.

**Comment by cm0x4D** [comment]
Do you some more information? Crashlog? Did you augment the memory for the JVM?

**Comment by Radviger** [comment]
No, I didn't. Cuz the server is in the test mode, so I'm awaiting to publish it when all things will be done. I just need to be sure that this crash isn't caused by memory outflowing and it will not happen again.

**Comment by Radviger** [comment]
P.S. The crash was by he same reason, so I needn't to publish it again.

**Comment by Radviger** [comment]
P.S. The lamp sockets, what's crashed the server were staying in loaded chunks at the all time.

**Comment by Baughn** [comment]
@Radviger Read your own crash logs. It clearly says OutOfMemoryError. That it happens in the Eln code is basically coincidental.

**Comment by Radviger** [comment]
The problem is Why they (lamps) takes a lot of memory?

**Comment by Radviger** [comment]
Or it's only a coincidence that crash happened exactly with the same mod and at the same place?

**Comment by Baughn** [comment]
It's probably a coincidence. GC isn't wholly random; do the same thing twice, and it isn't too surprising for the same thing to happen.

1GB isn't nearly enough for your mod setup. Try setting the maximum to at least 3GB.

**Comment by Radviger** [comment]
So much memory is probably needed to vanilla or cauldron servers, but the problem is that i'm using a hightly optimized server core, which tested with a lot of mods and haven't any lags. Also I want to ask mod authors: Is it possible to stably host a server with Eln and at least 50 players online?

**Comment by Baughn** [comment]
Eln won't be your bottleneck there.

I will state, however, that Electrical Age is only supported on vanilla Minecraft w/Forge. If you're using a custom server, it is entirely possible that it breaks EA's assumptions.

**Comment by Radviger** [comment]
Server core, which i'm using, directed at mod support. There aren't any incompatibilities.

**Comment by Radviger** [comment]
It was tested many times and works perfectly.

**Comment by cm0x4D** [comment]
> There aren't any incompatibilities.

The server has just not enough memory to hold the data of all mods.

**Comment by Radviger** [comment]
Thanks for help!

**Comment by Radviger** [comment]
No, this is ridiculous: http://pastebin.com/rmSwAgY9

**Comment by Radviger** [comment]
Waht I'm doing wrong? I have another server with ~90 mods and 1 gb of ram. There's no ElectricalAge and it works perfectly.

**Comment by Baughn** [comment]
@Radviger Tell me which server core you're using, at least. There still won't be any official support, but as I'm interested in running my own server I _miight_ take a look eventually.

Yes, it's possible that there's an incompatibility between Eln and your rewritten server. _This is not an Eln bug_. Take it to whoever develops that.

**Comment by Radviger** [comment]
It's private core, named ultramine. I'm not sure that you will find at least some info about it.

**Comment by vlad20012** [comment]
Um, hello. I am developer of ultramine core.
Excuse my little "friend" for the inconvenience. I will tell him about a memory profiler in my spare time.
As regards the core, it's not yet ready, there are big problems with documentation and deployment. But if you read in Russian, you can try ;)

**Comment by Radviger** [comment]
I have those lags again. Here's my timings: http://prntscr.com/9o9af8

**Comment by Radviger** [comment]
It seems that this lags happens only when the server is in Idle and after some activity they're disappear.

**Comment by Radviger** [comment]
No, they aren't. When I joined server i'ts hovered again.

**Comment by Radviger** [comment]
Any solution?

**Comment by Baughn** [comment]
No. This is not an Eln bug. Take it up with @vlad20012, or use an unmodified Forge server.
