### ISSUE TITLE
Color overlay on item (in inventory) for faster target voltage identification.

### ISSUE THREAD

**Issue by lambdaShade** [Electrical-Age/ElectricalAge#367]

**Comment by cm0x4D** [comment]
Voltage Colors:

![](https://img.shields.io/badge/50V-30AD63-30AD63.svg)
![](https://img.shields.io/badge/200V-2F81B8-2F81B8.svg)
![](https://img.shields.io/badge/800V-F29C2C-F29C2C.svg)
![](https://img.shields.io/badge/3200V-BF3A31-BF3A31.svg)

@Electrical-Age/devs: Ok with these colors?

**Comment by metc** [comment]
I like the color scheme. Why not invert orange and red ?

**Comment by cm0x4D** [comment]
OK. All silently agreed to the color palette. I will just swap orange and red.

**Comment by Dolu1990** [comment]
perfect ♥

**Comment by metc** [comment]
Thanks @cm0x4D
