### ISSUE TITLE
Emergency panels integration.

### ISSUE THREAD

**Issue by lambdaShade** [Electrical-Age/ElectricalAge#369]

**Comment by lrivard00** [comment]
What do you mean by a Emergency Panel?

**Comment by cm0x4D** [comment]
![1_123125_2245632_2246167_2247195_100308_signs_variationtn jpg crop original-original](https://cloud.githubusercontent.com/assets/6661117/14526230/3a0b0142-0242-11e6-9c8b-839b22f5d9bb.jpg)

**Comment by MyNameIsKodos** [comment]
Lol, I can just imagine an imminent nuclear meltdown being detected, and all of a sudden there's pathing lights and signs everywhere pointing out the base evac route. Cool =)

**Comment by lrivard00** [comment]
This is going to be awesome. I just hope it is 1.7.10 compatible.

**Comment by MyNameIsKodos** [comment]
Just to be clear, was this closed because it's been completed, or because it's no longer being worked on

**Comment by bloxgate** [comment]
It's been completed. See #692
