### ISSUE TITLE
Control suggestions

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#37]
I know this is a bit of a larger 'omnibus' issue, but..

As an electrician with industrial experience, I LOVE this mod already.  A mod like this is a dream come true, and especially already seeing the Modbus RTU.  I do have a suggestion/ or two, however.  Or, well, perhaps it's just a wishlist.

A) Multi-conductor signal cables.  Some decent way to carry multiple signals in a compact manner, akin to the Redpower2/Project Red bundled cables

B) Junction Boxes.  Multiple cables in, multiple cables out, but the individual wires might not all go each way.

C) Limit Switches.  Act as block/entity detectors.  Place them on the border of one block, and they'll detect if anything intersects a small bounding box in the next block over (e.g. an entity, another block, etc).  NC/NO versions

D) Relay cabs.  Large multi-block cabinets that can contain multiple relays/timers/etc in a small space.

E) LED Lighting, or a similar low-power, high-lifetime, high-cost bulb option.

Honestly I love this so far.  This mod works excellently and I'm really happy with it already.  You guys've made my day!

**Comment by Dolu1990** [comment]
Hi,

RTU modbus is a modbus over TCP server.
That was used for one lab in school. Maybe i could put the documentation online ?

A) For signals, It's true that would be cool. We have already think to that in past. It a possible post release enhancement. Maybe we could add some thing like RS485 bus ? with multiple master/slave. and they all speak on the same line, with channel, like for wireless but with RS485 wire ?

B) (my english is bad, maybe i don't have understood your proposal)
Actualy there are 2 things that help into complexe connections : 
  Color brush, to color cables into specific color to not allow cross color connections 
   (you can force alow cross color connection by right click + c key)
 hub, that is a block where you could specify interconnection between side. (showed at end of step by step tutorial)

C) Yes true, actualy the only method to do that is to use minecraft plate + redstone to electrical signal converter.

D) Hmmm, how manage input and output and configure relay timers ? with one GUI ? with the relay cabs GUI ? maybe you have a very clear vision of "how to do that" ?
It's maybe a blocks that enter into "get some already possible things and merge them into one block to simplify". The need must be high else that must wait  :( (actualy we have very few manpower XD)
In any case, with computer craft, the actual computer craft probe (a computer craft perfipheral with a lot of electrical input output) you can do things like that. But this block is WIP. already working but WIP. Do you know what computer craft mod is ?

E) Hmmm ultimate light by led. Yes it's true, i don't have think to that, that could do a third stage of technogy for light.  

I'm happy that this mod is a happy experience for you : D

**Comment by Sukasa** [comment]
Yeah, I've used computercraft before.

About D)...  For configuring relay timers and relays, why not allow crouch-using the items themselves?  This is used by a few existing 'big-name' mods as a way to give the user one way to configure their tools, and then using them is just normal right-click (though since here they'd be going into a cabinet, I suppose you can just standard right-click them instead of needing to crouch-click).

Y'know what, I'll play around with some ideas.  I've written Java before, so I could see what I can come up with.

B) is somewhat useless without A).  However, to give an extreme example of what I meant, please refer to this:
![](http://www.nachi.org/forum/attachments/f19/54409d1334150419-junction-box-dscf4152.jpg)

This Is basically a lot of cables going into a box, and then the wires inside them being connected as needed.  I hadn't meant for more than 4 cables into any one box, and without bundled signal cables it would be useless (as a sane design is already assumed for power cables).  The idea was that if you had a few cable with different numbers of conductors in them, you could pick conductors from each cable and tie them together, and do this multiple times.  Then, the circuits would behave as if all those wires were connected together, but not connected to the other connected sets inside the junction box.

C) I thought would be useful to think of limit switches mounted on a wall and testing beside them, etc.  It would be especially useful along with mods like MFFS that allow you to move entire chunks of the world, as you could use this mod to detect when they've hit a limit, using limit switches.  Perhaps also good for mob transport, etc.

I'm sorry if I am difficult to understand; I know these might range from 'easy' to 'very hard' to implement, but I figure you guys know better than I do, so the least I can do is at least suggest it.

**Comment by Sukasa** [comment]
Also, I saw that folder for a PLC.  Was that related to your school stuff too, or do you have plans regarding that? :>

**Comment by Dolu1990** [comment]
Hi ^^

D) I must play with crush to see where and how use it, basicly, crouch is for  me used to don't fall from blocks it's the reason why i don't have considerate that. But it's true that "why not use crouch". could remove the C key, and that not a bad thing.   

B) cables with multi conductor could be done, It's sur that could be very cool, and as you say, some new block could use this feacture. But for the moment, we must stabilise all. but i keep that in mind  : D

C) I don't understood, What is a MFFS ?

Don't worry it's interresting to have feed back :)

The PLC is the model of the signal processor block (the block where you can write the equation of the output from A B C input)

Ahhhhh to mutch things to do ! XD under water + school exams these time XD

**Comment by Sukasa** [comment]
MFFS is another mod, Modular Force Field Systems.  There are a few different versions of it around.  Here is a link to a video of one of its features in action: https://www.youtube.com/watch?v=gciXgF507gg#t=1328

Limit switches that could be wall-mounted and then test for the presence of entities or other full blocks in the block next to them would work nice with something like that.

**Comment by Dolu1990** [comment]
Ahhhh i understood your plans with limit switch. 
But there is a problems, Actualy, you can't move Electrical age blocks, it's not allowed because that could create big issue with the node manager that is totaly decoupled from minecraft blocks and tile entity. If you move electrical age blocks i'm absolutrly not sure of the result. Normaly small wall blocks must break, and big machine must not allow to be pushed.
If it's a very wanted feacture i can try to make that possible.  (blocks are standard blocks of minecraft, tile entity are extended data storage and processing for blocks, Nodes is my system that is never unloaded from the world, to always be present for the simulation, even if you go far away)

**Comment by Sukasa** [comment]
Not quite - I don't mean to move the EA blocks, but move other blocks and thus trigger mounted EA blocks like limit switches.

**Comment by Dolu1990** [comment]
I have try the crouch, that could work fine with items, but the problem is that don't work fine with blocks (to rotate them) because if you crounch and right click, that try to put the bloc that you have in hand.
I think if in any case the c key must be used for rotate blocks, we can use c key for all other things ?

**Comment by Dolu1990** [comment]
Ahhhhh oky, i understood your proposal (moving block detection)
That could be easly added :) i think soon after release 1.0 !

**Comment by Sukasa** [comment]
Hm.  Could you look into using an item?  A lot of mods, like Applied Energistics, Buildcraft, Thermal Expansion, etc each have items they can use to rotate blocks or perform advanced operations, -but- they're all set up so that the wrench from on (say the Buildcraft wrench) works on Thermal Expansion blocks, and such.  Perhaps that would be a cleaner solution, creating a 'Screwdriver' item that can do rotation?

I only bring that up since while the C key works fine when you don't have many mods, the more mods you accumulate in-game the harder it is to find useful keybinds for them.  Because of that, the fewer special keys you have to use to interact with mods, the easier it is to learn to use the mod and the happier the players will be, at least from my experience in hosting servers.

(By the way, I apologize if I at all seem needy or demanding.  I honestly just thing you guys have a really amazing mod that could easily wind up being a 'must-have' mod with a few bits of polish and some mechanics additions!)

**Comment by Dolu1990** [comment]
yes it's true =>  why not add a wrench !
I place that at first thing to do into my todo list ^^

Don't worry, it's cool to have feed back, it's important, because mod was made for people (and a litle bit because that was fun XD) 

Thanks for your persistence :)

**Comment by Dolu1990** [comment]
Wrench to turn blocks and crouch + click are now implemented juste missing a icon.
Normaly any item that has a name that containe "wrench"  can be used.
That come in next release.

**Comment by Dolu1990** [comment]
Released now

**Comment by nickdutto** [comment]
Awesome, the wrench will come in handy :+1: I must update now.

**Comment by Sukasa** [comment]
Ah, it looks like the wrench doesn't quite work on the historical monitors.  Just gives the error-texture block instead.

**Comment by nickdutto** [comment]
Damn, hopefully it'll be fixed soon :/

**Comment by Sukasa** [comment]
I've noticed this with a few tools; I can't get any of the meters (handheld ones, not the VU-meters), nor the paint rollers to work either.  I'm setting up MCP right now, I figure I could have a look at some of these instead of just whining :P

**Comment by Dolu1990** [comment]
Hmmm it's strang, on my instalation, all is working fine XD 
Even for case that you say XD
i investigate more now

**Comment by Dolu1990** [comment]
I can not reproduct bug, i have try but i can't XD
Can you give me more information about the setup ? forge version ?

**Comment by Dolu1990** [comment]
May be, the thing that was happen is that my releasing procedure has faild and i have push a hybrid release ?
Now i have pushed 1.4.6a,
