### ISSUE TITLE
Switch to Transifex for translations

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#380]
https://www.transifex.com

**Comment by cm0x4D** [comment]
@Electrical-Age/devs What do you think? 
I gave it a try and it works really well.

**Comment by metc** [comment]
You known my opinion ;)
https://www.transifex.com/electrical-age/public/

**Comment by metc** [comment]
Here are the most used languages by the mod users:
![image](https://cloud.githubusercontent.com/assets/229670/12210871/74fa0af4-b65d-11e5-9a54-700f7a8feeaf.png)

**Comment by metc** [comment]
@Baughn you are English native speaker. Could you have a look at the English file language on the Transifex page please ? It would be great if you could have a look at the current English translations before adding more languages.
Have a look and if your are interested and if you have some time ;)

**Comment by cm0x4D** [comment]
@Electrical-Age/devs If someone wants to improve the english texts, please do it in the language file and not in code as the keys are already used for translation...

**Comment by metc** [comment]
I added a configuration file for Transifex, see 2250a04e4b34b96db393e72c8c5dc02d854c19bd. I also added a script to push lang files to Transifex automatically after a successful Travis build.
@cm0x4D can you also test this locally and then I will enable it on Travis ?

**Comment by Baughn** [comment]
@metc If I start doing a typo pass, I'll probably end up bulk-renaming things in the source code again. There are a lot of typos there.

But I'l take a look, sure.

**Comment by cm0x4D** [comment]
@Baughn You can fix them in the en_US.lang file too. Otherwise new keys for the language files are created and we have to start over translating all other languages too.

**Comment by metc** [comment]
@Baughn you are now part of the ELN organisation on Transifex and of course you manage the Norwegian translations ;)

**Comment by cm0x4D** [comment]
@metc 
- just ensure that the updateMasterLanguageFile gradle task is run before to update the language file. 
- there is still a problem with the script: /home/travis/build.sh: line 45: ./script/transifex.sh: Permission denied

On every travis build we update the en_US.lang file on Transifex? Did I understood that right?
Ok for me then.

There is no support yet to automatically download and install translations from Transifex in Eln?
Would it not make more sense to create a gradle task for uploading the resource and downloading the translations?
So we would not need to install the transifex client: http://docs.transifex.com/api/resources/

**Comment by cm0x4D** [comment]
Translated into 7 languages, 19 on the way <3
A big thank to all contributors!!
