### ISSUE TITLE
Autominer texture glitch

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#381]
![2016-01-09_23 51 43](https://cloud.githubusercontent.com/assets/6661117/12218856/25b8f67e-b72c-11e5-8769-1c0daeaba941.png)

Underneath the autominer a face has some glitches...

**Comment by lambdaShade** [comment]
Corrected : https://github.com/Electrical-Age/ElectricalAge/commit/0b7a30f70ca123e54f1bfecc1589929f1a05dd4e.
