### ISSUE TITLE
Achievements: Either seriously create some achievements or remove them

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#382]
The achievements were some long time ago started, but did not evolve that hard. So either we will improve them for r51 or remove them completely for now.

What do you think? @Electrical-Age/devs

**Comment by metc** [comment]
Achievements could help new users to start playing with the mod, but they need to be well defined. In the current state, they are more or less useless, so I propose to remove them for the next release.

**Comment by lambdaShade** [comment]
I agree that the achievements are more annoying than else actually.
We can do a compromise : we can add a flag in "Eln.cfg" for enabling or disabling them (disabled by default until we do better ones).

**Comment by cm0x4D** [comment]
Fixed: b6e5b9fe9abcc91f5db31e29ff051889642fc8ef
