### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by metc** [Electrical-Age/ElectricalAge#384]
You use now Transifex to translate the mod, see #380.

Help is required to translate about 560 words/sentences. Should I add a message on the website so we could maybe find more people to help ?

@lambdaShade could you help me for the Franch tranlsations and review my work ?

**Comment by lambdaShade** [comment]
Okay^2.

**Comment by cm0x4D** [comment]
Would be perfect.

**Comment by metc** [comment]
I added a short not on the homepage and a post on the website: https://electrical-age.net/news/translations-help-wanted/
@cm0x4D thx for the review

**Comment by Radviger** [comment]
You should add a Russian greeting "Привет" to that sign on the site.
=)

**Comment by metc** [comment]
@Radviger pull request are welcome ;)
https://github.com/Electrical-Age/electrical-age.github.io/pulls
