### ISSUE TITLE
Pink sconse lamp is rendered white.

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#385]
Applying a gain of 2 to the pink brush color [1.0,0.5,0.5] results in white.

We have 2 possibilities to fix that:
- Apply globally a smaller gain
- Special treatment of the pink color in render code.

**Comment by lambdaShade** [comment]
It's not a bug... it's a (poor) feature ;-)
For the moment I used a color utility function tuned for cable drawing, tried a workaround on it without changing too much coefficients, and I prefer to say that there have a ugly render in all case (not only pink) with lamps... so I've already planned to do another one tuned for socket coloration !

**Comment by cm0x4D** [comment]
I actually liked the light blue ;-)
But I agree, a new color table for lightning would make sense.

**Comment by Baughn** [comment]
FSVO "feature"; I ran into the same thing a while ago with large resistors.

The simple solution is to normalize color before calling glColor, which will just take it back down to [1,0.5,0.5] unless there are other multipliers in between. The complex solution is to add a fragment shader that does the same.

The really complex solution, which I'm trying to do for said resistors, is to add a whole-screen shader that makes _everything else_ darker / provides proper glare and bloom. Well, I'll figure something out, but what exactly are you trying to do in your case?

**Comment by lambdaShade** [comment]
Just set finely tuned bright colors for compatibles lamps sockets. ;-)
Done now (simple and dirty solution) : https://github.com/Electrical-Age/ElectricalAge/commit/f5eb21c6701f4db79e70c311d4b0374a6ca6e4fd.
Of course, we can enhance that mechanism in the future.
