### ISSUE TITLE
Crash Upon Looking At LampSupply's Description (r51)

### ISSUE THREAD

**Issue by TheAmazingSpy** [Electrical-Age/ElectricalAge#386]
If I do this, I get a rendering text crash, here's part of the crash: java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String

**Comment by cm0x4D** [comment]
@TheAmazingSpy thanks for the issue.

**Comment by TheAmazingSpy** [comment]
Has it been fixed?

**Comment by TheAmazingSpy** [comment]
And how do I use the new distribution board thing and the power socket

**Comment by cm0x4D** [comment]
I hope so.

The power socket thing is not yet implemented afaik, so all you can do is placing them and look at the beautiful models ;-)

**Comment by TheAmazingSpy** [comment]
Will it have a cable?
