### ISSUE TITLE
Any creative light bulbs?

### ISSUE THREAD

**Issue by Radviger** [Electrical-Age/ElectricalAge#387]
I have a little problem on my server.
I've built a spawn with eln's lighting and the problem is that the light bulbs in the lamp sockets are burn out too fast. I don't like always putting them intoi the sockets.
And I think that adding a few infinite light bulbs will be a cool feature.
Thx!

**Comment by cm0x4D** [comment]
You can turn off lamp aging either in the ELN configuration file or in the console.

See here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104648-electrical-age-physics-electric-circuits-more

**Comment by Radviger** [comment]
But I want it only on the spawn and other creative buildings.

**Comment by Domi1993** [comment]
@Radviger

What is the IP of the server?

**Comment by cm0x4D** [comment]
I added LED bulbs in another branch, they have a quite long lifetime. 

An idea would be to let them age only in survival mode and not in creative mode.

@Electrical-Age/devs opinions?

**Comment by metc** [comment]
In my opinion a configuration parameter should be available for this in the `Eln.cfg` file. I like to play realistic in creative mode, so this parameter makes it possible.

**Comment by Santigames11** [comment]
Como es la Ip y que mods tiene?
