### ISSUE TITLE
Tutorial text

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#39]
Since some of the tutorial text wasn't in the best English, I took some time and tried to rewrite it to contain the same information, but write it so it's a little easier to read.  Hopefully it'll be of use :)
# singleBattery

A basic circuit.  The lamp is fed from the battery via the switch, and the battery is grounded on the other side.
The light connects to ground implicitly.
Battery has 2 side, 
  Black is the negative pin
  Red is the positive pin
# //Battery

You can put batteries in parallel in
order to source more current when needed
# ----Battery

You can put batteries in series to store more power
and to provide a greater supply voltage
# lowcostB

A basic, low-cost battery
# highcapacityB

Use more lead to produce a battery
with a higher energy storage capacity
# highvoltageB

This battery directly provides 200 volts!
# highcurrentB

This battery is designed to provide lots of current at once
# longlifeB

This battery lasts longer before wearing out
# singleusageB

It's a single usage battery, can be recharged.
# noregulationTurbine

A basic unregulated turbine generator.
Not safe at all, and can explode easily.
# heatFurnace

Burn coal, or other fuel, to provide heat.
You can manually tune the ventilation to burn less or more
with the control gauge (GUI)
# turbine

Product electricity from a temperature delta.
  Left side must be warm
  Right side must be cold
Electricity is output from the front and back
# passiveDissipator

Dissipate heat into the atmosphere
# internalregulationturbine

You can install regulators in a furnace to control the temperature automatically
There are 2 type of regulator (Check the furnace GUIs)
  On/Off regulator, with a hysteresis
  Analogue regulator, that tries to find the right burning ratio.
  It's not the best regulation method because the furnace never stops.
# activeDissipator

Breathe wind on dissipator is a much more efficient way to dissipate heat !
however, the fan needs a power source
# simpleregulationloopturbine

Furnaces can be controlled from an external signal.
  When the signal is at 0% (0V), the furnace will shut off.
  When the signal is at 100% (50V), the furnace will burn at maximum production.

Here, the signal is provided by a voltage probe configured for
a 100% (50V) signal when the voltage is below 190V, and a 0% (0V) signal
when the voltage is above 210V

This regulates the output voltage to between 190 and 210V
# regulationdisplayturbine

The control signal for the regulation can be monitored in two ways.
  With a Analogue VU meter that displays the signal voltage.
  With a Data Logger, that shows historical signal voltages.

You can see the signal swing when you switch the light state.
# signalA

Signal buttons can provide a 0% or 100% signal.  Note that they are not momentary buttons!
# math3F

The signal processor calculates its output from each input and a supplied equation
Here, each input signal from the three buttons has a specific numeric weight (50%, 33%, 25%)
The calculated output is displayed the VU meter
# mathRamp

A periodic ramp signal can be done with calling ramp(periodValue), where periodValue is in whole seconds
# mathSin

This demonstrates the use of sin() and the pi constant to create a sine wave
# mathSquare

You can also create square waves with some basic logic
# mathRS

One very interesting function is rs(resetTrigger, setTrigger).
This emulates a set-reset latch.  This function outputs a 0 or 1 depending on its internal state. 
  When setTrigger is higher than 0.5, the output is set to 1.
  When resetTrigger is higher than 0.5, the output is set to 0.  This can override setTrigger, if both are high.
This can be very useful to regulate a heat furnace, starting it when a battery is too low, and 
stopping it when the battery is full.
# complexTurbine

Here is a more complex system using a very efficient power regulator.
The Signal Processor controls the heat furnace according to two conditions
  The processor starts when the battery is below 180V, and stops over 220V.
  When running, it controls burn rate to produce electrical power between 450 and 550W from the turbine
This uses the battery as a primary current source, and uses the turbine to charge the battery at maximum efficiency
# transformer

This block transforms voltage and current with a ratio specified by the cable counts in the GUI
# complexTurbineVoltageMonitor

This display monitors the battery voltage
# furnace

This is a furnace that uses electricity to produce heat. 
It will cook the same materials as the base-game furnace
# WIP

Work in progress
# lampShowRoom

Electrical lamp showroom
# lumCaptor

The output of this sensor rises and falls with the amount of light in the block
# lampSupply

Because wiring every lamp in an area could be difficult, you can provide
power to lamps with the "Lamp Supply" block. Just provide power to the lamp
supply and put the lamp on the same "channel" as the supply box
# redstoneLamp

The plate's redstone signal is translated into an electrical signal
This signal is used as trigger by a timer programmed to output a 100% signal for 4 seconds.
That controls the relay which switched power to the lamp.
# greenlab

Green lab !
# solarPanelS

Solar panels produce electricity from sun, taking into account the sun position and if blocks are between it and the sun
# powerProbeS

This probe measures the power production of the solar panels
# solarProbe

This probe displays the sun's luminosity, aka daylight
# solarpanneltracker

This kind of solar panel tracks the sun to get more energy from it
# windturbine

Wind turbines produce more electricity when the weather is raining or thundering!
In general however, the power production is very random
# waterturbine

Water turbine product very little energy, except when the weather is raining.
# weatherDisplay

The weather sensor outputs a signal based on the weather.  0% is sunny
# Wirelesssignal

Wireless signals can be transmitted and received.
# alaram

Some standard blocks could be placed on small electrical element, like stone, or glass in this case.
Here, you can break the glass and push the button to sound an alarm.
# movmentDetect

This is a movement detector, using an entity sensor and a similar circuit to the pressure-plate light.
# hub

You can use hub blocks to cross electrical cables without connecting them. 
That could be very useful in some situations.  Note that you must select which sides are connected to which in the GUI.

**Comment by Dolu1990** [comment]
Seriously, Thanks ! I'm very bad with english XD
realy cool that you have mad that :)
i put that into next map release  : D
