### ISSUE TITLE
Increase Batterycapacity

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#393]
I just calculated the Capacity of the Batteries (the blockshaped not the Items), and i think the Batteries are (to small), they have unreal small capacity for their size. It is a good investition to increase Their Capacity for the Future is useful when even more Things are coming.

```
                               Old                               New
- Cost Oriented                 60KJ           333.33mAh          1800KJ      10Ah
- Capacity Oriented             240KJ          5.333Ah            4500KJ      50Ah
- Voltage Oriented              60KJ           83.33mAh           3600KJ      5Ah
- Current Oriented              40KJ           222.22mAh          2700KJ      15Ah
- Life Oriented                 60KJ           333.33mAh          3600KJ      20Ah
```

I Just suggest this Values, we can handle it when you think they are too high.

**Comment by Dolu1990** [comment]
Initially i don't have designed these capacity to be realistic, but to create a gameplay. I think new capacity in you proposal are why to high. But i'm not against adding a factor in the configuration file :)

**Comment by Domi1993** [comment]
I agree but the factor is a very good idea so everyone can define his own Capacitys i prefer higher because i play in Creative

**Comment by Baughn** [comment]
FWIW, when I was running a TPPI base powered purely by EA, I found that the battery capacities were small enough to make them difficult to use. As in, I needed a bank of 64 high-capacity batteries to duplicate the functionality of a single EnderIO cap bank.

I did so anyway, because it was fun, but if I hadn't turned off explosions the resource drain from occasional mistakes that make every one of them explode would have been painful. (Which is more of an issue with the explosions. Expect some related PRs in the next two or three weeks.)

On the other hand, with a pure Eln base, that same bank would have been massively excessive. So I'm all for the option, but perhaps document that it should be set to 2 or 4x when used in larger modpacks.

**Comment by bloxgate** [comment]
I'd certainly like to see something like this. For me the Eln batteries have always felt a bit small unless you're using massive banks.

**Comment by MaHuJa** [comment]
ELN cost battery: 60 kJ
Real car battery: 216 to 432 kJ (10 Ah)
@Domi1993's suggestion: 1800 kJ (10 Ah)

I don't know which of these are the result I'm looking for. I would presume the first, the result being about a 'capacitor'.
http://www.wolframalpha.com/input/?i=10+Ampere+hours+at+12V
http://www.wolframalpha.com/input/?i=10+Ampere+hours+at+12V+in+joules

---
- Batteries can smooth out much of the supply drop renewables give.
- The power draws we see in eln do not rival what you'd have in comparable real life situations. 20kW ore processing facility? Without looking it up, that seems fairly low. No heating or air conditioning in houses. The list is long.
- IRL renewables have huge problems that could be solved by storage - but actual capacities are orders of magnitude lower than needed.

I'm worried that such a scale mismatch (capacity vs consumption) could leave someone with the impression that storage is a viable solution for real life outside of small scale cases. The really scary scenario is that player being or becoming a politician. 

---
- Electricity IRL is a lot about making supply match demand.
  If you're going to do a 20kW draw at all times, you need to have the capability to produce the 20kW during a windless night. Batteries are not supposed to be the go-to solution for this problem, their job is to keep electricity running for a short while, basically until reserve generation comes online.

---

That said, there is already a config factor for bulb lifetime. Having one for battery factor is a natural next step.

---

I've built a bank of 48 life oriented batteries, but that size has more to do with longevity (by spreading the load) than capacity. After a few weeks, the lowest is still at 98.6% life. But I haven't had big power drains over longer time spans on this system yet.

But that leads me to a question: How would this change going to affect battery longevity?

**Comment by Domi1993** [comment]
@MaHuJa

Remember that the ELN Cost Oriented Battery has a Voltage from 50V (correct me if i be wrong i think the cost oriented has 50V).
1KJ is 1Ws you forget that you compared now a 50V with a 12V Battery thats why it should be 1800KJ, i want to get awaythis KJ and replace it with Ah.
I dont know what car you have when it has only a 10Ah Battery there are some with 80Ah, for the future of this mod is it useful when there are Bigger Batteries and Higher Voltages ( there is much could come in the future)

**Comment by Domi1993** [comment]
You can set something in the config about battery wear check it out

**Comment by Baughn** [comment]
I concur with MaHuJa. Setting the capacities too high would change how the game is played, which isn't something I believe would be valuable. Setting up sufficient standby power--or dealing with brownouts--is one of the better challenges EA has right now.

If there's a risk of major packs setting that value _too_ high, then I'd rather it isn't configurable at all. There should probably be a (small) maximum limit, to stave off the possibility; 3 or 4, say.

I invite everyone present to read http://vazkii.us/uncategorized/sins-of-a-solar-empire-or-the-passive-generation-conundrum/ and https://www.youtube.com/watch?v=EitZRLt2G3w.

## 

On the other hand, I don't think replacing worn-out batteries is very fun. The split there is between constantly-on servers and single-player worlds, in that they have a nasty tendency to go bad overnight while I'm not playing. Maybe we could tie wear-out rate to _real-life_ time?  Or, hmm, that would penalize you for not playing. I'll need to think about this.

**Comment by bloxgate** [comment]
I agree having a limit to the multiplier is a very good idea. It would be way too easy for someone to put a massive number in and get gigajoules of storage.

**Comment by Domi1993** [comment]
@Baughn

Can i visit the ELN-server you are Playing? 
Whats the IP?

**Comment by Dolu1990** [comment]
About life drop, the drop is square of nominal current. so if you only get a low current, the batterie life will not move that mutch. (when nobody is on the server)
Is that in pratice an issue with battery life ?

**Comment by Dolu1990** [comment]
Which mean, actualy, the standar life is :
The battery wll lose 50% of its life if you load it at his nominal current for 2 miencraft days (48 IRL minute)

So if for example you constantly load a battery with the quarter of his nominal current capability it will take 16 time longer to reach the half live.

**Comment by MaHuJa** [comment]
To be clear, some slightly increased battery capacity, maybe 2x, isn't so bad, but the magnitudes being proposed here certainly is.

The cost battery has a max power of 250W. 
But at 50V 10Ah, that means it'll take 1800000J/250W = 7200 seconds to drain.
Which is 120 minutes, which is 5 minecraft days. When redlining your battery.
If that value reaches 0.5 minecraft days, it's way too much. 

As such, given that 50V is not changing, 10Ah is way way way overboard.

And from there the upgrades only goes further.

---

So the life is not dependent on capacity. Got it.

**Comment by Baughn** [comment]
@Domi1993 I'm not currently playing, sorry. :P

@Dolu1990 When I _was_ playing, I set up a kind of power plant for other players on the server. Life would have gone down relatively quickly, because there was a lot of background activity. Even without that, the battery bank was intended to take over for solar panels in nighttime, and I didn't usually remember to shut off my AE system before logging off.

Yep, I eventually started relying far less on batteries.

**Comment by Domi1993** [comment]
@MaHuJa 
I'm still wondering where the Batterycapacity is defined so i can change it and try with 2x higher

**Comment by Domi1993** [comment]
I found it where to change it :) it's in the ELN.java serach for Life Oriented or the other Battery Names

there is a value "stdDischargeTime" there you can insert \* 4 or / 3 what you want it multiplies/Divides the Capacity with the value you entered there
