### ISSUE TITLE
ElectricalAge in french

### ISSUE THREAD

**Issue by Bricklou** [Electrical-Age/ElectricalAge#394]
In this were are the frensh translation for ElectricalAge.

[https://github.com/Bricklou/ElectricalAge/blob/1.7.10-MNA/src/main/resources/assets/eln/lang/fr_FR.lang](https://github.com/Bricklou/ElectricalAge/blob/1.7.10-MNA/src/main/resources/assets/eln/lang/fr_FR.lang)

**Comment by metc** [comment]
Salut @Bricklou,

Merci pour ton travail. Les traductions ont beaucoup évoluées et nous utilisons maintenant [Transifex](https://www.transifex.com/electrical-age/) comme plateforme de traduction pour toutes les langues du mod.
Si tu souhaite participer à la traduction du mod, tu peux t'inscrire sur Transifex et demander [un accès pour la langue francaise](https://www.transifex.com/electrical-age/dashboard/all_projects/fr/). Les traductions sont font directemenr sur le site de Transifex.

Merci d'avance pour ton aide.
