### ISSUE TITLE
Signal Source Graphic Bug

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#396]
![2016-01-30_16 01 30](https://cloud.githubusercontent.com/assets/16188258/12696428/f8c710de-c76a-11e5-8bd9-9151356707fc.png)
![2016-01-30_16 01 10](https://cloud.githubusercontent.com/assets/16188258/12696431/fb73b12a-c76a-11e5-8b35-c1ded09edd05.png)

I'm Still discovered that the Signal source is invisible
(Mod Builded 3 Days ago)

**Comment by bloxgate** [comment]
Hi, several models have been updated and as such not everything will work. The current recommended version of the mod, r50, has visible signal sources.

**Comment by cm0x4D** [comment]
The model was (re)moved by accident. 
This will be fixed once my new icons branch is merged. But the next week I will not have time to work on this, I will be quite busy celebrating mardi gras ;-)
However you can check out the feature branch if you like to test: https://github.com/Electrical-Age/ElectricalAge/tree/feature/updated-icons
