### ISSUE TITLE
[Request] Covering cable corners

### ISSUE THREAD

**Issue by BlayZett** [Electrical-Age/ElectricalAge#397]
This is a request (or possibly an issue) for some way to cover the corner of a cable. Here is what I mean:

![2016-01-31_03 17 41](https://cloud.githubusercontent.com/assets/8340715/12701055/bd21c6a0-c7c9-11e5-9446-6a8592cea616.png)
![2016-01-31_03 17 45](https://cloud.githubusercontent.com/assets/8340715/12701053/bd1c5ae4-c7c9-11e5-90c9-23e6822be6b7.png)
![2016-01-31_03 17 48](https://cloud.githubusercontent.com/assets/8340715/12701054/bd2115ac-c7c9-11e5-8d78-e7dee70d4475.png)

As you can see, placing a block on the corner disconnects the cable. Could this be changed?

**Comment by Baughn** [comment]
And for a lark: Placing a _sign_ on the corner _occasionally_ disconnects the cable, basically whenever there's a block update. The physical appearance indicates that this shouldn't happen, so it'd be great if it wouldn't.

**Comment by Domi1993** [comment]
![2016-02-03_10 33 56](https://cloud.githubusercontent.com/assets/16188258/12778198/c377d9d2-ca61-11e5-8181-7479013a3025.png)
![2016-02-03_10 34 05](https://cloud.githubusercontent.com/assets/16188258/12778200/c383f47e-ca61-11e5-8743-4dd3c545de7d.png)
![2016-02-03_10 34 10](https://cloud.githubusercontent.com/assets/16188258/12778199/c37e3124-ca61-11e5-910a-9ad915999836.png)

I made this using another single Wire (Creative Mode) that i placed there where the cable is going down, so i can cover it without cutting the wire

**Comment by anar4732** [comment]
or forge micro block support

**Comment by cm0x4D** [comment]
I can not imagine a good way to fix this on our side, as the cable would be cut even without the covering block and there is a workaround from @Domi1993, so I gonna close this issue.
