### ISSUE TITLE
Add DC Electrics

### ISSUE THREAD

**Issue by anar4732** [Electrical-Age/ElectricalAge#398]
DC Electrics
- 3V,5V,12V DC Cables (like microblocks)
- Micro Chips (like "project red" IC circuits)
  - micro light
  - micro displays
  - micro buttons and leaver
  - programable chips

Other (important)
- "Bulidcraft" and "Galacticraft" oil or fuel generator (need cooling)
- cooling with ice (for thermal cable)
- on/off display (like dijital clock)

**Comment by lambdaShade** [comment]
The electric simulation is already DC and we're trying avoiding an infinity of voltage range (and corresponding objects)...

**Comment by Baughn** [comment]
Fuel/oil-powered generation (steam-powered, really) is in the pipeline, and will probably be in r52. (That is, the release after the next one.)

I've poked at the idea of adding a PDP-8 (with a default Forth interpreter) to the mod.

The rest... is unlikely to happen any time soon, I'm afraid.
