### ISSUE TITLE
Power Plant and power

### ISSUE THREAD

**Issue by iceman11a** [Electrical-Age/ElectricalAge#399]
I tried creating a power plant from a video that don_bruce made. and I can't seem to get it to work. I tested this on 3 single player maps and one online. I still can't seem to get it to work. The video starts up the Heat Furnace with out using coal. When I try the same setup.  nothing happens. So I have no idea if this is a bug or what it could be. Some one else all so tried the power plant all so and got the same results as I did. 

The video all so shows the setup on the left side runs the fans for the power plant. and I can't seem to get that working all so. I tried contacting don_bruce. and still no reply. Here's the video on this. 

https://www.youtube.com/watch?v=Kp3who_qpWY

The idea is to power up a small town or city. With lights, In and Out.

**Comment by Baughn** [comment]
What were you using instead of coal? It does need fuel.

**Comment by iceman11a** [comment]
I have use Charcoal. The point is that in the video. He doesn't use any thing at all. It works fine in the tutorial world he made and released to us. How ever I never been able to setup the Heat Furnaces to run with out some kind of fuel.

**Comment by darqen27** [comment]
He had a single block of charcoal in that furnace, it consumed it when the probe flipped the furnace on. There was always fuel, you just didn't see it.

**Comment by iceman11a** [comment]
Then explain why after all this time. The power plant is still running. and I never added any fuel to it. All so I setup the same thing he did out side where he had his setup. and I didn't even add fuel to it and it started right up. Try downloading the tutorial world and go to the far end and go into the basement of the last building. and check it out for your self. 

On the left side of the basement. Is the setup that runs the fans. There's no fuel in those. Go back out side and setup a small sample. and use the setup he has, as soon as you setup the 1st heat furnaces you will see them come on and the fan will spin.

**Comment by Baughn** [comment]
A single block of charcoal can last quite a while if the furnace is set to low power.

I don't think there's any bug here. Your furnaces will work once you add fuel.

**Comment by iceman11a** [comment]
Sorry, I just fount out from some one else who is having the same idea and problem I do. He told me that the guy who made the video. add a /eln hestFurnaceFuel 0 to the mod. This sets the fuel required to 0, so the Hest Furnaces don't need fuel. They will run on there own. Sorry. I didn't know.
