### ISSUE TITLE
'Eln Interact' and 'Open Wiki' controls reversed in options menu

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#40]
I had 'Eln Interact' and 'Open Wiki' controls set to X and C respectively.  However, I had to hold C in order to rotate items, and X tried to open the wiki.

**Comment by Dolu1990** [comment]
Ahhh, i have swaped some id into code !
now it's fixed, must be in next release.
Thanks for issue :)
