### ISSUE TITLE
Electric items charges by themselves

### ISSUE THREAD

**Issue by Radviger** [Electrical-Age/ElectricalAge#404]
By unknown reason any electric items in enventory charges by themselves (Batteries, Drills, etc.)
I'm using latest version of Eln

**Comment by Dolu1990** [comment]
=> /eln aging [0 or 1]   in the console
When it's 1 portable battery are refilled naturaly

Did you try on a new map ? or it was on a tutorial map ?

**Comment by Radviger** [comment]
No, I didn't. But then what I should do with the light bulbs? They will be aged again?

**Comment by Radviger** [comment]
Ok, I've figured out all the things. Thanks!
