### ISSUE TITLE
Gitter as support channel?

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#405]
There is not that much activity on the IRC channel and I guess a lot of people do not know how to use the IRC chat to get in touch, so gitter.im might be a solution. It is used by many open source communities and seems quite easy to use. It offers an IRC bridge, so for those who prefer IRC there would not be that a change.

https://gitter.im/Electrical-Age

@Electrical-Age/devs What do you think?

**Comment by Baughn** [comment]
Mm, perhaps.

One thing I've noticed about IRC is that people tend to join, ask a question, and then leave after five minutes when it isn't immediately answered. I don't have any easy solutions for that.

One problem with gitter is that you need to already have a GitHub account, or register one with gitter, in order to log in. That isn't the case for IRC.

**Comment by nativewolf78** [comment]
guys i tried using the IRC chat a while back and was waiting about 3 hours for an answer there were 3 people in the channel but i just presumed that they were all asleep or something
as i know the mod creators are in a different time zone to me

but some sort of direct messenger would be handy for this mod

also can someone tell me why it has on the forum the current version is release r51 and in development r52 as i have r50 release and there are two blocks that keep saying to report to mod author  one has like an iron texture and the other one has a pink and black checker texture to it the ids of the blocks are 1145 and 1146 and even after reinstalling this mod the same problem is occurring

Don bruce told me to download r49 release that he was using as it has not got that issue in it and has a few more different things to the one i have but i dont really want to roll back to an outdated version as ive already set up my world with a hell of alot of electrical stuff
i was trying to find version r51 download but cant find a link to it as i am covering this mod in tutorials 
as i have been requested to make some tutorials on it by some people

i agreed to do them as there are not many out there in English so is difficult for people to understand
but im loving the mod and want to continue the tutorials

also how can i put a suggestion across to the mod creator to put some sort of wall socket in the mod that would be awesome to make it more realistic this mod is the best out there and im having fun learning from it and the first two videos ive done are my very first YouTube mod review videos as ive never done them before so im a noob to YouTube reviews its the first time ive ever spoken on a video

any advice would be great on the new release r51  thanks in advance guys

**Comment by cm0x4D** [comment]
Releases are here: https://github.com/Electrical-Age/ElectricalAge/releases

Thats just wrong on the Forum, actual release is r50, and we are a little behind the schedule...

Can you send us somehow your world that causes the issue with the 2 blocks? So we could look at it a little closer.

For development version (r51) you need to download the code from this repo and compile the mod yourself. There are no snapshots available. Using the gradle wrapper it should not be that hard...

Wall sockets are available in r51, but not already functional i guess. But they are very decorative anyway ;-)

Some of us are already on gitter, so chime in there if you have further questions...

**Comment by nativewolf78** [comment]
im not sure how to send you my world save the r51 version id love to try out but you lost me when you mentioned about using gradle wrapper lol i aint got a clue what that means and how to use it so ill have to stick with r50 the error im getting are just two blocks ones called ghost block for some reason and when spawn it just spawns an invisible block the other doesn't spawn anything at all id be more than happy to send a copy of my world but i dont know how id go about that

**Comment by cm0x4D** [comment]
Back to topic: I agree, Gitter is not ideal as support channel due to the fact that people have to log in in order to write a message. But it could work pretty well as communication platform for devs...

**Comment by nativewolf78** [comment]
cm0x4D

wouldn't Skype be alot easier to use 
as many people already have a Skype account especially people that dont think they do 

but they do if they have a live.co.uk email or Hotmail.com email address as msn bought Skype as a replacement to there msn messenger

so alot of people wouldn't know they have a Skype account but they already do its there email and password from there outlook account

im pretty sure that would be an easier way and form of communication between devs and users of the mod

i added dolu on Skype and he accepted my friend request and answered a lot of my questions about r51 and the release date
he mentioned that he was in the process of moving back to his home county and that the release was delayed at the moment
i found the Skype easier to talk to him in :)

just a suggestion :) dont wanna tread on anyone's toes i know im not a dev
and just a normal user of the mod

but i try to help others on the curse forum about this mod but dont wanna tread on don bruces toes there too lol i just try to help where i can and also started doing tutorials on the mod :)

**Comment by cm0x4D** [comment]
Using gitter as communication between devs is quite simple, nobody needs to create an account as everybody can use his github account which is not the case with Skype. Gitter offers some handy integrations as for example displaying the latest activity on github or travis build results on a side view.

So lets vote on this comment:

Gitter as dev comm?

**Comment by nativewolf78** [comment]
thats even better then i didnt know it would automatically be linked to the github account :) you have my vote for it then :D awsome :+1:

**Comment by metc** [comment]
Gitter or Slack for the developers. What about https://discordapp.com/ ?

**Comment by Baughn** [comment]
I feel a bit sad about IRC being forgotten, but... I can live with Gitter, yes. Thumbs up.

**Comment by metc** [comment]
@Baughn what about https://irc.gitter.im/ ?

**Comment by Baughn** [comment]
That works, thanks. ^_^

**Comment by cm0x4D** [comment]
Gitter. Period.

How about https://github.com/finnp/gitter-irc-bot?

So support would be on Gitter and IRC simultaneously, IRC without the need to create an account and Gitter as an alternative...

**Comment by ghost** [comment]
Tbh, it you would get a lot more attention if you were on irc.esper.net ... it would be really nice if you made a channel there.

**Comment by ghost** [comment]
This is something i brougth up a while ago when i came to the other network, also its hard for some to be connected to more than 2 networks at the same time.

**Comment by Baughn** [comment]
Every client I know of can connect to one as easily as ten. I'm connected to five-six networks right now.

Which is not the same as players knowing how to do that, so perhaps we should indeed move the channel. I've also wondered about building an irc client into the mod... I know that's usually a modpack thing, but Eln might be just hard enough to need that.

**Comment by ghost** [comment]
Still i know some people which would like an Electrical-age irc channel on espernet.

**Comment by cm0x4D** [comment]
Support is now on IRC and gitter.im, both are bridged using https://hub.docker.com/r/chihchun/gitter-irc-bot/
