### ISSUE TITLE
/home/travis/build.sh: line 45: ./script/transifex.sh: Permission denied

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#406]

**Comment by metc** [comment]
This is a WIP. I will look at it, thanks.

**Comment by metc** [comment]
The Transifex client is buggy. The latest client version cannot be used with Travis. I create an issue about this, so in the meantime for the next release, I will synchronize the languages files manually.

**Comment by cm0x4D** [comment]
> I will synchronize the languages files manually.

Well, then I can close the issue...

**Comment by metc** [comment]
I always monitor the status of the Transifex client. As soon as the issue is fixed, I will add it and the job will be done automatically ;)
