### ISSUE TITLE
electrical age wiki problems??

### ISSUE THREAD

**Issue by nativewolf78** [Electrical-Age/ElectricalAge#408]
Guys im not sure if you are aware but everytime i go to look at the wiki online its saying the page i just get this on a blank white page

A database query error has occurred. This may indicate a bug in the software.

is the wiki down or is this expected as i know it says on the forum that release planned on 02-04.2016 for r52

**Comment by metc** [comment]
Hello,
Thanks for your message. The online Wiki (http://wiki.electrical-age.net/ ) is currently down for a maintenance. Sorry for any inconvenience.

**Comment by nativewolf78** [comment]
Thank you metc thought my browser was playing up on me for a moment when it came up that message lol :) im looking forward to the new release hope its soon as i do videos on your mod its awsome to work with such a great mod and im finding it very good to do the tutorial videos for others to learn from :) you people are inspirational keep up the good work on the mod :)
