### ISSUE TITLE
Possible wiki in the future?

### ISSUE THREAD

**Issue by nickdutto** [Electrical-Age/ElectricalAge#41]
Do you think there is any chance that there will be a wiki for reference in the future?

**Comment by Sukasa** [comment]
There is an in-game wiki

**Comment by nickdutto** [comment]
I know, but an online wiki would be a preferred thing for some people.

**Comment by BroBeans** [comment]
We do plan to have a Online Wiki in the near future. We will begin, around the time v1.0.0 has been released.

**Comment by Dolu1990** [comment]
If guy want to contribuate to the wiki, we are of course open :)

**Comment by nickdutto** [comment]
Sure I'd love to.

**Comment by Dolu1990** [comment]
I'm abolutly not a wiki expert (how manage a wiki) BroBeans has begin something. Maybe you could loooking to that together ?

**Comment by JacobCZ** [comment]
Hey, I'd like to contribute to the wiki, do you have something already set up? Or I could create the wiki for you, make some nice design, homepage... Just let me know ;)

**Comment by nickdutto** [comment]
You got any example work?

**Comment by Dolu1990** [comment]
We are open, for the moment the wiki is under design contruction. But we don't have loot of experience into that :(
If you have experience into wiki making, off course you could create wiki, and off course, if your result is betther than what we actualy try to do, we adopte your proposal :)

There is the actual wiki http://electricalage.wikia.com/wiki/Electrical_Age_Wiki

**Comment by JacobCZ** [comment]
Okay, hmm, I will create something and let you see it, then you can decide, if you want to use it, okay?

**Comment by metc** [comment]
We are building a new open-source website for the mod. We also want to create a wiki. It will be based on MediaWiki (or something similar) and will be sefl-hosted on our web server.

MediaWiki seems to be a good choice: @JacobCZ do you have any experience with MediaWiki or what type of wiki do you recommand us ? We want to use a self-hosted wiki.

Any suggestions or contributions for the wiki are welcome :thumbsup:
We wiil give you news as soon as possible. If you want to contribute, please contact directly @Dolu1990 using this forum: http://www.minecraftforum.net/topic/2741783-172forge-electrical-age-mod/.

**Comment by JacobCZ** [comment]
@metc I have a previous experince with mediawiki, so if you provide me with hosting access or already installed MediaWiki, I can help you to set it up and make it up and running ;)

**Comment by Dolu1990** [comment]
There is the wiki ! http://wiki.electrical-age.net/index.php/Main_Page
Now, when people have time and motivation, everybody can contribuate : D

**Comment by JacobCZ** [comment]
Perfect! Could you please allow me (JacobCZ on the wiki) to edit the main page? I'll make some nice index or directory or whatever you want to call it of categories and articles ;)

**Comment by JacobCZ** [comment]
And also, if possible, please install this plugin, as it will make the wiki creating much easier... http://www.mediawiki.org/wiki/Visualeditor

**Comment by metc** [comment]
@JacobCZ your are now admin on the Wiki. I will see if we install this plugin or not.

**Comment by JacobCZ** [comment]
@metc I don't have a very good access to the internet right now, but when i get to better one, I will start working on it ;) And please, install that plugin, it would help me a lot...

**Comment by BroBeans** [comment]
@JacobCZ You and I will be working together on the wiki. If you will, could you provide with your Skype? If you don't have a Skype account, I recommend you create one.

**Comment by JacobCZ** [comment]
I have one (kubicek250), but i'd rather use hangouts (jakubsycha@gmail.com)...

**Comment by JacobCZ** [comment]
When adding a new page with crafting recipe, use the http://wiki.electrical-age.net/index.php/Template:Crafting_Grid template, more info listed on that link, also use the http://wiki.electrical-age.net/index.php/Template:Block template and add the page to http://wiki.electrical-age.net/index.php/Template:Blocks Table Of Contents...

**Comment by JacobCZ** [comment]
@metc swap the logo on the wiki for the blue circle with lightning one, it looks better than the current one...

**Comment by metc** [comment]
@JacobCZ thx for your work on the Wiki. You are all welcome to contribute :wink:
We are also working on it and a new logo is in preparation. 

I had some common CSS styles here: http://wiki.electrical-age.net/index.php/MediaWiki:Common.css Please use it for the new wiki pages.

**Comment by JacobCZ** [comment]
sure, i will try at least ;)

**Comment by JacobCZ** [comment]
And btw, http://wiki.electrical-age.net/index.php/NyanCat :cat:

**Comment by JacobCZ** [comment]
And one more thing, make one more wiki, maybe on wiki.electrical-age.net/cs/ or something like that, so i can make a Czech-localised version of the wiki... I know a lot of people in Czech, that play this mod and I'm czech, so it will be easy for me to translate it.. Also, try to fix the Visual Editor plugin, because it does not work...

**Comment by Dolu1990** [comment]
Hi ^^
Sorry for latency.
Actualy we don't want to split up into many language, because we are few :(
Personnaly, my english is not very good, but so many people can understand english. And that why i think before split into many language, we must do a complet english wiki :)

**Comment by JacobCZ** [comment]
Sure :)

**Comment by Dolu1990** [comment]
Miaouuu
