### ISSUE TITLE
Add OpenComputers support and compatibility

### ISSUE THREAD

**Issue by TekuSP** [Electrical-Age/ElectricalAge#419]
OpenComputers can should be used as microprocessors and you should add compatibility for converting energy into OpenComputers one. You should add too add Convertor block what would allow OC computers access digital signal from signal cable.

**Comment by bloxgate** [comment]
There is already a computer probe block, if you cannot create it please double check that you do not have it disabled in the config.

**Comment by TekuSP** [comment]
Oh, it was disabled in config. Thanks for answer

**Comment by bloxgate** [comment]
No problem. Just a heads up though: the last time I used the probe some of the side labels had their textures flipped. So if you can't select certain sides of the probe for some reason, keep that in mind.
