### ISSUE TITLE
Setting up MCP?

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#42]
I feel kind of bad having to ask this, but is there a reference you used for setting up MCP and Forge?  I have tried to set up, but apparently the tutorials I have found are not working for 1.7.2.

May I ask what tutorial or reference you used for getting Eclipse set up to make a 1.7.2 mod?  I'd like to contribute more than just issues, but this is making me feel a little dumb.

**Comment by nickdutto** [comment]
LexManos has a ForgeGradle setup guide for 1.7.2. Should be on the minecraftforge forums.

**Comment by Sukasa** [comment]
Thanks.  Last time I set up an environment was 1.4.7.

**Comment by Dolu1990** [comment]
That had change a lot ^^
Ahhh just, instalation dependancy => 
"modbus4j" 1.1 must be added in java path of eclipse project. http://sourceforge.net/projects/modbus4j/files/modbus4j/ (Files : modbus4J.jar + seroUtils.jar)

Additionaly => 
![image](https://cloud.githubusercontent.com/assets/4832082/3311278/53f19fe0-f6c2-11e3-9490-43b22df967e6.png)

**Comment by nickdutto** [comment]
Easy enough.

**Comment by metc** [comment]
A page will be available on the official Wiki, ASAP.
