### ISSUE TITLE
New Item Request

### ISSUE THREAD

**Issue by lrivard00** [Electrical-Age/ElectricalAge#420]
I was wondering if colored lights could be put in. Or more variety of lamps. Thanks!

**Comment by cm0x4D** [comment]
You can change the color of a sconce lamp socket using EA brushes. This will come probably with r51...

**Comment by lrivard00** [comment]
I mean the color of the light emmiting from the socket.

**Comment by SaphireLattice** [comment]
That's impossible. At least unless the colored lights will get added to the
vanilla Minecraft or to the Forge. Which is "practically never".
Issue can be closed i guess?

**Comment by Baughn** [comment]
There's a Colored Light mod, but it has compatibility issues with a variety of other mods. Still, it might not be unreasonable to integrate with it if it happens to be installed.

**Comment by TonyTash** [comment]
Not sure if its possible to implement into a mod, but MInecraft does have lighting of different colors. Nighttime is bluist, torches are yellowish and daylight is white
