### ISSUE TITLE
Batteries wont charge when using solar power

### ISSUE THREAD

**Issue by redstonegenious** [Electrical-Age/ElectricalAge#421]
My favorite form of power is solar (I dont like using coal) and when I add a battery system. The power input deplates as the batteries charge. When it is about 68%, the power reaches too low to charge the batteries. All other sources work fine and the voltage is always higher than the batteries.

**Comment by Baughn** [comment]
Probably you don't have enough solar panels in serial.

A picture would help. There's no bug here, though; the solar panels work fine, and while I don't mind just helping, you'd be better off going to IRC and asking. (Given patience. The channel isn't very active.) There's a tab over on https://electrical-age.net/ to get you there.
