### ISSUE TITLE
Let's document the purpose of the branches, how to develop, etc.

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#426]
Aka. there should be a Develop.md. We also ought to clean up the repository branches.

We've discussed this a little bit on #422, and the consensus seems to be to use Gitflow, as described on http://nvie.com/posts/a-successful-git-branching-model/. Just got a 'develop' branch, too.

In short, this means:
- Features get developed on feature branches, in your local repository or pushed to github. Feature branches can be rebased.
- Once ready, feature branches are PR'd to develop.
- When we want to make a release, develop is branched into a release branch. Any necessary stabilization works happen there; develop is never frozen, and efforts to PR in feature branches should not stop just because a release is happening.
- When a release is made, the release branch is pushed to master and master is tagged at that point.
- If hotfixes need to be made, then they can be made on the release branch. Anything that also applies to the development branch is first committed there, then cherry-picked to release. The release branch is then pushed to master (again), and tagged (again), going from e.g. 0.52.0 to 0.52.1.
- Develop, master and the release branches are all protected; no rebasing happens there.

So, at any given time we might have these branches:
- master, with 0.52/0.53/0.54/etc. release tags.
- develop
- release/0.53 (Which would be deprecated, and can be deleted once we feel like it. It can in any case be recreated from the tag on master. Where there is a 0.53.1, that would still be contained in this release branch.)
- release/0.54
- feature/rheostat-wiper
- feature/omniglove
- feature/foobar2000
- feature/flightdrone

...and so forth. Feature branches can be deleted at the pleasure of the person(s) owning them, which would generally happen after merging to develop.

It would _not_ include:
- 1.6.4
- 1.7.10-MNA
- 1.7.2
- etc.

Those branches should all be deleted, though it'd be smart to keep their most-recent tip as tags.

Make sense? Once we have such a document, we can also start documenting some of the internal APIs there eventually.

**Comment by cm0x4D** [comment]
I pushed a first version of the DEVELOPMENT.md file. Please review it and if it is ok for you, we can integrate it into 1.7.10-MNA (later master) as well.

**Comment by metc** [comment]
I fully agree with the @Baughn comment the `DEVELOPMENT.md` document, especially the ["In short for EA"](https://github.com/Electrical-Age/ElectricalAge/blob/develop/DEVELOPMENT.md#in-short-for-ea) comments. I have some experience with the Gitflow workflow and I think this is everything we need.

Some remarks:
1. I created the [`CONTRIBUTING.md` file](https://github.com/Electrical-Age/ElectricalAge/blob/1.7.10-MNA/CONTRIBUTING.md) some time ago. Not sue if we need both`DEVELOPMENT` and `CONTRIBUTING` files.
2. For the version name, I vote for [Semantic Versioning](http://semver.org/). Should we also include the targeted Minecraft version in the release name (for instance `1.7.10-Forge`) ?

**Comment by metc** [comment]
They are [some open questions](https://github.com/Electrical-Age/ElectricalAge/issues?q=is%3Aopen+is%3Aissue+label%3Aquestion) we should discuss and take a decision.

**Comment by Baughn** [comment]
It might also be good to set the default branch to 'develop'. As it stands, Github's "X commits ahead" messages are becoming almost useless.

**Comment by metc** [comment]
IMHO it is better to keep the master/release branch as default branch. The end user should not use the develop branch I think.
