### ISSUE TITLE
Circuitbreaker grren and red Lines

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#429]
I dont know if that was intentionally made so, that the Green line on the Circuitbreaker means ON and the red one OFF.
I know this only on the different way that Green means OFF and red ON. Have you do this the other way that peoples dont be confused when they dont know about electricity?

**Comment by cm0x4D** [comment]
I guess if we do red = on and green = off, more people would actually interpret it wrong than right. On the other side we should be correct.

I will retexture the breaker and use red = on, gray = off. That should be more comprehensible...

**Comment by cm0x4D** [comment]
Fixed in develop
