### ISSUE TITLE
Items/Blocks not showing up in creative menu

### ISSUE THREAD

**Issue by nickdutto** [Electrical-Age/ElectricalAge#43]
Hello,

In release 1.4.6 you cannot see the items/blocks in the creative menu, I have also not been able to find any ore but that may just be luck. The only ELN item I could find was the spawn egg for a replicator. I loaded up the tutorial map and all items/blocks are still there.

**Comment by Sukasa** [comment]
I know this is stupid, but you're sure they aren't a page over in the creative menu?  I've got that branch here and it works fine

**Comment by Dolu1990** [comment]
absolutly any item / blocks of the mod are drawed into creative menu ?
Here all is working to. But i know that some graphics variation could be linked with graphic card, especialy if you use a intel integrated graphic chipset. is it the case ?

(all is working fine on my PC)

**Comment by nickdutto** [comment]
Nah got a GTX 750, I'll try dropping it into Forge and see what happens.

**Comment by nickdutto** [comment]
And yes I went a page over.

**Comment by Dolu1990** [comment]
Ahhh cool :)
Fine (you know, adding bug on release is realy bad) XD
Issue can be closed ?

**Comment by nickdutto** [comment]
Yep, it might just be a problem with things I'm running in my instance.
