### ISSUE TITLE
Recipes missing for logic gates

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#442]

**Comment by Baughn** [comment]
Once they've got recipes, maybe it'd make sense to build the signal processor from them?

**Comment by cm0x4D** [comment]
I am playing with the idea to create a PCB block which can be equipped with those chips and some lines can be drawn between then. This would definitely be fun...

For the recipe I am not sure if we should change existing ones.

**Comment by cm0x4D** [comment]
https://github.com/Electrical-Age/ElectricalAge/pull/494
