### ISSUE TITLE
Bugged Menus since new release

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#446]

**Comment by Domi1993** [comment]
Wrong button 😁

But yes since the new version is avialable i has some / in the batterymenu...

It says Energy/:24KJ on other blocks there is this bug too.

I will upload pics of it today evening or tomorrow

**Comment by cm0x4D** [comment]
Seems to be a problem between Forge and Transifex. Try to fix for the next release...

**Comment by cm0x4D** [comment]
Fixed in develop (32d3093a)

**Comment by Baughn** [comment]
@cm0x4D Do we do a hotfix release?

**Comment by cm0x4D** [comment]
I have to fix another small issue with the formatting of numbers, then why not. 
On the other side the issue does not really justify an update on his own. Maybe I could add the Straight Joint, a flywheel and a Shaft hub to the mechanical portfolio and then an update would actually make sense...

**Comment by Baughn** [comment]
That's why "hotfix". The cost to doing a release should be low enough that it doesn't hurt, at least.

**Comment by Domi1993** [comment]
@cm0x4D

Means that i can use the shaft to get power from the rotarycraft gasturbine and engines? This dont work now when i put the Generator on the rotarycraft stuff

**Comment by cm0x4D** [comment]
No, we make our own turbines with blackjack and hookers ;-)

But seriously: no. There were once some plans, but for the moment it is not possible.

**Comment by Baughn** [comment]
Yeah. The concern is mostly power scaling, but also integration. As much as I love RotaryCraft, and the inspiration here should be obvious, the shaft simulation in EA is a good bit more realistic in some ways that make integrating it hard.

(And less in others, since it's indestructible, but I'll fix that eventually.)

**Comment by Domi1993** [comment]
I want to try out some 3D modelling to make new stuff for the ELN-Mod. What are you using? Blender or something other?

I had the idea to help making a gasturbine generator for thats powered by Fuel, and i think the player must insert a Current oriented battery for the Starter, i got some awesome sound of a Turbine generator starting and stopping

**Comment by cm0x4D** [comment]
Yes we use blender. There are some templates to start that have a MC block and some settings: 

https://github.com/Electrical-Age/ElectricalAge/tree/develop/src/main/resources/assets/eln/model/_TEMPLATES

Well, would this be something like a diesel-generator?

**Comment by Baughn** [comment]
So, an equivalent to the steam turbine, but a gas turbine instead? Cool. I'd definitely use that. :)

You could even reuse most of the steam turbine code. You'd just need to change the liquid filter, and the model. Well, if you make the model, I'd be happy to do the coding.

I should add a block-with-shaft to the template library.

**Comment by Domi1993** [comment]
Something like this here

https://youtu.be/_OymET8YGWc

With the same sound as it is in the Video :)
