### ISSUE TITLE
Sound on Fire Detector

### ISSUE THREAD

**Issue by Safranil** [Electrical-Age/ElectricalAge#448]
Hello,

Can you add a sound to the Fire Detector when it detect fire like in real life or add an alarm with this sound ?

See this for example : https://www.youtube.com/watch?v=utn4Mrd9BcM

**Comment by cm0x4D** [comment]
Ok, the alarm should be pretty easy to implement.

I ask myself if I should add the alarm sound to the existing fire alarm or if I should create a new fire alarm working with batteries and only this one makes the sound, but does not provide an output signal...

**Comment by Safranil** [comment]
The second option sounds good :)

Do you have planned a fire sprinkler system ? If not, it can be good (if not too hard) to add this to stop fire propagation. I remember some storm in my wood house and the fire start because the rain doesn't reach the fire...

**Comment by cm0x4D** [comment]
No, at least not at the moment. Currently some mechanical stuff is added, but in order to add such a system we would need to add a pipe subsystem for liquids and we just do not have the resources for such things.

**Comment by Safranil** [comment]
It's ok, no problem.

**Comment by Baughn** [comment]
I am plotting such things. :-)

I wasn't planning a fire sprinkler, however. Mostly because it, well... it wouldn't be used very much. What's the scenario you're imagining?

**Comment by Safranil** [comment]
My previous example with a wood house and the storm, and on my server, my friend use RailCraft and the Raw Firestone (http://ftb.gamepedia.com/Raw_Firestone) 

> When it is held, the area around the holder will catch fire.

But indeed, I think there are too little scenario and it wouldn't be used very much.

**Comment by bowserjr2424** [comment]
Just get the fire extinguisher mod

**Comment by cm0x4D** [comment]
Ready to merge into develop [here](https://github.com/Electrical-Age/ElectricalAge/pull/477). So it is basically done and will be part of the next release.
