### ISSUE TITLE
Issue with ModBus

### ISSUE THREAD

**Issue by peekomo** [Electrical-Age/ElectricalAge#451]
Running this concurrent on the same box produces an error even if modub is not enabled.  Disabling the mod allows the server to boot.

See end of crashlog:

http://pastebin.com/404Df3Sh

Thanks for your time.

**Comment by bloxgate** [comment]
I have a fix for this on my repository, I'll PR it sometime tomorrow.

**Comment by cm0x4D** [comment]
Fixed in develop.

**Comment by enterprise12nx** [comment]
So..what do i do while i wait, i cannot play is there a fix i can apply @cm0x4D as i assume the next update is a long time away

**Comment by bloxgate** [comment]
You could use one of the dev builds available over at http://ci.safranil.fr/job/ElectricalAge/. They should be fairly stable, though keep in mind there will likely be bugs and incomplete features.

**Comment by enterprise12nx** [comment]
ok thanks!
