### ISSUE TITLE
[new feature request] Wireless fire alarms or emergency systems

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#460]
It'll be easier and safer to play Minecraft with emergency systems running in the background(survival). #

**Comment by cm0x4D** [comment]
Currently you can connect the fire alarm directly to a wireless signal transmitter. Should do the trick for the most cases or do you have a particular case where the fire alarm really should be wireless directly?

**Comment by Baughn** [comment]
I'd be against that. The game is way more fun when it's played with legos, rather than single, unified magic blocks.

**Comment by ghost** [comment]
It is kinda annoying paying both in places where you only have room for one firedetector

**Comment by cm0x4D** [comment]
Agree with @Baughn, two blocks is not that much at all.

**Comment by ghost** [comment]
Well ok.
