### ISSUE TITLE
[feature idea] multiblock chips

### ISSUE THREAD

**Issue by ZimmermannFlorian** [Electrical-Age/ElectricalAge#461]
My idea is a multiblock chip with more than 4 in or outputs for thinks like a JK-Flip-Flop or a bigger programmable ic.

**Comment by cm0x4D** [comment]
Well, they are already pretty big for SMD chips ;-)

But seriously there are imho more disadvantages than advantages of such a chip. The two cables connected to two ports on the same side would connect directly if one of them is not colored differently, so it would be still a mess to wire them. The JK Flip Flop is already available.
