### ISSUE TITLE
[issue] placing alarm switches inside blocks is not working

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#462]
It seems impossible to place them inside blocks how do you do it, it doesn't work...

**Comment by cm0x4D** [comment]
What do you mean exactly by alarm switches?

**Comment by ghost** [comment]
just normal switches I cant place them inside blocks

**Comment by ghost** [comment]
Hello you still here @cm0x4D ?

**Comment by cm0x4D** [comment]
Why should it be possible to place a switch inside a block?

**Comment by ghost** [comment]
I tried it wont work.

**Comment by cm0x4D** [comment]
That does not answer my question, why would you place a switch inside a block?

**Comment by ghost** [comment]
Its been possible in the tutorials but I cant get it to work.

**Comment by cm0x4D** [comment]
Ah. You can place a block afterwards on the switch by using the EA wrench key (defaults to C) and placing any block on the switch.

You might prefer the [IRC](https://qchat.rizon.net/?channels=electricalage) channel or the [gitter](https://gitter.im/Electrical-Age/Support?utm_source=share-link&utm_medium=link&utm_campaign=share-link) support channel for such questions as there is almost always someone online that might help very quickly.
