### ISSUE TITLE
Power Lines and power plant control panel and a few ideas

### ISSUE THREAD

**Issue by mattt628** [Electrical-Age/ElectricalAge#463]
I love this mod but i hate having to put the power lines underground from my power plant so it would be cool to have power lines with actual poles. Another idea would be a control panel where you could see if a house/ building had a black out and where you can shut down lines with out having multiple switches and if you guys could put some monetary system in where people had to pay for there power from like a computer or terminal and it would get shut off when they didn't pay automatically that would be really cool. One last idea is maybe traffic lights that you can put on overhead wires and have a controller box for that too that would be cool too.
(New Items Requested)

**Comment by bloxgate** [comment]
The power poles are coming soon. See e50a087

**Comment by mattt628** [comment]
Cool what do you think about the other ideas?

**Comment by Baughn** [comment]
Your control panel is possible to build with things we already have. A suitable combination of displays, signs, switches and signal processors... it'd be hard, yes. Here's an example: https://brage.info/e12/#9

There are other mods which handle money, but the base problem there is that it's nearly impossible to build a working monetary system in modded minecraft. What's it supposed to be based on?

Anyhow, while I'd love to have _some_ kind of working monetary system, it's way out of scope for EA.

**Comment by mattt628** [comment]
Thanks for the example and the pricing i'm not sure how to do that so i'm not sure what it should be based on a flat fee could work better.

**Comment by Baughn** [comment]
A flat fee of _what_? :)

**Comment by mattt628** [comment]
Maybe using universal coins mod like 25 coins

**Comment by mattt628** [comment]
Or if you guys want to but money into electrical age then it could be like 50 dollars

**Comment by mattt628** [comment]
What do you think about the traffic light system? No other mod that I can find has that.

**Comment by melindaendv** [comment]
Immersive engineering compatibility would be nice. This way you don't have to write up a whole set of power line code just make a few blocks that adapt the systems together. and be reverse compatible.

**Comment by bloxgate** [comment]
Power lines are already in the upcoming 1.12 version IIRC.

**Comment by Baughn** [comment]
They're in whichever version is released after I manage to finish them. We're not going to wait for that before 1.12, and we're not going to sit on it for long after merge either.

**Comment by Baughn** [comment]
As to IE compatibility, for various reasons that's not likely to happen. The way EA works makes anything cross-mod... Difficult.

But I did copy some of their powerline code, so there's that. :P
