### ISSUE TITLE
Steam Turbine

### ISSUE THREAD

**Issue by mattt628** [Electrical-Age/ElectricalAge#465]
How do you even use the steam turbine? it wasn't on the tutorial map.

**Comment by cm0x4D** [comment]
We do not give support on github issues. Please use the official support channels on [IRC](https://qchat.rizon.net/?channels=electricalage) or [gitter](https://gitter.im/Electrical-Age/Support?utm_source=share-link&utm_medium=link&utm_campaign=share-link) for such questions as there is almost always someone online that might help very quickly.
