### ISSUE TITLE
No generate amps and wt

### ISSUE THREAD

**Issue by salatets** [Electrical-Age/ElectricalAge#468]
In all the possible sources of energy does not generate A and Watts.  Version   BETA-1.11r51.
![2016-06-29_16 24 28](https://cloud.githubusercontent.com/assets/20206844/16454034/ab208814-3e17-11e6-9d75-e4e1bf6de242.png)
![2016-06-29_16 24 43](https://cloud.githubusercontent.com/assets/20206844/16454139/25f68cb4-3e18-11e6-9a54-1b9cc22484ed.png)

**Comment by bloxgate** [comment]
You don't have anything hooked up to use power, so the power isn't flowing anywhere. Hookup something that's using power and you should see power moving through the wires.

**Comment by salatets** [comment]
That's connected to multiple devices. A and Watts are not present.
![2016-06-29_17 02 41](https://cloud.githubusercontent.com/assets/20206844/16454993/7e9df1ec-3e1b-11e6-8f05-6d6cdc990280.png)

**Comment by bloxgate** [comment]
That battery should have a ground on the negative terminal. It doesn't look like the furnace is running. ~~Try increasing the line voltage to closer to 50v, it might be too low for the charger to run.~~

EDIT: Just checked, that setup should be working fine, except for the missing ground on the battery. Tried it myself and got power.

![2016-06-29_09 19 30](https://cloud.githubusercontent.com/assets/2079324/16455669/cdc0a81e-3dda-11e6-9dd9-f6b01c67c25d.png)

**Comment by salatets** [comment]
Thank you for taking the time bloxgate
