### ISSUE TITLE
Z-fighting in 50V turbine model

### ISSUE THREAD

**Issue by Sukasa** [Electrical-Age/ElectricalAge#47]
Looks like the 50V turbine model has some z-fighting at the 'connector' polygons where it connects to medium-voltage cable.

**Comment by Dolu1990** [comment]
Hmmm yes i must fix that, We are not sur to keep the 50V turbine model. maybe remplacing by the 200V turbine model with color swap for the moment. What do you think about that ?

**Comment by Sukasa** [comment]
That certainly would keep the graphics consistent with the other 50/200v machines, yes

**Comment by Dolu1990** [comment]
Ok, i kill the 50V turbine model in next update ♫♪

**Comment by Dolu1990** [comment]
Done :) in next release
