### ISSUE TITLE
Switch to semantic versioning.

### ISSUE THREAD

**Issue by cm0x4D** [Electrical-Age/ElectricalAge#475]
How about to switch to semantic versioning in the next release.

This would be 1.12.0 and not anymore 1.11r52.

Then new features will increment minor and bugfixes will increment patch level.

@Electrical-Age/devs What do you think about?

**Comment by Baughn** [comment]
All for it. For those not too familiar, here's a writeup: http://semver.org/

**Comment by metc** [comment]
We do not have a regular release cycle, so IMO semver makes sense for the mod and not the version numbers are formatted in `Y.MM` like for Ubuntu.

Should we still include that we are in beta ? Should we use an additional number to indicate which version of the Minecraft API we are targeting ?

**Comment by cm0x4D** [comment]
> Should we still include that we are in beta?

Imo no.

> Should we use an additional number to indicate which version of the Minecraft API we are targeting?

Would probably make sense, but the resulting number will be quite long and cumbersome. So I am uncertain about this...

**Comment by cm0x4D** [comment]
4x Yes, 0x No. 
So the decision has been taken. Next release would be then **1.12.0**. I updated the concerned milestone.

How about to remove the BETA from the version? Does it still makes sense? Guess we have the next vote...

**Comment by AMIDIBOSS** [comment]
You might remove all bugs, disable all the unstable features, make the mod version as stable as possible, and call it non-beta. Can't wait for 1.12.0 to come out!
