### ISSUE TITLE
Bug with signal blocs

### ISSUE THREAD

**Issue by XxNatarsxX** [Electrical-Age/ElectricalAge#48]
Hi, when I place a bloc (for example, an voltage probe), I can't place correctly this bloc because it's automatically oriented to the west, So, actually, are there a correctly version?
![2014-06-21_13 43 19](https://cloud.githubusercontent.com/assets/7950043/3348646/9ca7a3f0-f939-11e3-9cc5-113adc305c61.png)
In this picture, all voltage probe have the same wire and the same parameters
![2014-06-21_13 43 50](https://cloud.githubusercontent.com/assets/7950043/3348647/9cad70e6-f939-11e3-892f-d5ab4e515db3.png)

I use ElectricalAge_BETA_1.4.6d

**Comment by Dolu1990** [comment]
Hi, do you have try to use the wrench ? and right click on ?

**Comment by XxNatarsxX** [comment]
Sorry for this post, I didn't see the wrench, and for the signal precessor, I didn't understand how it work. Thank you very much

**Comment by Dolu1990** [comment]
For the signal processor you can write one equiation that can take in input each of 3 side input.
There are some usage into tutorial map, and tutoAll map :)
