### ISSUE TITLE
New Way to put light bulbs and wires in.

### ISSUE THREAD

**Issue by mattt628** [Electrical-Age/ElectricalAge#482]
Could you guys make and easier way to place light bulbs and wires into lamps. I build a lot using the lamps and that takes the longest so I was hoping you could make a faster way to put the bulbs and wires in?

**Comment by Dolu1990** [comment]
Hmm maybe could make that maj + item in hand place it inside it ?

**Comment by cm0x4D** [comment]
At least for the bulb that would be quite useful in order to replace defect ones.

**Comment by mattt628** [comment]
That works

**Comment by cm0x4D** [comment]
Pull request in progress: https://github.com/Electrical-Age/ElectricalAge/pull/493
