### ISSUE TITLE
Power socket on front of Fuel Generator

### ISSUE THREAD

**Issue by bowserjr2424** [Electrical-Age/ElectricalAge#484]
I thought it would be cool to add a power socket on front of fuel generator for portability or something
50v socket on 50v fuel generator (obviously) and 200v socket on 200v fuel generator

**Comment by cm0x4D** [comment]
Socket? Afaik that feature is not functional yet and might never be or do you mean that it should be possible to connect a wire to the front? That is already possible.

**Comment by bowserjr2424** [comment]
I know the power socket doesn't work yet but it's just an idea

**Comment by cm0x4D** [comment]
Ok. I am not really a fan of that socket idea after all (like most active EA devs) - so it is uncertain if that feature will ever make it to a release...

**Comment by cm0x4D** [comment]
Power socket idea is de facto "dead".
