### ISSUE TITLE
New way to configure transformers

### ISSUE THREAD

**Issue by bowserjr2424** [Electrical-Age/ElectricalAge#485]
Transformers are very confusing, it would be nice to be able to type in a voltage on both sides and then it would tell you how many cables it needs

**Comment by bloxgate** [comment]
The transformer converts using the following ratio, Cables on yellow side : cables on green side. It shouldn't be too hard to solve for how many cables you need if you know the input voltage and desired output voltage.

**Comment by cm0x4D** [comment]
No they are not confusing at all. 

It is Vout/Vin = Nout/Nin or ratio = Nout/Nin. Where V are the respective voltages and N the number of cables on each side.

The mod should imho have an educational aspect, where the users start to investigate the basics of electricity like for example the voltage/windings-ratio on transformers.
