### ISSUE TITLE
Let's use Reviewable for code reviews

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#496]
Aka. https://reviewable.io/

That can be done on an individual basis today, just by going there, but it's possible to turn it on by default for the EA repository. I'm familiar with most of the concepts it involves, and it should be a vast improvement on plain GitHub PRs.

Don't take my word for it, though. Click the link, look at the demo PR, and try it out.

**Comment by metc** [comment]
Looks interesting and yes, this is much dev-friendly to review PRs. 
They are so many services like this one for code reviews, if you are familiar with it, why not try it (they have a LGTM smiley :P)...
What is maybe missing with this tool is a code quality review. Sonar or Codacy offer this and this could be interesting maybe.

**Comment by cm0x4D** [comment]
We're already on Codacy: https://www.codacy.com/app/cm0x4d/ElectricalAge/dashboard.

**Comment by cm0x4D** [comment]
EA is on reviewable.
