### ISSUE TITLE
trouble with signal prossesors

### ISSUE THREAD

**Issue by redstonegenious** [Electrical-Age/ElectricalAge#50]
I'm trying to make a formula to calculate the possible power that is able to be created based on how bright it is and how much wind is in the area without interference from batteries and power consumers. but i cant find out how to use the possessor using advance functions because there is no tutorials about the subject. Is their anyone who knows more than the basic functions. I have been doing some testing and found out A,B,and C are sides,battery Charge Is to calculate how the battery strength based on voltage,but it gets interference by generators and power Consumers. The last thing I know  is that every function cost one redstone.

**Comment by Dolu1990** [comment]
Hi, 
Yes sorry for the lack of documentation about that. 
In the TutoAll, near turbine there are 2 display that show 2 method of calculation
the method at the right take in acount perturbation :)

That remove most of glitch, you juste must calibrate it.
I add that in the next release of  electricalAge_tutorial map :)

**Comment by Dolu1990** [comment]
There the source code of equiation solver : https://github.com/Dolu1990/ElectricalAge/blob/1.7.2/mods/eln/solver/Equation.java

At line 38 is declaration of function. Maybe that could help you.

**Comment by redstonegenious** [comment]
I have studied lua and JavaScript but i don't know this language.
