### ISSUE TITLE
[Questions] A few questions about EA

### ISSUE THREAD

**Issue by iancbogue** [Electrical-Age/ElectricalAge#504]
1: What is different in the upcoming r52?
2: How can I fix orange lights on shaders?
3: Can we download the map shown in the pictures on the website?

I know this probably isn't the best place to post this, but whatever!

P.S: Also, it would be cool if you added things like air conditioners, heating furnaces, vents and vent covers and thermostats. Whew that was a long one! I bet it would look cool considering the models you've made. Just wanted to make the suggestion. There would be the 50V and the 200V. And on the thermostat, you would have temperature controls and you could see the temperature. And you would have to put in wires as well for the different AC units as well as a battery or battery pack to power it.

**Comment by cm0x4D** [comment]
> 1: What is different in the upcoming r52?

We will see, you can read the commits for the develop branch to get an idea. Quite some improvements for the mechanical part are on the way and bug fixes...

> 2: How can I fix orange lights on shaders?
> 3: Can we download the map shown in the pictures on the website?

I can not answer these two, as I never played with custom shaders nor do I have access to the map.

> I know this probably isn't the best place to post this, but whatever!

Contact us over IRC (#electricalage channel on irc.rizon.net) or Gitter (https://gitter.im/Electrical-Age/Support) for support.
