### ISSUE TITLE
[Bug] Whenever re-entering my world, I have to jump through hoops to get lights on.

### ISSUE THREAD

**Issue by iancbogue** [Electrical-Age/ElectricalAge#505]
Let me give a step-by-step:
1. I log in to my world.
2. I see that my lights are off, even though I exited with them on.
3. I go over to my control panel and light switches.
4. I see that the switches are on, but the lights are off.
5. I go to the lamp supply.
6. I reset the wireless channels
7. I turn the switches on for the lights.
8. It lags a bit, then the lamps start to flicker (fluorescent) and then stay on.
9. Lighting is sluggish to update, and you guys really should work on some new bulbs. With ranges of 20, 25, and maybe 30 blocks, they would work great in places like warehouses and factories that sometimes have ceilings higher that 14 or 15 blocks.

And also, how do I use the new plugs/sockets?

Any help appreciated!
-Ian (minecraft: icbogue)

**Comment by bowserjr2424** [comment]
You probably have it wrong, try the tutorial map. Also the sockets don't work

**Comment by bloxgate** [comment]
The sluggish lighting updates have already been reported in #474

**Comment by iancbogue** [comment]
Yeah, I already saw that issue, it fixed for me. The main problem was the wireless networks not working properly. I'll have to make sure that they're working alright now. And will they be adding functionality to the sockets?

**Comment by AMIDIBOSS** [comment]
try installing other forge version

**Comment by jrddunbr** [comment]
Does this still happen? Might want to close this, I've never experienced it.

**Comment by iancbogue** [comment]
Umm I'm not actually sure as I gave up on 1.7.10 a while ago in favor of 1.12. That instance of the game might also be corrupt so I wouldn't be able to check. I'll go ahead and close it since it's been over 2 years 😂.

**Comment by jrddunbr** [comment]
Neat. I'm just going through issues since we're bound to close old 1.7
tickets with 1.12 coming soon.

**Comment by iancbogue** [comment]
LOL disregard what I said on the other comment. That's awesome that 1.12 update is on its way!
