### ISSUE TITLE
Power Plant ideas 

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#507]
Existing solar panels are called small
Will there be any Type of medium,  Big, other types of solar panels? 
Maybe there'll be other types off wind turbines as well? 
I don't think you're going to leave it like that! 
May I sugggest other things, like Nuclear Power Plants! 
And the most important thing - When r25 flows out?

**Comment by bloxgate** [comment]
See #185 
The milestone for version 1.12.0 (r52) does not yet have a due date, so I can't help you there.

**Comment by cm0x4D** [comment]
The resources for the mod are very limited, the main devs have moved to other projects and I do not have the time to contribute that much, so...

> Will there be any Type of medium, Big, other types of solar panels? 

Probably not. You can chain the panels to any needed size, so there is no imminent need for that.

> Maybe there'll be other types off wind turbines as well? 

There seem to be quite a lot of problems with big objects and lightning in  Minecraft and I personally have no intent to go trough that, so do probably the other devs...

> May I sugggest other things, like Nuclear Power Plants! 

I ask myself is this really needed? To my knowledge there exists already mods that provide nuclrear rectors and as long as you can produce steam using them, you should be able to construct a nuclear power plant using @Baughn's steam turbine.
