### ISSUE TITLE
Energy Meter bug

### ISSUE THREAD

**Issue by yannic312** [Electrical-Age/ElectricalAge#508]
I just discovered this bug while building my house: I have an Energy Meter, set it to "prepay mode", enter an energy value and let some power run through it. As long as I'm playing it works normally, but when I leave and re-enter the world and look at the Meter, it is set to "counter mode" again!

**Comment by AMIDIBOSS** [comment]
This is a bug, and i needs to be fixed. It's very anoying,especially on a server. I try to sell power and make my players pay from energy i sell them. It seems I'll use counter mode anyway i prefer prepay. If u can tell me why u need this meter, i may tell you how to use it with counter mode/CPU/some other special devices if u wish

**Comment by yannic312** [comment]
I need the prepay mode because I am making a world for a server where players must pay for electricity, and if they dont pay, their power should get cut off! There are already like 10 meters and it's really annoying to reset them each time the world gets reloaded... It would be really useful if you could tell me how to use it with counter mode :)

**Comment by bookerthegeek** [comment]
You can set up a counter circuit that turns on when a specific number of pulses have passed.  Then have a switch turn off the power to the counter.

**Comment by cm0x4D** [comment]
Issue is fixed in branch develop and will be part of the 1.12.0 release.
