### ISSUE TITLE
Single-use battery Question/Bug

### ISSUE THREAD

**Issue by Oscariremma** [Electrical-Age/ElectricalAge#509]
I have a question, should i be able to charge a Single-use battery?

![battery1](https://cloud.githubusercontent.com/assets/16071372/17838176/805f1f04-67c6-11e6-9601-0edc5da64f07.png)

![battery2](https://cloud.githubusercontent.com/assets/16071372/17838175/805a4cb8-67c6-11e6-8e20-d0f9fac797ae.png)

**Comment by AMIDIBOSS** [comment]
No, they'll overheat and explode i u do that
