### ISSUE TITLE
in-game wiki upgrades and game crashes from memory shortage 

### ISSUE THREAD

**Issue by redstonegenious** [Electrical-Age/ElectricalAge#51]
It gets annoying having to constantly switching to the tutorial world and your other world. plus it fills up the memory and eventually causes the game to crash. can you make the In-game wiki also carry information that is full of info how to set it up and it's special abilities.

**Comment by Dolu1990** [comment]
Hi,
For the ingame wiki, Yes it's possible to add information. and that is already ready to that. That juste need time, and for the moment we have to mutch things to do :(

For the fillup memory i add that into my todo task for directly after current task :)
thanks for feed back

**Comment by Dolu1990** [comment]
A big memory leak (and stupide XD) was resolved in last update. I think that solve your problem.
For ingame wiki, off course it's possible to add additional information. but i'm realy busy with loot of task :( 
A online wiki was created at http://wiki.electrical-age.net/index.php/Main_Page
Maybe on possible thing is to create a section that get screen shot of tutorial map + more explaine ?
