### ISSUE TITLE
State of wiki.electrical-age.net

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#510]
@KimBruning just attempted to add a new user, which apparently returned a lot of internal errors. Not permissions errors; 500s.

What's the situation? If you don't have time to maintain it, then I could do so. I even have a machine to run it on, in case you aren't comfortable giving me access to that one.

**Comment by metc** [comment]
We updated some time ago the wiki to MediaWiki 1.27.0 (running PHP 7). It seems that the `account_requests` table is missing, this is why you cannot create a new user:

```
Error: 1146 Table 'account_requests' doesn't exist (localhost)`
```

We do not use the wiki very much so nobody reported the issue, sorry for that. I am looking for a patch.

**Comment by metc** [comment]
I updated the `ConfirmAccount` extension, the issue should be fixed. Could you try again to [create the new account](https://wiki.electrical-age.net/index.php?title=Special:CreateAccount) ?

**Comment by AntonBoch1244** [comment]
@metc Special:CreateAccount is not work for me i use Special:RequestAccount and it work.

**Comment by metc** [comment]
What is your username @AntonBoch1244 ? You must be a bureaucrat to be able to create an account.

**Comment by ghost** [comment]
Account creation works now. Now we just need more people to create accounts for ;-)

**Comment by ghost** [comment]
(account for draggster99 was created correctly now, btw)

**Comment by cm0x4D** [comment]
Seems to work now.
