### ISSUE TITLE
Default branch should be 'develop' after all...

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#512]
Because, if you just take a glance at the github page, it looks like development has entirely stopped. That isn't true, and the 'develop' branch shows it to be false, but I encountered several people who _think_ that it's true.

**Comment by Domi1993** [comment]
I wonder me that here nothing happens since 4 Months, but now i see that there is changed something in the develop branch.

How i can clone the Develop Branch?

**Comment by cm0x4D** [comment]
@Baughn: Totally agree.

@Domi1993: You can checkout different branches after you cloned the repo: https://git-scm.com/docs/git-checkout

**Comment by Domi1993** [comment]
ok i have now the latest build but how i can us this Gasturbine?

**Comment by Baughn** [comment]
Please ask questions this on gitter or IRC, not in an unrelated bug report.

**Comment by cm0x4D** [comment]
Develop branch is now default branch.

@Electrical-Age/devs What about renaming the branch 1.7.10-MNA to releases?

**Comment by metc** [comment]
IMO `1.7.10-MNA` is fine and not so important. The user will download the release from the website or from the releases tab on Github.
If we want to use Git flow, we should create the `release` branch only when we are working on the production release, and then merge it to the master `1.7.10-MNA` branch.

**Comment by Baughn** [comment]
"1.7.10" is fine, minecraft being minecraft. The "-MNA" part might confuse, but I don't see it being a real issue. We'll probably end up with a distinct 1.10 branch at some point.

**Comment by Baughn** [comment]
Looks complete.
