### ISSUE TITLE
(IDEA) 12.5kv Tazer  (Simple Electrical Weapon)

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#513]
(IDEA) 12.5kv Tazer  (Simple Electrical Weapon)

As the name below says, it's a simple electrical weapon, used by clicking left mouse button!
Powered from bateries, to be sure.

A concept of crafting recipe:
![tazer](https://cloud.githubusercontent.com/assets/10089795/18751987/3f369a82-80e1-11e6-9616-52a899f24ddc.png)

It takes a little bit of energy when used.
It should deal from 2 to 6 dmg.

**Comment by cm0x4D** [comment]
Duplicate of #140
