### ISSUE TITLE
(IDEA) Compact Electrical box (9 Components in 1 Block!)

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#514]
This would be the great idea, to make it able to put multiple components in one block to make electrical circuits more compact!
![eb1](https://cloud.githubusercontent.com/assets/10089795/18807911/069b1742-8254-11e6-92c9-215595751898.png)

This block has 4 I/Os, set by components placed in slots:
-Top Center
-Middle Left
-Middle Right
-Bottom Center

This will have gui that allows to put components and mantain conection between them!
![eb2](https://cloud.githubusercontent.com/assets/10089795/18807882/61edb75e-8253-11e6-8d04-1aa6d2b2d3f6.png)
What do you thing about that? Any other ideas for that?

**Comment by mattmtgaming005** [comment]
i like this idea

**Comment by Baughn** [comment]
I've been considering making something akin to Super Circuit Maker's system, for 1.10. No clue when I'll get around to it, though.

**Comment by AMIDIBOSS** [comment]
what's the diffrence between Super Circuit Maker's system and my Electrical component box?

**Comment by Baughn** [comment]
It's in-world, and somewhat larger. Not just nine slots.

Otherwise it's the same basic idea. If I do this I'll do it the SCM way, though.

**Comment by Domi1993** [comment]
This SCM look interesting, in ELN it could be a 2x2 box like the one for the signalprocessor. in this box breakers and relays can be added and custom wired to made a controlcircuit in it, like the real life switch cabinets.

If it's possible to codewhy not make that buttons and dataloggers can be mounted in the door too.

Thats something like SCM it has but in ELN-Style

**Comment by bookerthegeek** [comment]
Or better yet, add compatability so that you can build it on SCM.

**Comment by Domi1993** [comment]
You can acctually

Just use a voltage to redstone converter/redstone to voltage converter
