### ISSUE TITLE
Problem when remove mod

### ISSUE THREAD

**Issue by THEJean-Kevin** [Electrical-Age/ElectricalAge#515]
Hello,

i would like to remove your mod (This is a great mod, but for performance reasons we are forced to remove) and when it's removed and i come back on the map, i crashed. 

This is the crash report : http://pastebin.com/aWGyTn4b

**Comment by AMIDIBOSS** [comment]
And if you put the mod back in, will it work?

**Comment by Domi1993** [comment]
IMPORTANT! MKE A BACKUP OF YOUR WORLD BEFORE DOING THIS

You can try out if it works when dou delete the some files in the data folder.
- electricalAge -1
- electricalAge 0 
- electricalAge 1
- eln.worldStorage
- GhostManager
  This files are only in world saves with the i didn't find this files in vanilla worlds.
