### ISSUE TITLE
Out Of Memory error on empty servers.

### ISSUE THREAD

**Issue by DonBruce64** [Electrical-Age/ElectricalAge#525]
Having an issue where servers hosting a world with Electrical Age will slowly leak RAM until they run out of memory, but only when there are no players present.  The time to Out of Memory (OOM) depends on the complexity of the system in the world, but I suspect it is directly related to the number of lights as the OOM always occurs during the NBT saving process of LightBlockEntity TEs.  On my server with 400+ lights this occurs in less than two hours, though it can be replicated with the older EA tutorial map on a server where it takes about 15 hours to run out of RAM.  Either server will run indefinitely if I keep a player logged in, so it's something about how EA handles itself when nobody is around.

Log and crash report attached for EA tut map.
[crash-2016-11-01_14.41.12-server.txt](https://github.com/Electrical-Age/ElectricalAge/files/567533/crash-2016-11-01_14.41.12-server.txt)
[fml-server-latest.txt](https://github.com/Electrical-Age/ElectricalAge/files/567534/fml-server-latest.txt)

**Comment by cm0x4D** [comment]
Thanks bruce, that is something to work with...

**Comment by cm0x4D** [comment]
@DonBruce64 I could not reproduce the bug on macOS and Ubuntu (in a docker container) and the only difference is that I am not using any other mod aside of EA. So this might be some bad inter-mod interaction between EA and CoFH.

I would like to do some tests with the CoFH mod installed, but I do not find the exact version you are using (3.0.0B9-40) as a dev version, so I will use the newest version 3.1.3-328 of CoFH. Maybe if you find the time you could do a favor with those two tests:
- Try the same version of CoFH as I use and check if the problem occurs too
- Try to run the server without CoFH and see if it works if EA is the only mod.

**Comment by cm0x4D** [comment]
With 1.12.0 there seems the same problem, but this time even if EA is the only mod installed :(

**Comment by cm0x4D** [comment]
IMPORTANT: For all having this issue, please give us as much information as possible like:

- Operating system including version (kernel version if possible)
- Used Java VM including version
- List of all involved mods including their version
- Anything else that could help...

**Comment by bimbam2103** [comment]
Ubuntu 14.04 LTS
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
Only ElectricalAge - no other mods
The entire server dir can be downloaded from http://s1.xs-project.de/downloads/mc_ea.tar.gz

Machine: (/proc/cpuinfo)
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x1
cpu MHz         : 2394.454
cache size      : 15360 KB

The CPU is x2 (two XEON CPUs)

RAM: 32 GB DDR3 ECC-RAM

Kernel: 3.13.0-Kernel

**Comment by cm0x4D** [comment]
#362 is the same problem

**Comment by Baughn** [comment]
I've yet to spot this happening on Erisia. But, it occurs to me, that might be because Erisia runs a large modpack which has multiple fake players, not to mention chunkloaders.

**Comment by cm0x4D** [comment]
@bimbam2103 I have the server running on my Ubuntu 16.04 (Java 1.8u101) now for 10 hours. No problem at all, it does use about 1 GB currently, so again I can not really reproduce the problem.

I will try to test it on a 14.04 today to see if it might be related to a specific version of the OS (which would be somehow really odd).

**Comment by Baughn** [comment]
For reference: http://www.beyondjava.net/blog/how-to-count-java-objects-in-memory/

I'll try to make an Eln build including this code. Maybe we can at least figure out what's leaking.

**Comment by cm0x4D** [comment]
Ok. Everyone having trouble with this, please start your server with **-XX:+HeapDumpOnOutOfMemoryError** parameter and check if you can find a file called __*.hprof__ and send this file to us. We were never able to actually reproduce the problem ourselves.

**Comment by DonBruce64** [comment]
Hprof file is 2GB in size.  Good luck opening it.  I'm going to host it on my DropBox, but could you let me know when you download it?  I don't like to have chaff sitting in there and 2GB is a LOT of chaff.
https://www.dropbox.com/s/96njqmzn3svw05i/java_pid3672.hprof?dl=0

**Comment by cm0x4D** [comment]
Ok, have it. Thanks!

**Comment by cm0x4D** [comment]
After I had not enough heap to parse the heap dump (lol) I finally managed to parse the file and it is indeed EA that causes the problem:

I see that there are 77 pending chunks to save. Each of them is carrying more light handles. The biggest chunk has a size of 350 MB of data alone. Each light block seems to have about 25k light handles in its list, so I suspect that the lights are spreading faster than Minecraft is able to save them or the algorithm to remove the outdated light handles does not work.

@DonBruce64 Is it possible that the server did a spin-down of the HDD before the map was saved? This might explain why there were a lot of pending chunks around...

Anyway the problem is now pretty clear and I will have a look what can be changed in order to fix it. IMHO we do not need to save those light handles at all, as they have a very short lifecycle and they would be missing in map loading for just some frames.

**Comment by cm0x4D** [comment]
@DonBruce64 Could you take a dev snapshot version of EA [from here](http://ci.safranil.fr/job/ElectricalAge/360/) (might take still an hour to build) and let it run on your server to check if the bug is fixed or not?

**Comment by DonBruce64** [comment]
I'll get to work on building the version.  Not sure what you mean by "spin-down of the HDD before the map was saved".  Are you implying that the server's HDD span down at some point during the server run, or just any point in the life of the map?

**Comment by DonBruce64** [comment]
Just downloaded it.  Y'all have a stray dependency "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mcp/mobius/waila/api/SpecialChars".  Not sure if it's intentional, but I don't think WAILA should be a dep for servers.

Either way, the new build seems to have worked.  Have had my server up for over 4 hours with no RAM issue in sight.  Usually they come up on less that 2 hours.  I'd call this fixed.

Question: can I just swap out LightBlockEntity.java from this version into r50?  I'm not a fan of the new models and GUI, but I understand if this isn't possible.

**Comment by bloxgate** [comment]
~~@DonBruce64 Did you setup the dev environment with a --refresh-dependencies when you built it? That should get WAILA. It's needed to compile the WAILA integration in the mod.~~ Ah. Nevermind. See below.

**Comment by cm0x4D** [comment]
> Just downloaded it. Y'all have a stray dependency "cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mcp/mobius/waila/api/SpecialChars". Not sure if it's intentional, but I don't think WAILA should be a dep for servers.

That's a bug. I need to fix that asap. I used that class where I should not.

> Either way, the new build seems to have worked. Have had my server up for over 4 hours with no RAM issue in sight. Usually they come up on less that 2 hours. I'd call this fixed.

Good to know. Thanks for testing.

> Question: can I just swap out LightBlockEntity.java from this version into r50? I'm not a fan of the new models and GUI, but I understand if this isn't possible.

You have to try, the lightning code did not change for a while, so your chances are intact to be able to replace that class.

New models? Afaik the models did not change that much. For the icons, yes we thought it would add an educational aspect to the mod to have IEEE icons for a lot of components. Additionally we harmonized cable colors with the color of the machines. This changes seem to not please everyone. If this really troubles a lot of people, an idea could be to have a config that brings back the old icons, but as rendered pixmaps (I did this for the fire detector for example). Would be that an option?

**Comment by DonBruce64** [comment]
My mistake, you are correct, I meant icons.  My thoughts on that:

I see the reason for the schematic icons, though as a visual person it's easier for me to look for the shape of the model in the inventory rather than the schematic icon.  The relays and RIC circuit stuff is just fine as I've taken EE 101, but the batteries are impossible to tell apart now (sans the HV one).  If I used the mod enough I'd probably get used to it, so feel free to ignore the complaints of a fellow who publicly admits he hates change.

One thing that still throws me off is the new cable colors.  It used to be that light blue was 50V and green was 200V, so I keep placing green cables thinking they're 200V.  That makes for lots of holes when I hook a 50V cable to a 200V line.  As they now match the machines (didn't put two and two together until you mentioned it), I can't really complain.  I'll just have to learn better if I want to stop making TNT in my power plants.

Also, I'm aware that models can't be rendered in the inventory 1.8+, so I'm not going to ask you to bring them back.  I converted all my ItemRender GUI models to 32x32 icons a year ago for MFS when I found they didn't work.  Perhaps pixelize the battery icons to make it easier to tell what they are? Maybe a V for voltage, P for power, I for current, heart for life, $ for cost, and nothing for a single use?  Just a thought.

P.S. Best of luck to y'all with the 1.10 port.  I have little clue about blocks past 1.7.10 (I deal with multi-part entities and physics), so I can't imagine the fun you guys must be having with the BlockStates, Capabilities, and Properties.

**Comment by cm0x4D** [comment]
Thanks.

You could actually help me to get the icons back: Play the game in fullscreen and make screenshots of all items using an old version of the mod, then it is pretty simple for me to create pixelated versions of the icons.

Your idea for the batteries is quite good. I will see if I find time during ski holidays to do all this stuff...

**Comment by DonBruce64** [comment]
Finally got around to doing the icons (Gimp is a lifesaver).  Here's a sprite sheet of all the icons in 32x32 from r50.  I didn't split them up as I didn't feel like sending you 100+ icons.  I'm sure someone on your end knows how to use Linux enough to throw the PNG at ImageMagick and have it cut it up.
![eaicons](https://cloud.githubusercontent.com/assets/15241611/22360119/997dec18-e412-11e6-89d0-d8f4ef3c9220.png)

**Comment by cm0x4D** [comment]
Thanks, @DonBruce64. That works perfectly!

**Comment by cm0x4D** [comment]
By the way, the issue with the out of memory on empty server is fine now?

**Comment by DonBruce64** [comment]
As far as I could tell with the dev version you gave me, yes.  Do you know if the WAILA dep is gone?  From what I can tell this fix isn't in 1.13.0, but I can build from source if need be.
