### ISSUE TITLE
[Wiki] Failed to create dir on account creation

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#527]
On approving a new account on the electrical age wiki  ( using  https://wiki.electrical-age.net/index.php?title=Special:CreateAccount&AccountRequestId=1&wpName=CaliRailfan&returnto=Special%3AConfirmAccounts%2Fauthors&reason=I%27ll+approve+any+request+that+seems+to+come+from+a+human+being+%3A-%29 ):

I get the following error:

Warning: failed to mkdir "/accountcreds/e/el/ele" mode 0777 [Called from wfMkdirParents in /home/httpd/vhosts/electrical-age.net/wiki.electrical-age.net/includes/GlobalFunctions.php at line 2200] in /home/httpd/vhosts/electrical-age.net/wiki.electrical-age.net/includes/debug/MWDebug.php on line 300 Exception encountered, of type "Error" Notice: JobQueueGroup::__destruct: 2 buffered job(s) of type(s) EnotifNotifyJob, RecentChangesUpdateJob never inserted. in /home/httpd/vhosts/electrical-age.net/wiki.electrical-age.net/includes/jobqueue/JobQueueGroup.php on line 433 

Apparantly a permissions error? I don't have access to the server itself, so I'll have to ask someone to take a look!

**Comment by metc** [comment]
I accepted the account request for CaliRailfan. See #528
