### ISSUE TITLE
[Wiki][enhancement] Account request form

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#528]
The default account request page on the eln wiki is maybe a bit overdone for our purposes, and might scare people off.

Suggest cutting the form down to the minimum, as per

https://www.mediawiki.org/wiki/Extension:ConfirmAccount#Minimal_settings

**Comment by metc** [comment]
Hi,

We had to setup an account request page because we had quite a lot of fake/spam accounts.
As you proposed, we are now requesting only a username, email address and brief message. Thanks!

**Comment by ghost** [comment]
thank you! :-)
