### ISSUE TITLE
electric age mod not working on any forge

### ISSUE THREAD

**Issue by xZx-YourMum-xZx** [Electrical-Age/ElectricalAge#529]
ive tried forge 1.6/1,7/1,8 and none of the electric age mods work please help

**Comment by cm0x4D** [comment]
Please use official support channels here https://electrical-age.net/contact/ (IRC or gitter) for support.

**Comment by xZx-YourMum-xZx** [comment]
ive triend that but it doesnt tell me how to fix the problem

**Comment by cm0x4D** [comment]
You might want to actually ask on IRC or gitter for help. There is always someone (including me) around which might help you.
