### ISSUE TITLE
[BETA-1.5_r10] Machines are not oreDict aware.

### ISSUE THREAD

**Issue by MrGraphic** [Electrical-Age/ElectricalAge#53]
Tried only macerator - only EA ores can be processed.

**Comment by Dolu1990** [comment]
Hi, yes, that must be fixed.
Lot of things are not dictionary ore compatible, it's in road map :)
Thanks for feed back

**Comment by Dolu1990** [comment]
It's now my first todo task

**Comment by Dolu1990** [comment]
It's now fixed, that come in next release. That was a stupide forget XD
Thanks for issue : D
