### ISSUE TITLE
Breaker and Power  Resistor problem

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#530]
When trying to use the power resistor with the breaker the resistor stops doing its job. So I have 53.00v going into the resistor and from there it comes out to be 50.00v then i have it going to a breaker  then from there to a switch then a lamp supply. When using the lamp supply to turn on a light the resistor stops doing its job and sends the 53.00volts to the breaker tripping it. I have the breaker set to turn off at 50.00Volts.

**Comment by Baughn** [comment]
First of all, you don't need to break at 50V, and probably shouldn't; that's well within the normal range. "50V nominal" actually means that the cables will work up to 60-something volts.

But you're probably misunderstanding something. Can you drop by Gitter or IRC? Check the support page, and bring screenshots.

Github is not intended as a support channel, so closing.
