### ISSUE TITLE
Q: is this mod for 1.7.x or 1.6.x?

### ISSUE THREAD

**Issue by nolimet** [Electrical-Age/ElectricalAge#54]
I am a little bit confussed right now about if this mod is 1.6 or 1.7

**Comment by nolimet** [comment]
Never mind it's 1.7 so please change the tag to 1.7 somethimg beta ish

**Comment by Dolu1990** [comment]
Hi, it's minecraft 1.7.2.
About which tag you are talking about ?

i have forget to put in last release description that is Minecraft 1.7.2 need forge. sorry ^^
