### ISSUE TITLE
Error with lampposts

### ISSUE THREAD

**Issue by Russian123** [Electrical-Age/ElectricalAge#542]
Hello, to Build # 46 there is an error during installation with departure into the world of lampposts, flies and decora tion client. I write through Google translator)

**Comment by cm0x4D** [comment]
The translator did a pretty bad job. I am not close to have any clue what you actually mean. Could you post in you native language, maybe we can find a person that can translate this.

на родном языке, пожалуйста

**Comment by Russian123** [comment]
Здравствуйте, есть ошибка при установке фонарных столбов в мир, игра просто вылетает и больше карта не загружается. Build # 46

**Comment by Russian123** [comment]
Hello, there is an error with the installation of the lampposts in the world, the card is not loaded. Build # 46  
my translation

**Comment by Russian123** [comment]
http://rgho.st/6jx745bVn

**Comment by cm0x4D** [comment]
Ah, now i got it. The waila integration makes troubles when you look at the streetlights.

I discovered that yesterday too, a fix is on his way: #543

Thanks for the issue!

**Comment by cm0x4D** [comment]
Fixed in 37ffc194889d899167470cdc9d4626551c242317
