### ISSUE TITLE
Other to ELN converter

### ISSUE THREAD

**Issue by bowserjr2424** [Electrical-Age/ElectricalAge#561]
It would be awesome to have a nuclear reactor from IC2 to power ELN things. Maybe even take the ELN to other converter and make it do vise versa. PLEASE!

**Comment by Baughn** [comment]
That won't happen. It's a deliberate design decision.

The IC2 reactor has a config option to output steam. Try that, instead.

**Comment by AMIDIBOSS** [comment]
Eh, Try using Big Reactors instead. And forget about IC2, now it's TE era.
