### ISSUE TITLE
Thermal Probe will not connect electricty

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#562]
Thermal Probes will allow you to insert electrical wires, but will not update their model to match this, nor will they transmit electricity. Either electrical wires need to be exempt from fitting in the slot, or they should function like the copper wire.

**Comment by cm0x4D** [comment]
The thermal probe shares code with the temperature probe and by adding the feature to by able to measure the temperature of a cable using a temperature probe, this was accidentally added to the thermal probe too. It will be removed as it makes no sense.

Thanks for issue.
