### ISSUE TITLE
Cannot middle-mouse multiblocks

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#564]
Attempting to middle-mouse a multiblock should proxy to the base block, allowing you to middle-mouse any part of the multiblock to select it.

**Comment by cm0x4D** [comment]
If the middle mouse button is set to pick up items (which is iirc the default) it picks up the correct (sixnode) item. Did you modify the controls that you expect it to something different?

**Comment by OmegaHaxors** [comment]
It does work, but only if you select the block of the actual node itself. Any of the other blocks will fail to pickblock properly.

**Comment by cm0x4D** [comment]
Ok. It is probably the same issue for WAILA.
