### ISSUE TITLE
1.7.10 support!

### ISSUE THREAD

**Issue by Techokami** [Electrical-Age/ElectricalAge#57]
Wow this is a really neat mod! Too bad that, at a quick glance at the code, I can tell it will crash on Minecraft 1.7.10. This is due to some functions being depreciated. For example, getAABBPool() is gone (but can be fixed quickly by doing a search and replace operation, replacing "getAABBPool().getAABB" with "getBoundingBox")

Can't wait to see this mod be updated :)

**Comment by Dolu1990** [comment]
Hi :)
Yes i can change to getBoundingBox , and if there is not to mutch other minecraft function that have as name for example "func_65837 " i can release 1.7.10 version. But i think i can have the same code for 1.7.2 and 1.7.10 because of that (some function name change)
Do you know if it's possible to have the same jar for 1.7.2 and 1.7.10 ? (i think no)
sorry for my bad english XD

**Comment by Techokami** [comment]
Most of the changes SHOULD be compatible with 1.7.2, since the workarounds were added in the latest Reccomended versions of Forge. Another one to look for is world.getWorldVec3Pool().getVecFromPool, that got replaced with Vec3.createVectorHelper.
There are also some reobfuscations to watch out for. Some of them are particularly nasty, since they actually changed the function parameters and will not work between versions.
I suggest updating to the latest Forge Gradle, and target 1.7.10-10.13.0.1180, and see what breaks. I would have helped out, but your repository is missing the build scripts!

**Comment by Dolu1990** [comment]
Ahaha it's fun, i was just exploring that and see that Vec3 make the 1.7.10 crash ^^
Thanks for help :)
Basicly, i'm not a java guy, i come from electronic industry, it's the reason why i don't have a lot of know how about workspace setup and build script because we alwas use C/C++.

**Comment by Dolu1990** [comment]
Hmm it's realy cool, only 10 line to change : D

**Comment by Dolu1990** [comment]
Oky it's now released. I juste have one question :
Actualy i have do the release from forge 1.7.2 and that working on minecraft 1.7.2 and 1.7.10
Must i do release from forge 1.7.10 or that change nothing ?

**Comment by Techokami** [comment]
If you got it working on both versions, then you can release it as targeting 1.7.x (or, 1.7.2/1.7.10)
That way, your users will only need to grab one file and it will work on both versions of Minecraft 1.7.x :)

**Comment by Dolu1990** [comment]
oky ^^ thanks, release 1.7_r19 is like that, it's realy cool because it's always very borring to have to maintain 2 different version of code XD
thanks for help !
