### ISSUE TITLE
[QOL] Right click to install component

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#579]
I noticed that street lamps can have wires and bulbs can be installed in them by right clicking while holding relevant component. This functionality is very nice and needs to be implemented in various machines which can accept it:

Installing drills into the auto miner
Refilling pipes in the auto miner
Installing Ferromagnetic Cores
Placing regulators in machines
Upgrading panels with the Solar Tracker

It should not be used for things such as putting materials into machines, for example putting coal into a macerator as that would dramatically increase the instances of accidental inserts.

**Comment by cm0x4D** [comment]
The lamps were some sort of test for that functionality. If we want to adapt this to a broader set of blocks, I would prefer to have a generic way of doing that in one of the base classes. Should imo be not to hard to achieve.

**Comment by cm0x4D** [comment]
Changes are merged, will be part of the next release. Whenever you find another that would make sense, feel free to reopen the issue.
