### ISSUE TITLE
[Enh] Find some permanent samples for Turbines and generators

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#583]
The Steam and gas turbines + 3200V generators now have sound support thanks to @Baughn, but iirc we need samples we can redistribute. 

(If someone PR's a decent sample (needs to be fairly steady) I can loop it if need be. )

**Comment by cm0x4D** [comment]
I posted already samples on the PR.

> You can try these. 
[Turbines & Generator Samples.zip](https://github.com/Electrical-Age/ElectricalAge/files/679224/Turbines.Generator.Samples.zip)

They are adjusted to the "old" sound looping system. I have to adjust the samples to the new, much more powerful system once we finished it's implementation, but they are basically available.
