### ISSUE TITLE
Suggestion: Sandbox Mode

### ISSUE THREAD

**Issue by alffn** [Electrical-Age/ElectricalAge#587]
Electrical Age mod is really fun to play with. The features are neat, and the simulation is (maybe) accurate. But the thing is that sometimes components blows up if they heat up to the meltdown temperature of 160-ish degrees. It could be painful to fix things, and playing it could just be irritating if it keeps happening. Especially if the player just want to build things how they want.

So maybe, the mod should have an option at the config file to prevent components from exploding. Not just preventing the explosion, but also preventing the components from dismantling itself. Or how I'd like to call "Sandbox Mode".

If not, at least the config file could adjust the meltdown temperature to higher values.

I know this is not the definition of accurate simulation, but this would make this mod less confusing for those who can't do electricity like this.

**Comment by AMIDIBOSS** [comment]
Config already does disable explosions, there's no need "Sandbox Mode". If you want to play sandbox try GMod. But don't mind me wrong, the idea isn't bad.

**Comment by alffn** [comment]
It's ok, that's fine. Personally, I can do this mod myself without it exploding. But lots of people I know have been struggling with this mod... So I thought, I could suggest this.

But really, that's fine. Thank you for replying!
