### ISSUE TITLE
Compressor and plate machines don't work.

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#60]
I have checked the 50V one and the 200V one. I also checked the voltage and that the turbines are working correctly (I also tried with the power source) and just does not work. It receives voltage but no power, even if they have enough power on the cable and other machines on the same cable are working correctly.

**Comment by ivangouba** [comment]
Sorry, I didn't know that I have to put four items of what you want to process in order to get something. :$

**Comment by Dolu1990** [comment]
Hi ^^ no problem. 
power <=>  energy consumption. If there is no item to process => no energy consumption => no power.
