### ISSUE TITLE
Null casted to non-null

### ISSUE THREAD

**Issue by ArcasCZ** [Electrical-Age/ElectricalAge#604]
Server disconects people around place where something exploded.

Stacktrace: http://pastebin.com/S7zUfun9

Forge: Latest (1614)
Server core: Thermos (latest build)
EA: Latest 1.13.0

**Comment by cm0x4D** [comment]
Thanks for the issue, should be fixed in the next release. In the mean time try to avoid explosions ;-)

**Comment by cm0x4D** [comment]
Oh I fixed it already in 38a5c2348e0c7dfa1f1024e129d5d176cb5b393c. \o/

**Comment by ArcasCZ** [comment]
Is there any dev build or I have to compile it by myself?

**Comment by cm0x4D** [comment]
Yes, here: http://ci.safranil.fr/job/ElectricalAge/lastSuccessfulBuild/

Reopen the issue if it would not have been fixed.

**Comment by ArcasCZ** [comment]
Thanks :-) I'll let you know ;)

**Comment by ArcasCZ** [comment]
I have another one error - http://pastebin.com/ibgJErPs

**Comment by cm0x4D** [comment]
Are you actually using the Modbus RTU?

**Comment by ArcasCZ** [comment]
I don't even know what it is? :D

**Comment by cm0x4D** [comment]
This is very, very strange, do you used the dev snapshot when this happened?

The lines of the error do not match with the files in the actual code base, so I bet it is an older version...

**Comment by ArcasCZ** [comment]
Yep, it is before update. I found it in my TXT file. If it will happen now, I will let you know.

**Comment by cm0x4D** [comment]
If I did understand right it is just a warning during world unload... Anyway someone must have placed a Modbus RTU somewhere in the MC world before, which not very many people actually use or let's say know how to use...

**Comment by ArcasCZ** [comment]
http://pastebin.com/zckknyG3

Here's actual.

**Comment by ArcasCZ** [comment]
I'll make new issue for that.
