### ISSUE TITLE
Gray Grass

### ISSUE THREAD

**Issue by ghost** [Electrical-Age/ElectricalAge#608]
When i put grass over wires it turns gray
![2017-01-17_00 53 59](https://cloud.githubusercontent.com/assets/23726306/22010609/e9f14304-dc4f-11e6-8f21-ab0907ae3976.png)

**Comment by ghost** [comment]
I am running the latest update of Electrical Age and Forge. I also don't have any mods installed.

**Comment by cm0x4D** [comment]
Same as #142
