### ISSUE TITLE
[Feature Request]  Higher voltages (like 220kV and 380kV or lower)

### ISSUE THREAD

**Issue by MCPC10** [Electrical-Age/ElectricalAge#612]
Hi,
Wouldn't it be a good idea to implement higher voltages than power polas and/or special transformers? Like that you could use only one wire to power a whole city (or connections to other cities), because we are powering a whole city. So 3kV is not enough.

I've edited your Mod, so you have 220kV wire and 380kV wire and a 800V Trubine. But we prefer to use the original version on our private server. :)

Sorry for my english. :)

**Comment by AMIDIBOSS** [comment]
How did you added those wires? I tried as well but I'm now a coder...
I can't find it... Where they are registerd???
My friend already working on transmission tower mode (don't tell @Baughn)  l with voltage...
That is:
Tier 1 poles V * Next Tier multiplier = Transmission voltage
12,8 kV * 4 =51,2kV Yeah, seems about right.

**Comment by MCPC10** [comment]
You will need to search "Medium Voltage Cable" (use Ctrl + F) in Eln.java. Then you only have to copy and past the lines of code with a new subId, MVU (voltage of the wire), MVP (power of the wire), meduimVoltageCableDescriptor and stdCableRender200V.

Sorry for my english. :)

**Comment by AMIDIBOSS** [comment]
I found it myself. That is @Baughn helped me. But thanks anyway.
And again, I doubt we will add such cables. Consider using utility poles instead.

**Comment by cm0x4D** [comment]
Afaik higher tier poles are planned. @Baughn might know more details about those. Imho 220 kV or 380 kV cables on ground just do not feel right.

**Comment by MCPC10** [comment]
Yes, thats right ;)
Thanks for making this awesome project!

**Comment by Baughn** [comment]
Yeah, they are. There will be tier-two power poles in the next release (probably), at 51 kV nominal voltage.

If that isn't enough, then I don't know what to say. I would be interested in what you're doing that needs so much power, though. :)
