### ISSUE TITLE
Cables that handle more power and current?

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#62]
Yeah, that would be nice, because with the limitations they have now it' s difficult to make big projects. Even if it is not for big projects I think that those limitations are too low. Aso would be nice if you implement something like an electric counter wich measures the electricity used in kwh (or kJ) that works with some kind of coins or credits for servers.
Just some suggestions :)

**Comment by Dolu1990** [comment]
Hi,
Juste to syncronise, the idea for big system is to have all "station" using 200V (2KW), and inter station connection with 800V (4KW). Do you had this topology ?
For very big thing it's true that's a little short.  Maybe i must rise max power. without change power lost on cable. i must take time to re considerate that.

For electrical counter, it's a very nice idea : D How must be credit/coin ? =>  dedicated items ?
Additionaly, i can add block that check that the client don't has bypass the electrical counter.

**Comment by ivangouba** [comment]
Yes, you can add different types of coins (maybe only one type, to make it easier), made of copper, lead or alloy (not craftable, so players in a survival server can only earn them working for someone that gives the coins manually or selling things and not by crafting them which would be a bit OP). 
For the first thing, do you mean something like buildings working at 200V interconected by cables of 800V?

**Comment by Dolu1990** [comment]
for the first part =>  Why not create credit card ? it's more generic because the amount of the money on the card can be infinit ^^ and that use less space in inventory
for second part => yes, 50V is only for survival when you start the game.

For sure i want to add the energy counter system !

**Comment by ivangouba** [comment]
Yes, the credit card is a very good idea, but the counter is going to be prepay, or something like you have to pay every night for the electricity you have used in the day?

**Comment by Dolu1990** [comment]
Maybe we can add a system to fill the money on credit card ? for example some gold nugets for some credit on the card.
For electrical counter, you put the card and prepay for some KWh

**Comment by ivangouba** [comment]
For the first part: Something like an ATM? Yeah, good idea, but maybe with any other type of dedicated coins (uncraftable, that you can only get from creative) to put into the credit card, you know, because gold nuggets I think are very cheap.
For the second part: Perfect :D

**Comment by Dolu1990** [comment]
We have starting to work on.

**Comment by Dolu1990** [comment]
In r32, => Reduct resistance of High voltage cable and rise the maximal power of it
not released yet (5Kw, 200mOhm)
