### ISSUE TITLE
MineTweaker support

### ISSUE THREAD

**Issue by Shurik1236** [Electrical-Age/ElectricalAge#622]
Когда будет поддержка MineTweaker? Или если уже реализовано где посмотреть что вписывать в zs?

(Google)
When will support for MineTweaker? Or if you have already realized where to look what to write in zs?

**Comment by Baughn** [comment]
Um... as soon as I get around to fixing the pull request. Might be this week, I've found that I need it.

Call it next release. By the way, for questions like these, please ask using our support channels rather than opening a bug.
