### ISSUE TITLE
Devices lose energy

### ISSUE THREAD

**Issue by Shurik1236** [Electrical-Age/ElectricalAge#635]
Любые устройства работающие от батареек теряют энергию если их поместить в механизм правым кликом.
Google:
Any device running on batteries lose energy if placed in the right-click mechanism.

Тут понятнее (Надеюсь русский интерфейс не помешает):
Google:
There are clearer (I Hope Russian interface will not interfere):
https://youtu.be/wQtOYnd_zdw

**Comment by Baughn** [comment]
Interesting...

That's a valid bug, yup.

**Comment by AMIDIBOSS** [comment]
I guess rightclicking charger removes item form inventory and adds same item into charger. Can we temporarily store item data in some varrible? And then apply it to item in charger...
Might that fix it? @Baughn what do you think?

**Comment by cm0x4D** [comment]
It is fixed in #636. Thanks for the issue, @Shurik1236 . 
I am happy the bug did not make it into the release 😄 ...
