### ISSUE TITLE
Animations and sounds while paused

### ISSUE THREAD

**Issue by SaphireLattice** [Electrical-Age/ElectricalAge#64]
Animations and sounds doesn't stop when game is paused.

**Comment by Dolu1990** [comment]
Hi, 
Before 1.6.4 this "feacture" was ok. But when the mod was going to 1.6.4 the class attribut that could give me the information if the game is in pause or not   become a private member XDXD 
i must take a look if now it's become a public member. Or find a other trick
Thanks for issue.

**Comment by Dolu1990** [comment]
Hi, it's ok now. that comming in next release
