### ISSUE TITLE
[BUG] Utility pole with DC DC converter not rendering properly

### ISSUE THREAD

**Issue by AMIDIBOSS** [Electrical-Age/ElectricalAge#641]
Utility pole with DC DC converter not rendering properly on feature/t2poles
Take a look:
![2017-02-07_17 41 44](https://cloud.githubusercontent.com/assets/10089795/22701201/520fc758-ed5d-11e6-9727-96b823005165.png)
![2017-02-07_17 41 49](https://cloud.githubusercontent.com/assets/10089795/22701205/540f9592-ed5d-11e6-8e63-4abbfbdf2f6e.png)
Conected or not, will not work!
![2017-02-07_17 47 15](https://cloud.githubusercontent.com/assets/10089795/22701302/95df4d6e-ed5d-11e6-90dd-7e5ac54d275e.png)
![2017-02-07_17 47 34](https://cloud.githubusercontent.com/assets/10089795/22701312/9ee06c72-ed5d-11e6-91ad-fb2f76272ca2.png)
The one at the left is normal, the one at the right has (or hasn't) DCDC converter. It's hard to tell, the only things you see are wires

**Comment by Baughn** [comment]
I'm redoing a lot of the rendering code, so glitches like this can happen.

**Comment by pooing1234** [comment]
How did you get those large poles?

**Comment by AMIDIBOSS** [comment]
@pooing1234 As I said, they are in t2 poles branch: https://github.com/Electrical-Age/ElectricalAge/tree/feature/t2-poles?files=1
You need to build it youself. Or i can provide you with my jar if you need.

**Comment by Baughn** [comment]
I've noted this down in my PR checklist.

**Comment by AMIDIBOSS** [comment]
Good
