### ISSUE TITLE
[Suggestion] Farming lights improve crop growth rate

### ISSUE THREAD

**Issue by bjorguv** [Electrical-Age/ElectricalAge#647]
I think it'd be cool if farming lights could increase growth rate of crops. Maybe faster rates w/ higher voltages. and also if you were to do this take into account the crops that grow past 1 block in height. so maybe the light has a radius that it reaches so that it can be placed like 2 to 3 blocks above a plant that way the plant can reach maximum height. sugar cane for example.

**Comment by pooing1234** [comment]
YES!

**Comment by OmegaHaxors** [comment]
I think that would be pretty cool. Perhaps have the lamps give off "direct sunlight" so players don't just abuse the lamps for extra growth on top of their already optimal setup.

**Comment by AMIDIBOSS** [comment]
Anyway the lamps are called "farming lamp", they're high power industrial lamps. They're not ment for farming. But adding yet another lamp intended for farming would be cool. Maybe it'll work like worm from AA but have wider range. 😃

**Comment by cm0x4D** [comment]
I might not understand your request correctly, but there are already 50V and 200V "Farming Lamp" bulbs that can be installed in any lamp socket. They do actually increase the growth rate on a range of several blocks. Is it that what you are asking for?

![farming](https://cloud.githubusercontent.com/assets/6661117/22842655/496b9020-efd6-11e6-91ab-a1b9d3894cc9.png)

**Comment by bjorguv** [comment]
@cm0x4D That's exactly what I was requesting. I just couldn't find that in any documentation. thanks.

**Comment by cm0x4D** [comment]
Hapoy to help. Have fun.

**Comment by AMIDIBOSS** [comment]
Wiki should say "increases crop grow rate"
