### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by asianboi98** [Electrical-Age/ElectricalAge#65]
I know this mod is in BETA, but I need help on how the power system works, which way sends/receives power on the battery, how to charge the battery while using the battery (Charging the battery without having to relocate it to use it) the Tutorial didn't help. Also, when you destroy a battery, and replace it with another(different) battery and open its GUI, then in chat, a message appears saying...

"Damned! sorry, it's a debug message from Electrical afe
Could you send me a message about that ?
Thanks : D"

Before the charged battery was replaced...
![2014-07-28_13 24 01](https://cloud.githubusercontent.com/assets/8291686/3724239/15fcf002-167c-11e4-983b-d2fc904867d7.png)

After the charged battery was replaced...
![2014-07-28_13 24 09](https://cloud.githubusercontent.com/assets/8291686/3724241/21dab04e-167c-11e4-964e-7fb087759ba1.png)

**Comment by Dolu1990** [comment]
Hi,
For charging batteries, i see on your screen shot that it was in reversed side. You must put the red side in front of solar pannel.

You are the first to send me my secret debug message that i have left in the mod XDXD
Thanks for repporting. I have try to do your instruction to reproduct that, but nothing come :(
Thanks for issue :)

**Comment by asianboi98** [comment]
Okay tell me if I am wrong... The red on the battery means it accepts power... ad the black on it sends power... now my main issue is how do i do it to where i can have the battery being charged WHILE it is being used for, lets say power for the machines (its a hassle to always change the battery when it dies). Because if i try to do just that, the battery has a heart attack and explodes T-T
One last thing for sure, may i ask how the "Ground Cable" works? To me its like this, "The ground acts as a spot holder so that when the battery is charging from the Red side, it has to be occupied by the other side so a ground cable is set to hold that spot." and vice versa for sending power.
Sorry for wasting your time and thanks for the help above :)

**Comment by asianboi98** [comment]
Also regarding the debug, to reproduct it...
(Left to Right)
Ground Cable(Nothing inside it), Cost Oriented Battery(red or black side facing Solar Panels), Medium Voltage Cable, then Solar Panels x4(All with red side facing towards the battery), and last is another Ground cable(Nothing inside it)
In your Inventory should be a pick and another of the same battery, FIRST you break the charging/uncharging (depends which way you faced it :P) battery, SECOND you place the Battery (in your inventory) in the same place as the charging/unchargin Battery and LAST all you have to do is open the Battery's GUI(the one you just placed down) and wait a second or two and then exit the GUI; if you did it correctly the debug message appears. *Make sure you have in your multiplayer options chat is shown :P
Sorry again for bothering you!

**Comment by Dolu1990** [comment]
It's not a energy packet based mod. you can't say " input output" for batteries. It a real battery model. Look at tutorial, this room : https://raw.githubusercontent.com/Electrical-Age/electrical-age.github.io/master/screenshots/complexRegulationNetwork.png
there is a batteries example.

You realy don't must speak about input output. ground usage is put a ground referance to some pin (battery, solar pannel). to say, there is 0V, if you had a 50V batterie with negative side grounded => the positive side is at 50V. if you add a second battery in serial you had 100 V

Thanks a loot for complet debug instruction. i try that now :)

**Comment by Dolu1990** [comment]
hmm i don't have succesfuly reproduct it XD
Do your are in 1.7.2 or in 1.7.10 ?
Is the message appear in single player to ?
Do you have a modpack instalated ?

**Comment by asianboi98** [comment]
Sorry i forgot i had left that information out. It's Minecraft 1.7.10, Singleplayer, and yes it is in a modpack, but it probably doesnt have to do with other mods(I might be wrong) because i have removed many mods and the debug still appears, would you like the mod names i am currently using that still cause the debug to appear? Also dumb question, you mention you places the debug there, why did you?(You don't have to answer this if you don't want to)

**Comment by Dolu1990** [comment]
I have put this message because some people report a crash, and i suspect this part of code to provoc it :)

**Comment by tvk1372** [comment]
Hello!
I need some help Im making a gigantic powerstation for my city and i have some issues with the signal processor!
I use 1 stone heat furnace and 2x200v turbine for one line,and I use 23 lines/side and the is 2 sides (Right and left) So there is 46 lines complete.
And my biggest problem is when I use this voltage formula I find the formula on youtube:  (1 - ((A + C) / 2)) + 0.22 + B / 2 \* 2.2     with 2 turbines/ line the heat goes up very.I use 2 temp sensor and 1 electr. sensor for current detect  on the main 10A power cable.
Can you help me with the voltage formula?
Here are sme pictures of  my project:
This likes one line of the generation
![minta1](https://cloud.githubusercontent.com/assets/8401485/3865885/b8a4d962-1fb1-11e4-878a-7866749305fa.png) 
And 2 line coneccted together like this but shorter distance
![2014-08-09_12 40 25](https://cloud.githubusercontent.com/assets/8401485/3865889/12b9ff0e-1fb2-11e4-8be4-bda3886f69ac.png)
That sort of distance
![minta3](https://cloud.githubusercontent.com/assets/8401485/3865895/49bd67ca-1fb2-11e4-86da-ea6e4ede44da.png)
And it will look like this when I finish
![minta2](https://cloud.githubusercontent.com/assets/8401485/3865900/6e3fed3e-1fb2-11e4-81bd-ecc77cbb3071.png)
Im using the latest version (r34) so the heat sensors are calibrated to 350 celsius max and 150 min.

**Comment by tvk1372** [comment]
O and i forget something how do I control or shut down by a signal button or trimmer a signal processor,because a want to control my generators by sectors I mean there is 23 lines / side and i want to turn of some of those from the control room when the consumption is low

**Comment by Dolu1990** [comment]
Hi,
(1 - ((A + C) / 2)) + 0.22 + B / 2 \* 2.2 is a very strang formula, i suggest you to take a look into ElectricalAge_tutorialmap. there is some turbine setup :)

It's betther to put turbine in paralell than serial

On very good setup is to use the signal processor with  a external power regulation combinated with a internal rs function like in this room : https://raw.githubusercontent.com/Electrical-Age/electrical-age.github.io/master/screenshots/complexRegulationNetwork.png (from tutorial map)

**Comment by Dolu1990** [comment]
Did you have try electricalage tutorial map before ?

**Comment by tvk1372** [comment]
No I didn't,but Im gonna try
Thanks!
