### ISSUE TITLE
(suggestion) Dc to DC converter box.

### ISSUE THREAD

**Issue by pooing1234** [Electrical-Age/ElectricalAge#650]
I really think it would be beneficial to have a DC to DC converter that looks like [this](http://strongerchristchurch.govt.nz/sites/strongerchristchurch.govt.nz/files/u28/grafton-street-photo-1.jpg)

I don't want to keep having to cover up DC to DC converters in the street. It looks messy, and ugly imo.

**Comment by AMIDIBOSS** [comment]
DC converter is ugly? *I think you're expressing your personal opinion a little too directly* 
but still, boxed version would be nice!
Just duplicate existing code of converter changing the model. And when you're done make a pull request so that everyone can have it! :stuck_out_tongue_winking_eye:

**Comment by pooing1234** [comment]
@AMIDIBOSS I may have came a little too harsh, and I'm sorry about that. I mean It didn't look nice in the street that I'm building. Also, I'm no good with modding, but it's always a good opportunity to learn something new. :)

**Comment by AMIDIBOSS** [comment]
I just joked about doing it youself. But if you do that it would be awesome! I 'll try doing that later. 
At least I' ll create a model. For now put your converters underground.

**Comment by cm0x4D** [comment]
Well it hurts a little. The model should represent the electronics and main inductor of a DC-DC converter. The big inductor shows how many cables are on each side and enables the player to determine the ratio very quickly.

I can understand that it looks a little awkward on a street. But I actually prefer to have the blocks appearance to be reasonable about it's function and not just the aesthetics in it's environment. But again this is my subjective opinion.

Creating a new DC-DC converter block is imho not the best solution. I would propose something different: We create an "enclosure" item. This item can be placed in the DC-DC converter's GUI and if it is present, an enclosure (something like in the link) is rendered in the place of the actual model. This "enclosure" item could then be used to be put over other ELN elements to hide them.

What do you think about that solution?

**Comment by AMIDIBOSS** [comment]
Nice solution. 
Today i'll make some box models

**Comment by OmegaHaxors** [comment]
Just give it the cable facades that the other 6-node blocks get, then you can place any block you want over top of it.

**Comment by AMIDIBOSS** [comment]
@OmegaHaxors unfortunately, you can't put facades on transparentNode blocks. (to be clear, converter is one). But maybe we could add camouflage feature to the box? BTW. box model is done already!
https://github.com/Electrical-Age/ElectricalAge/pull/654

**Comment by cm0x4D** [comment]
The casing actually works on PR #690. If someone wants to test it, you're welcome...

@AMIDIBOSS: I had to modify the model a little bit in order to integrate it, check if you're ok with the changes. Basically I removed the components of the original DC/DC and copied all textures into one texture file.

**Comment by cm0x4D** [comment]
Done and merged into develop
