### ISSUE TITLE
(Item request) Emergency Lighting 

### ISSUE THREAD

**Issue by pooing1234** [Electrical-Age/ElectricalAge#661]
Lamps that have an internal battery that charges while mains is on. Lamps will turn on during a power outage.

They should have their own lamp supply that will trigger them to turn on if the lamp supply does not detect a voltage.

**Comment by AMIDIBOSS** [comment]
You can do that with existing devices

**Comment by pooing1234** [comment]
@AMIDIBOSS I know, but something that takes less space, and slightly simpler to make.

**Comment by cm0x4D** [comment]
There are already 3D models present for such devices (Emergency exit lights). It just needs to be integrated, which I might start once I find time...

**Comment by cm0x4D** [comment]
Done in PR #692 and merged, will be part of next release.
