### ISSUE TITLE
just click to place a solar tracker

### ISSUE THREAD

**Issue by HoodedCr0w** [Electrical-Age/ElectricalAge#662]
its annoying when you got a lot of solar panels but you have to open a gui just to place the solar trackers in. please change it so you just need to click the solar panel with the tracker.

**Comment by pooing1234** [comment]
Yes, I agree. I had a HUGE solar setup on our grid, and it's such a time consuming task.

**Comment by HoodedCr0w** [comment]
how huge?

**Comment by pooing1234** [comment]
@PeridotGem Huge, don't know the exact number of panels, but probably well over a 100.  You could imagine how long that would've taken to set up.  Helps power my sisters city, and my large underground base. Our battery bank is huge, and my sister has built a gas turbine plant to support the grid during the night. I may post some screen shots soon.

**Comment by Baughn** [comment]
You'll approve of the 2x3 panels that'll be in the next release, then. :P

**Comment by cm0x4D** [comment]
Was implemented in 834c4dfbd68f175891644312e521d504dd511132 and will be part of the next release, so we can close this issue I guess.
