### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by ArcasCZ** [Electrical-Age/ElectricalAge#663]
Using latest build of EA.

![image](https://cloud.githubusercontent.com/assets/6602975/23094604/7393b4aa-f5fc-11e6-9d54-1334e0b92f24.png)

**Comment by AMIDIBOSS** [comment]
OK, that does not look good, eh... can you give us full log?
So the voltage watchdog tries to destroy a block...
and then it propably fails...
And then tries again...
Maybe the block isn't chunkloaded? Try teleporting to that location.

**Comment by ArcasCZ** [comment]
Full log is so long. 

Actually, it stops after few secs, but... This has to stop :D

**Comment by Baughn** [comment]
What *is* at that location?

This may be something we fixed with https://github.com/Electrical-Age/ElectricalAge/pull/644, though.

**Comment by ArcasCZ** [comment]
I don't know, I'll check next time.

**Comment by cm0x4D** [comment]
> Using latest build of EA.

Latest build is somehow ambiguous. Latest release build or latest dev snapshot? And maybe in two weeks *latest* is something else.

In general prefer using version numbers for releases and build numbers (or commit hashes) for dev snapshots when referring to a build of the mod.

**Comment by ArcasCZ** [comment]
Last successfull from 16. 2. 2017 - it's your fault your builds doesn't contain build number in jar name.

**Comment by cm0x4D** [comment]
70017924815c6b98938256ad4793d2f241aebe73 fixes this
