### ISSUE TITLE
Problem with Tutorial sign

### ISSUE THREAD

**Issue by shadowpotion** [Electrical-Age/ElectricalAge#665]
I have a little problem while trying to make text in tutorial signs in russian. When i change latin symbols to cyrillic i got this:
![xdyc1lk](https://cloud.githubusercontent.com/assets/25900631/23123883/4e4a5b74-f77b-11e6-85a4-60d914907f6c.png)
Is there any way to fix this?

**Comment by Baughn** [comment]
Probably.

To start with, make sure you're using UTF-8, and I'll take a poke at the code tonight to see how it works.

**Comment by shadowpotion** [comment]
> make sure you're using UTF-8

> 

 Decode tutorialSign.txt to UTF 8 and now symbols are ok, thank you for response.
