### ISSUE TITLE
Big Bug That Causes Crash in 1.14.2

### ISSUE THREAD

**Issue by HoodedCr0w** [Electrical-Age/ElectricalAge#670]
you can crash the game by placing the 2x3 solar panels and reloading them. and they can clone into small solar panels when you break them.
I have been using other mods on my minecraft but the solar panels seem to be the only thing crashing my game.

no other bugs that i have found yet. so, keep up Good Work!

i have the crash log. 
[crash-2017-02-22_15.15.56-server.txt](https://github.com/Electrical-Age/ElectricalAge/files/793708/crash-2017-02-22_15.15.56-server.txt)

**Comment by cm0x4D** [comment]
You mean version 1.14.1?
