### ISSUE TITLE
Right clicking a chargeable item onto a charger zeroes the item's charge.

### ISSUE THREAD

**Issue by Kreidos** [Electrical-Age/ElectricalAge#682]
Placing an item into the charger's GUI maintains the current charge level, but right clicking an item (e.g. Electric Axe) directly onto the charger block zeroes its charge before starting to charge.

**Comment by AMIDIBOSS** [comment]
What versions do you use?

**Comment by Kreidos** [comment]
Sorry, I thought it was assumed I was running the latest stable. 1.14.2

**Comment by AMIDIBOSS** [comment]
It was fixed, you can close it
