### ISSUE TITLE
Crash caused by Conflict with YukariLib

### ISSUE THREAD

**Issue by C6H2Cl2** [Electrical-Age/ElectricalAge#683]
Yukari Lib is a mod  to help KotlinModding.
ELN use kotlin-1.0.5-2 , YukariLib use kotlin-1.1.0-rc-91
This difference make a crash 
Crash Report is [here](https://www.dropbox.com/s/5i35h1c21kjxvrw/KotlinCrush.txt?dl=0)
Would you mind changing kotlin version?

**Comment by Baughn** [comment]
I'll look into it.

At a minimum, yes, we'll change the version. The way Kotlin works necessitates a single dependency mod that contains the runtime, however, which hasn't existed for 1.7. Perhaps this one could do the job.

**Comment by Baughn** [comment]
A quick look at YukariLib does not inspire confidence. There are typos in the description; I don't want to know what the code looks like.

Additionally, Kotlin 1.1 is not out yet. I'm not going to upgrade to a release candidate build; you should get YukariLib to downgrade. I'll update to 1.0.6 at most.
