### ISSUE TITLE
(request) Power regulation

### ISSUE THREAD

**Issue by pooing1234** [Electrical-Age/ElectricalAge#687]
It would be nice to have some proper voltage regulation. Especially if there is more than one power station on grid.

**Comment by cm0x4D** [comment]
Would that not destroy the actual challenge and even the purpose of the accurate simulation?

I am planning to add linear voltage regulators for 50V and 200V, for everything else you need to assure that the produced power equals to the consumed power. All building blocks to achieve this should be available.

**Comment by Baughn** [comment]
Could you be more specific?

I'm not sure what problem you're facing.

**Comment by pooing1234** [comment]
@Baughn I'm having trouble keeping power stations in sync. I need them to out put the exact same voltage. I have a gas powered plant, outputting 3.6kv and a solar farm outputting 3.7kv. 
But I need the solar farm to have same voltage as the gas plant. But I'm not sure how. I could have the gas power plant with 3.7kv, but I don't want to risk having the generators to over spin.

**Comment by cm0x4D** [comment]
All building blocks for such a regulation are available. We can and will not do that for the player, it is the duty (and somehow the challenge when using this mod) of the player to regulate his installations. You can do pretty much everything using the probes, the signal-processor and the digital/analog chips.
