### ISSUE TITLE
crashed because of rendering

### ISSUE THREAD

**Issue by lightning02** [Electrical-Age/ElectricalAge#697]
http://pastebin.com/4SEhy68P
This happened looking into the white brush recipe pressing "R" keyboard button after I've modified it with mnetweaker

**Comment by lightning02** [comment]
it was a sort of my fault btw because I was just missing "withTag({life: 32})"

**Comment by cm0x4D** [comment]
We fixed the potential NPE anyway in PR #698. Thanks for the issue.

**Comment by lightning02** [comment]
Thanks to you! :)
