### ISSUE TITLE
Some blocks don't have a texture/don't render correctly

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#7]
Namely:
Computer craft probe
Auto miner
Basic ore scanner
Advanced ore scanner
10A diode
25A diode
Signal diode

**Comment by Dolu1990** [comment]
All have no texture. model to do

**Comment by DrummingFish** [comment]
Okay well this issue will keep you reminded of them :)

**Comment by Dolu1990** [comment]
yep ^^
