### ISSUE TITLE
Link to jenkins for newist builds?

### ISSUE THREAD

**Issue by MFernflower** [Electrical-Age/ElectricalAge#70]

**Comment by Dolu1990** [comment]
Hi, 
I have now know how about jekins and very fiew about gradle build script. 
What are advantage of jenkins ?

**Comment by cm0x4D** [comment]
We do not have a build server and we are that few people on the project that we can not manage continuous builds. I guess Dolu makes updates quite often and if you like to use the newest stuff from the repository, you can install Minecraft forge and clone the repository...

**Comment by metc** [comment]
@MFernflower Here is a Jenkins CI server:
http://ci.safranil.fr:8080/job/ElectricalAge/lastSuccessfulBuild/

**Comment by Safranil** [comment]
Hi,

You can also access to Jenkins without the port : http://ci.safranil.fr/job/ElectricalAge/lastSuccessfulBuild/

**Comment by metc** [comment]
All the credits to @Safranil, thanks !
