### ISSUE TITLE
[Feature Request] An easy mode option in the config

### ISSUE THREAD

**Issue by bjorguv** [Electrical-Age/ElectricalAge#708]
Make someway for people to make use of the awesome features like the lights, switches, etc... without having to complicate it with the electronic aspects.

**Comment by AMIDIBOSS** [comment]
Eww, so...
Electrical age is a **realistic** simulation mod. It's all about *complicated electronic aspects*.
So disabling that is... like...
It's really not that hard. A little bit of electronic knowlege is required, that's true.
You see, ELN is not about cool looks and "realistic-like" components.
they also have realistic behavior!

**Comment by pooing1234** [comment]
@bjorguv WTF?

**Comment by Baughn** [comment]
Turn off explosions, turn on WAILA easy mode.

That's as much easy-mode as the mod can have. Anything more would be missing the point; for pure payoff, there's nothing in Eln you couldn't also get with, say, Immersive Engineering.
