### ISSUE TITLE
help me with receiver transmitter antenna 

### ISSUE THREAD

**Issue by bomdia** [Electrical-Age/ElectricalAge#71]
i need to know how to use it haven't any gui there isn't any to-do to make it work?
how i do it transmit?

**Comment by asianboi98** [comment]
Something like this I think... Only problem I am having is that how do I get current???
P= Power(Give it energy to be used)   C= Current(?)   S= Signal(Wireless redstone)
Dolu1990 could you show us how the Transmitters/Recievers work?
I've seen a tutorial on Youtube except the guy who did the spotlight wasn't sure of how it worked...

![2014-08-01_14 09 40](https://cloud.githubusercontent.com/assets/8291686/3782928/2e15d0e0-19a7-11e4-83fa-18cd4f9905d0.png)

![2014-08-01_14 09 45](https://cloud.githubusercontent.com/assets/8291686/3782929/2e1ae9fe-19a7-11e4-945f-615307ef4bde.png)

![2014-08-01_14 09 51](https://cloud.githubusercontent.com/assets/8291686/3782930/2e1f177c-19a7-11e4-8080-072e7c40da4b.png)

![2014-08-01_14 09 57](https://cloud.githubusercontent.com/assets/8291686/3782932/2e2d7c2c-19a7-11e4-96cb-963fc724a611.png)

![2014-08-01_14 10 01](https://cloud.githubusercontent.com/assets/8291686/3782933/2e336178-19a7-11e4-8f3b-d97abf11f45c.png)

![2014-08-01_14 10 10](https://cloud.githubusercontent.com/assets/8291686/3782934/2e375cc4-19a7-11e4-8490-5a70c695cda5.png)

**Comment by bomdia** [comment]
i have tried your config but doesn't work for me

**Comment by asianboi98** [comment]
I told ya XD All that is missing in the picture is a Current source.... i think the Current Oriented Battery should work, if not then I'll keep working til i manage to make it work ;D

**Comment by Dolu1990** [comment]
Hmm i must add that into tutorial map :) i close this issue when it's released.
It's a little bit complicated to explaine how to do, because some regulation are possibles.

**Comment by Dolu1990** [comment]
Hi, it's now juste after the outside part into electricalAgeTutorialMap. r29.
