### ISSUE TITLE
Add a better explanation for power socets

### ISSUE THREAD

**Issue by anar4732** [Electrical-Age/ElectricalAge#716]
I do not understand how use.

**Comment by cm0x4D** [comment]
The explanation is quite simple: They do not work as they are WIP of a developer that did not contribute since years. They basically are in the mod by accident.

**Comment by Baughn** [comment]
We should add a "decorative only" tag to the tooltip, but oh well.

**Comment by AMIDIBOSS** [comment]
@Baughn Maybe we'll go *the hard way* and try to make them work?

**Comment by Baughn** [comment]
@AMIDIBOSS Even if we do, they don't work *right now*.
