### ISSUE TITLE
Forge ServerState Error on Worldjoin

### ISSUE THREAD

**Issue by LukaPix** [Electrical-Age/ElectricalAge#721]
This happens to me trying to enter a world. Tested on different world Types and new and already existing Worlds. Java version 1.8.21. Newest Forge and ElectricalAge Versions.
There is also some AE2 error going on, but i dont really know whats happening so im first posting it here.

https://hastebin.com/efisadaxey.sql

**Comment by AMIDIBOSS** [comment]
Give as the actual forge and eln versions, as "Newest" change the never version comes out.
Line 39: [14:25:20] [Server thread/ERROR] [FML]: Caught exception from appliedenergistics2
I suppouse you have AE2 installed right? Can you try to disable it and create a new world without it?
Can you post the whole console log? And list of mods maybe?

**Comment by cm0x4D** [comment]
It seems to me that either the method `onServerStopped()` has been called, but the method `onServerStart()` has not been called or the method `onServerStopped()` has been called twice.

These are the only possible cases where the `modbusServer` field could be null.

So basically it seems the NPE in EA is a symptom of something other failing...

**Comment by AMIDIBOSS** [comment]
Yep. But we don't have the full log.

**Comment by Baughn** [comment]
I can see that happening if some other mod crashes during startup. Assumptions were made. This'd be low priority, because if it happens then no-one is playing Minecraft today anyway, but it's still a bug.
