### ISSUE TITLE
buildcraft integration

### ISSUE THREAD

**Issue by bomdia** [Electrical-Age/ElectricalAge#73]
that can be very good if you create a convertion block for energy and other stuff

**Comment by Dolu1990** [comment]
Hi, yes, it's in the pipline, recently IC2 + OpenComputer support was added ^^
Maybey i don only converssion from electrical age to other ?

**Comment by bomdia** [comment]
The transportation pipe of buildcraft is very useful ex furnace for thermal production use carburant from buildcraft and transport it with a liquid pipe from extraction site.

**Comment by Dolu1990** [comment]
yes i must suport it :)

**Comment by Dolu1990** [comment]
I have take a look to the buildcraft API, and it's real ... strang.
One possibility is to suport RF, and then RF to buildcraft ?

**Comment by bomdia** [comment]
mmm talk with mod creator of buildcraft ! they know how to use it :D 

im don't know java sorry i know only php js css py c++ vb 6.0

**Comment by Dolu1990** [comment]
It's now ok in rxx i don't remember XD
