### ISSUE TITLE
Missing Block Texture

### ISSUE THREAD

**Issue by asianboi98** [Electrical-Age/ElectricalAge#74]
The 10A Diode, 25A Diode, Signal Diode. and the Signal 20H Inductor doesn't have any texture when placed down(The Signal 20H Inductor also doesn't have a Icon)

![2014-08-01_13 58 28](https://cloud.githubusercontent.com/assets/8291686/3782882/c2bfc5ee-19a6-11e4-82b3-7d107b5adb20.png)

![2014-08-01_13 58 30](https://cloud.githubusercontent.com/assets/8291686/3782883/c424de42-19a6-11e4-8325-3572803a6554.png)

![2014-08-01_13 58 31](https://cloud.githubusercontent.com/assets/8291686/3782884/c434e67a-19a6-11e4-9c5b-4f3bb23daeab.png)

![2014-08-01_14 18 40](https://cloud.githubusercontent.com/assets/8291686/3783013/50ea82c2-19a8-11e4-84b9-0bd117552056.png)

**Comment by Dolu1990** [comment]
Hi, 
Thanks for issue, For the moment i'm asking myself if i must keep diodes into the mod. i think i remove it. not sur for the moment XD.
Or maybe i must change the electrical simulation model for diodes (i don't like it)

**Comment by asianboi98** [comment]
If you do plan to remove these, are you planning to create another one to where it controls which way the power flows?

**Comment by Dolu1990** [comment]
I don't like the actual simulation model of diode that don't exactly do what we can wait of a diode. Diode could introduct instability. i must take more time one.

**Comment by cm0x4D** [comment]
Done (in repo)
