### ISSUE TITLE
Cable is heating up without reason!

### ISSUE THREAD

**Issue by dennis-qt** [Electrical-Age/ElectricalAge#744]
After one of my cables melted, I simply placed a new one, but this melted too, but I had cut off all power before and there is no current and voltage on the cable(tested with the allmeter). I play with ELN 1.14.2

**Comment by dennis-qt** [comment]
![2017-07-03_18 03 49](https://user-images.githubusercontent.com/28846491/27800525-11052fa2-601a-11e7-8a48-e6df563716fe.png)

this is my Test-system(melting cable is between Generator and Relay). It's designed to start and stop an engine. While and after stopping the cable always heats up and melts(no, it's not an short-circuit!)...

**Comment by angelwork727** [comment]
When the Generator starts up, it first pulls a huge amount of current, try putting a resistor in series( you have to try which resistance works best for your setup) and bypass it after some time, then, when the generator is up to speed(when you hear the turbine sound), cut off the power line that you used to start the generator and connect the load.
Also make sure that, while starting the Generator, the stop relay(the one with the ground cable on it) is definitely off, else it will  cause a short circuit.

Some questions : 1. What is the Voltage you entered in the power source?
                             2.Can you measure the current directly after connecting the cable?
                             
One tip : Try replacing the wire with the "hub" thing, setting it so that it connects the cable right through, it won't melt.

**Comment by dennis-qt** [comment]
What I've done is:

1.  placing the cable(VHV, 3.2kV)
2. starting the engine with the lower swich
3. cut OFF all the power with the relay(by pressing the swich again)
4. after the engine runs, pressing the upper swich to short circuit the generator and shut down the engine
    note: the power source is cut OFF because of the relay

after that the cable melts(I replaced it with an probe to meter the current: 0A!)

**Comment by dennis-qt** [comment]
the hub doesn't melt.
I don't know why this happens with an normal cable...

**Comment by AMIDIBOSS** [comment]
I know that current is 0A, but what's the voltage?
--EDIT--
And where's the feedback circuit?

**Comment by dennis-qt** [comment]
which feedback circuit do you mean? This is a system for testing... It's to test an system which starts and stops an engine to generate power(later the electrical source will be reblaced with my power grid) the voltage is of course 3.2kV from the generator(if it's short-circuited, the voltage will go down of course). But why does this matter? the cable melts only AFTER I short-circuited!(no, I've not forgotten to swich off the electrical source)

**Comment by OmegaHaxors** [comment]
I know the answer to this one. Generators have their own heat system which does nothing to themselves but transfers into nearby wires, often melting them. That's why only the wire coming out of the generator is melting for no reason. Either break/replace the generator to reset its heat or wait for the generator to cool down.

**Comment by AMIDIBOSS** [comment]
That might be the thing... Short circuiting generator might cause it to heat up and melt cables nearby...
Can you measure generator's temp?

**Comment by dennis-qt** [comment]
Yes, this is the reason. The generator heats up very much. Thank you!

question: is there a way to cool the generator down?

**Comment by AMIDIBOSS** [comment]
use heat spreaders!

**Comment by dennis-qt** [comment]
![2017-07-05_22 19 26](https://user-images.githubusercontent.com/28846491/27883295-5e851168-61d0-11e7-96f3-a0199f9c19cc.png)
the generator doesn't connect to these or to thermal cables :/

**Comment by bloxgate** [comment]
I don't think the generator should heat up if you're running it at the correct speed. At least not enough to actually melt things. What speed are you running it at?

**Comment by dennis-qt** [comment]
@bloxgate the generator heats up based on the load given to it

**Comment by Baughn** [comment]
I just never implemented failure modes for the generator, but heat transferring to the cable is WAI. You have to overload it pretty badly for that to matter; normally the generator acts as a heat *sink* for the neighbouring cables.

I'd be interested in any bugs you find, but this is more likely a design flaw. Humans can't react fast enough; you really should automate generator/turbine control right out of the gate.

Here's a design which definitely works: https://wiki.electrical-age.net/index.php?title=Simple_gas_turbine_control

**Comment by dennis-qt** [comment]
@Baughn I overload the generator to stop the connected engine. Now I prevent my cables from melting with a hub (like ihaveaquestion02 said)

And this is only a small system for testing. The real power plant is fully automated(auto cut-off, speed regulation,...) and monitored(speed, voltage, current on each single generator,...).

**Comment by dennis-qt** [comment]
thanks @all, you helped me to build this huge power plant!

![2017-07-06_18 54 30](https://user-images.githubusercontent.com/28846491/27923276-1ef40366-627e-11e7-93a4-1a7922e228ed.png)
![2017-07-06_18 54 42](https://user-images.githubusercontent.com/28846491/27923275-1ef25bec-627e-11e7-8553-b9fec624ec07.png)

**Comment by AMIDIBOSS** [comment]
No problem! we're here to help!
(As we don't have anything better to do...)

**Comment by dennis-qt** [comment]
> (As we don't have anything better to do...)

^^

**Comment by dennis-qt** [comment]
made a little test with this power plant: teleporter at 18kW(because the 3 HV-cables which are powering the transporter can't handle more load) is no problem for the plant!

**Comment by AMIDIBOSS** [comment]
yes... But you need two teleporters...

**Comment by dennis-qt** [comment]
of course, but while teleporting only one of these teleporters causes this load.
