### ISSUE TITLE
not working on server 1.7.10

### ISSUE THREAD

**Issue by ravenshayld** [Electrical-Age/ElectricalAge#748]
i'm a French player
i tried use ELN 1.14.2 in my server but the servers crash
BUT the modpack work easy in singleplayer

version of Kcauldron:1517.168

i go to tried to put Thermos in the place of KCauldron

Can i have help ?
ps : sorry for my English

**Comment by AMIDIBOSS** [comment]
Your English is no problem if you can understand us...
What is the modpack you use?
What Java version does the server host have? (ELN requires Java 8)

**Comment by cm0x4D** [comment]
Could you provide the crash log? 
Otherwise we can not much more than speculate about the problem.
