### ISSUE TITLE
[FR] True DC-DC Converters

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#749]
With the existing system it is easy to step between x2, x3, x4. However, by mixing 3:1 and 1:4 you can get various different conversions which allow for a little more control when it's needed. However, there's one minor problem with this system: Generator Balancing. Because generators require more voltage going in to get up to speed Vs what they output, the voltage needs to be increased by a factor of 1.25x which unfortunately under the current system is an absolute joke.

In order to interface between two networks of shafts, 8 stepdown 1/3 converters, 6 1/4 converters and 1 2x converter are required. That's 15 converters total! You also lose half the energy going in due to all the conversions making it even less of a viable strategy.

An easy way to fix this, and also to make DC-DC converters act less like the transformers they were modeled on, is to replace the winding system with one more fitting to real converters: setting the transformation by adjusting internal resistance values by adding coal dust, and fine-tuning with a signal.

The three downsides of this system would be that power is directional due to the internal diode and losses are heat-based so attaching a cooling fin may be necessary with larger loads. External capacitance is strongly suggested with higher transformations as you'll get a bit of a voltage swing otherwise.

Since its functionality isn't exactly the same, keep the old converter, give its old name back, buff it to allow up to 1:16 and headcanon that it's run by an internal alternator and fullbridge rectifier and god damn it force it into isolated mode there's no reason for non-isolated to exist, especially by default.

**Comment by AMIDIBOSS** [comment]
Whell, the non isolated mode is for optimalozations...

**Comment by cm0x4D** [comment]
We already considered to make the DC/DC converters more useful by letting the user place up to 8 or 16 wires on each side. I guess that should do the trick for most (static) scenarios.

**Comment by Baughn** [comment]
I'm also going to change the generator behaviour somewhat, making them reasonable motors, which will provide truly arbitrary (if slightly inefficient) voltage conversions.

**Comment by jrddunbr** [comment]
We have 16 cable DC/DC converters, is that sufficient?

**Comment by OmegaHaxors** [comment]
It's proven to be a nice addition at the very least. Thanks for adding that.
