### ISSUE TITLE
Not detecting Beta 1.8 R28 (Bug?)

### ISSUE THREAD

**Issue by asianboi98** [Electrical-Age/ElectricalAge#75]
My Minecraft cannot detect Electrical Age Beta 1.8 R28, to be sure I deleted it and placed Beta 1.7 R26 then loaded Minecraft, it detected Beta 1.7, so I removed it and placed Beta 1.8 in my mods folder and it still cannot detect it.

**Comment by Dolu1990** [comment]
Hi,
I juste have tested, on my setup it's ok. but i suspect it's because i have add a system.exit and forge now refuse mods with that :) 
What is your forge verssion ?
i fix that in r29, coming soon

**Comment by asianboi98** [comment]
Forge version is 10.13.0.1182

**Comment by Dolu1990** [comment]
oky, so with 1192 it's oky, i think it's juste a forge bug :)
I recommand to use 1180, 1192 is buged.
