### ISSUE TITLE
[Minor] Battery Voltage floors at 0V

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#753]
When a battery has energy forcibly drawn from it (say by an inductor) it will go into the negative charge. However, the voltage stays at 0V preventing it from correcting itself back to normal charge amounts.

**Comment by AMIDIBOSS** [comment]
...
i really don't know what to say now...

**Comment by cm0x4D** [comment]
We should probably not allow the charge to be negative.
