### ISSUE TITLE
OP Bug! (Beta 1.7)(Check Beta 1.8 incase!)

### ISSUE THREAD

**Issue by asianboi98** [Electrical-Age/ElectricalAge#76]
Just like stated above, the op bug is that almost all the items in the mod can be used as a pickaxe that takes no damage XD (Batteries, Lightbulbs, Brushes, Flashlight, Electrical Axe, The upgrades, nearly the whole mod is a pickaxe XD)

**Comment by Dolu1990** [comment]
XDXD i fix that now

**Comment by Dolu1990** [comment]
It's ok, Comming in r30
thanks for issue
