### ISSUE TITLE
Game crashes when clicking with item on Fire Sensor (Not Battery Powered)

### ISSUE THREAD

**Issue by iancbogue** [Electrical-Age/ElectricalAge#764]
I accidentally right-clicked on the Electrical Fire Sensor (or whatever it's called, my game isn't open RN) and the game immediately crashes. The same thing happened when I tried to break it with an item in my hand. I don't know if it happens w/o and item in hand.
[crash-2017-09-16_17.27.11-server.txt](https://github.com/Electrical-Age/ElectricalAge/files/1308752/crash-2017-09-16_17.27.11-server.txt)

**Comment by OmegaHaxors** [comment]
~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.

**Comment by OmegaHaxors** [comment]
`~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.`

This is the bit of the code that reveals the core issue.

**Comment by iancbogue** [comment]
Which means...

OH! Is it because I'm using a Win10 Beta? Although I've gotten this error even before I downloaded the beta.

**Comment by bloxgate** [comment]
This looks like a duplicate of #694

**Comment by iancbogue** [comment]
Yes but will it be fixed in next 1.7.10 update? Just concerned, that's all.

**Comment by cm0x4D** [comment]
Duplicate of #694. Fixed in develop branch.
