### ISSUE TITLE
Right-clicking a portable power device (not a battery) into a charger resets the stored energy.

### ISSUE THREAD

**Issue by DonBruce64** [Electrical-Age/ElectricalAge#767]
Had a flashlight with 1/2 power in my hand that I right-clicked to put into a charger.  Upon doing so the internal stored energy of the flashlight was reset to 0J.  This resetting does not happen when using the GUI for the charger, nor does it happen with batteries.  It does happen with the Ore Scanner, except that item gets its internal energy storage reset to the level shown in the creative tab menu.  I'm sure there's a bad data transfer here somewhere.

**Comment by OmegaHaxors** [comment]
Confirmed this is an issue.
