### ISSUE TITLE
BETA-1.8_r28: In-Game Wiki has Invalid Information

### ISSUE THREAD

**Issue by BlayZett** [Electrical-Age/ElectricalAge#77]
The In-Game Wiki (X) shows that only one ingot is required for the plate machine to make a plate. It currently takes four.

**Comment by Dolu1990** [comment]
Hi,
It's now fixed, come in r30

**Comment by BlayZett** [comment]
Thanks! If I knew anything about mod programming (or programming in general) I would love to help. Maybe I'll learn some.
