### ISSUE TITLE
Odd character at the end of resistance value for lamps.

### ISSUE THREAD

**Issue by DonBruce64** [Electrical-Age/ElectricalAge#770]
Not sure why these are tacked on to the end of the lamp resistances.  Also suggest truncating the lamp resistance values.  Having gobs of 3333333 doesn't really help....
![2017-09-30_23 06 32](https://user-images.githubusercontent.com/15241611/31051682-a2c3463a-a634-11e7-8114-f6481a4e8309.png)

**Comment by AMIDIBOSS** [comment]
having the same for a year...

**Comment by cm0x4D** [comment]
There should be an Ohm sign (Ω), apparently the font used in the texture pack does not support that unicode character. The 33333333 are annoying, I will try to fix that...

**Comment by DonBruce64** [comment]
Noted.  Will ignore it.  I only submitted this bug as I had a similar one for the lamp GUI and thought it was another case.

**Comment by bloxgate** [comment]
Hmm, actually I wonder. I think someone had typed an actual omega in somewhere instead of the unicode escape. Maybe that could be causing this problem?

**Comment by AMIDIBOSS** [comment]
@bloxgate Maybe we just have to look for it?
