### ISSUE TITLE
BETA-1.8_r29

### ISSUE THREAD

**Issue by BlayZett** [Electrical-Age/ElectricalAge#79]
Electricity passing through breaker?
![2014-08-03_06 40 48](https://cloud.githubusercontent.com/assets/8340715/3790343/1256580c-1afb-11e4-9833-7a79ccc5f56a.png)
Breaker is OFF. Medium voltage cable inside. NOTE: I just noticed that it shows me aiming at the breaker. You can still see the bug in the second screenshot.
![2014-08-03_06 42 42](https://cloud.githubusercontent.com/assets/8340715/3790344/157fcff4-1afb-11e4-8a46-7c9bb3fed878.png)
Different world.

**Comment by Dolu1990** [comment]
Hi,
It's not a bug, it's because for the moment, switch are done with resistance value. If you put a load to this side, the voltage drop directly to zero, because of high resistance value..
I can fix that by puting some pull down resistor to each side.

**Comment by Dolu1990** [comment]
I have add that. now, the unconnected side (like in you picture) has the voltage of the other pin divided by 1000 but with very high impedance.    I can't do a betther solution that don't show some mV, because of numeric calculation error. (matrix inverse)
Come in r30

**Comment by Dolu1990** [comment]
Hi,
Now it's totaly fixed. By puting pull down in java code to each side of switch  pins, that help the simulator to solve matrix inverse, and now i can put realy high high high impedance on switch resistance (1 peta ohm XD)

**Comment by Dolu1990** [comment]
in r34
