### ISSUE TITLE
Strange Problem

### ISSUE THREAD

**Issue by owenhickey13** [Electrical-Age/ElectricalAge#794]
.jar file is in "mods" folder. everything is as it should be. BUT FORGE WON'T LOAD THE MOD INTO THE GAME!!!!

**Comment by owenhickey13** [comment]
**even not in mods list**

**Comment by AMIDIBOSS** [comment]
Hmm, strange,

**Comment by cm0x4D** [comment]
@owenhickey13 Did you download the jar from the official site?

**Comment by owenhickey13** [comment]
latest ver of forge, latest ver of minecraft java edition, .jar file in mods folder but not loaded and not in mods list

**Comment by owenhickey13** [comment]
downloaded from electrical-age.net

**Comment by cm0x4D** [comment]
> latest ver of minecraft java edition

Latest Version? Electrical Age is for Minecraft 1.7.2 and 1.7.10

**Comment by AMIDIBOSS** [comment]
Download it from github

**Comment by Baughn** [comment]
*Don't* do that. The github release page is deprecated.

The most up-to-date version will always be on Curseforge.

**Comment by AMIDIBOSS** [comment]
Oh sorry

**Comment by owenhickey13** [comment]
I MEAN I HAVE THE LATEST OF EVERYTHING!!! I DON'T NEED NEW VERSIONS!!!

**Comment by AMIDIBOSS** [comment]
You know it's not about the version. Some files on unknown sites may be corrupted.
https://minecraft.curseforge.com/projects/electrical-age/files/2385734

**Comment by owenhickey13** [comment]
the website you mentioned is the website I used

**Comment by owenhickey13** [comment]
[https://owenhickey13.wixsite.com/towcp](URL)

**Comment by owenhickey13** [comment]
> You know it's not about the version. Some files on unknown sites may be corrupted.

btw _i do know that_

**Comment by Baughn** [comment]
Okay, please contact support here: https://electrical-age.net/contact/

We'll be better able to help through IRC than via a bug. ;-)

**Comment by owenhickey13** [comment]
hello
