### ISSUE TITLE
Infinite loop in SixNode::canPlaceBlockAt

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#797]
Drop a sixnode-anything around a Rannuncarpus, and the server will freeze. This is our fault.
```
@Override
    public boolean canPlaceBlockAt(World par1World, int par2, int par3, int par4) {
        Utils.println("CACATOTAL1");
        while (true)
            ;// DON'tCALL THAT XD
    }
```

Wat.

**Comment by lashtear** [comment]
src/main/java/mods/eln/sixnode/thermalcable/ThermalCableDescriptor.java:62:            while (true) ;

is a similar instance but gated behind having an already bad thermal cable net.

**Comment by lashtear** [comment]
`find src -type f -name \*.java -print0 |xargs -0 egrep -C2 'while \(true\)'`  shows we have a much larger problem here.  This cause-a-hang methodology is in use in a bunch of places.

**Comment by metc** [comment]
@Dolu1990 `Utils.println("CACATOTAL1");`

**Comment by Dolu1990** [comment]
Ahahaah
<3
