### ISSUE TITLE
[Bug] Generators cannot be charged off inductors

### ISSUE THREAD

**Issue by OmegaHaxors** [Electrical-Age/ElectricalAge#799]
Realistically, the motor would begin drawing current from the inductor similar to a capacitive load and then begin to act like an inductive load once charged. However, in practice the inductor only allows 2mA of a 4kV load to pass the 100H inductor thus completely blocking the motor from charging up.

![2017-10-14_20 58 16](https://user-images.githubusercontent.com/16057503/31581589-68ad5d3c-b124-11e7-8f13-34c4be8c26a3.png)

The reason this is a problem is because I was planning on using the motor as an idler to regulate voltage and current, however this design flaw prevents me from doing so without a voltage/current regulator of its own.

**Comment by Baughn** [comment]
I'm doing a more general rework of the generator mechanics, which will include this--existing generators are going to start acting like permanent-magnet DC generators.

...well, you'll see soon enough.
