### ISSUE TITLE
[Enhancement] Signal Processor

### ISSUE THREAD

**Issue by BlayZett** [Electrical-Age/ElectricalAge#80]
An entry in the In-Game Wiki (or elsewhere) that explains what each character does and the commands and their usage would be very helpful.

**Comment by Dolu1990** [comment]
hmm yes i must add it very soon, in r30
Good idea :)

**Comment by Dolu1990** [comment]
ok, i have added the following :
![image](https://cloud.githubusercontent.com/assets/4832082/3790669/19f9944e-1b13-11e4-87d3-628a280cc9fe.png)
![image](https://cloud.githubusercontent.com/assets/4832082/3790670/225eec9c-1b13-11e4-9fb8-403d0ee976c6.png)
But for more complet explain i think we must do that on online wiki no ?

**Comment by BlayZett** [comment]
I agree. Thank you for adding this, it's going to help a lot.
