### ISSUE TITLE
order

### ISSUE THREAD

**Issue by Gerson1813** [Electrical-Age/ElectricalAge#800]
I would like to add transmission lines like these, where I could pass about 256 KW, leaving more realistic the mods, lines of transmission like these    if he came near he would take shock and die                                                  
                                                                                                                         
![67da9541-1eee-40d2-b4b1-e19e54533189](https://user-images.githubusercontent.com/29736511/31799200-7fa2c292-b517-11e7-8e8c-8df6ea64c0ea.jpeg)

**Comment by AMIDIBOSS** [comment]
Well, there will be Tier 2 powerlines

**Comment by Baughn** [comment]
Yeah, it's mostly complete. Blocked on some legal issues, but I should get that out of the way soon enough.

**Comment by AMIDIBOSS** [comment]
legal issues?
