### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by Zeinder** [Electrical-Age/ElectricalAge#81]
This error seems to be the bane of my existence in my 1.7.10 test world. It seems to occur consistently with some mods like Ender IO and it seems ProjectRed as well. 

Crash report: http://pastebin.com/nam3EiwH

**Comment by Dolu1990** [comment]
Hi, Thanks for issue,
I have secure this part of my code juste now, in future that could not happen. but could you explain to me how reproduct this bug exactly ? (with ProjectRed if possible) i don't have successfuly reproduct this bug :(

**Comment by Zeinder** [comment]
I forgot to mention that when this crash occurs it turns every ELN block into an invisible crash block you need to MCEdit out.

**Comment by Zeinder** [comment]
With project red I have it going Wireless Reciever -> Voltage to Redstone -> Red Alloy Wire

**Comment by Zeinder** [comment]
Oh, I forgot to mention break pretty much anything next to said ELN components.

**Comment by Dolu1990** [comment]
I have try that in single player, and nothing crash :( 
You are in single player no ?

**Comment by Dolu1990** [comment]
![image](https://cloud.githubusercontent.com/assets/4832082/3790872/44a3698e-1b1f-11e4-81ea-2918e686aad8.png)

**Comment by Zeinder** [comment]
Yea, single player.

**Comment by Dolu1990** [comment]
and we have exatly the same setup XD
joy XD Do you have a skype ?
could you share me your screen ?
skype => capons1785

**Comment by Zeinder** [comment]
I was going to make a youtube video of it quick actually.

**Comment by Dolu1990** [comment]
oky nice :)

**Comment by Zeinder** [comment]
Unfortunately I'm also battling this crash problem as well. http://pastebin.com/9Tqpnkga

**Comment by Dolu1990** [comment]
Your last crash report is on the same map ? it's probably due to map corruption of the first bug. 
is that possible ?

**Comment by Zeinder** [comment]
Well they don't appear back to back. I enabled the forge option to delete erroring entities so that at least let me back in quickly. The the other crash is hard to consistently reproduce.

**Comment by Dolu1990** [comment]
To explain why, it's because the first crash has product a not well saved map. All electrical blocks of electrical age have a "shadow" that is not saved with chunk, but in a separated file. When you have reload the map, this file was not loaded (because of bad crash) and that cause a lot of mistake.

**Comment by Dolu1990** [comment]
Forge can't see this kind of error.

**Comment by Dolu1990** [comment]
I release r30 in 5 mn, that must remove the first bug, and the second bug is due to the first.
Could you say me when it's released if that completly solve the first bug ?

**Comment by Dolu1990** [comment]
it's now released :)

**Comment by Zeinder** [comment]
I'll have to play for a bit to see if I can cause it, but I'll let you know.

**Comment by Dolu1990** [comment]
Thanks :)

**Comment by Zeinder** [comment]
Well I had a non-eln related crash, and nothing has exploded since. So fingers crossed it is fixed. Should it happen again at some point I'll let you know.

**Comment by Dolu1990** [comment]
Thanks you :) 
Sorry for your map crash.
