### ISSUE TITLE
Minecraft crashes when going near to running Generators

### ISSUE THREAD

**Issue by Domi1993** [Electrical-Age/ElectricalAge#814]
When i going near to running Gasturbines or Steamturbines with the Big Green Generators, Minecraft will crash.
It happened to me on the Erisia Server while i want to go inside the Powerplant to survive the first night.

Crash logs are Here:

The first Time when i go inside for the first night:

[crash-2017-11-15_21.25.07-client.txt](https://github.com/Electrical-Age/ElectricalAge/files/1485732/crash-2017-11-15_21.25.07-client.txt)

Second time when i rejoin the Server with Sounds and Music OFF:

[crash-2017-11-19_17.37.58-client.txt](https://github.com/Electrical-Age/ElectricalAge/files/1485733/crash-2017-11-19_17.37.58-client.txt)

**Comment by bloxgate** [comment]
Hi, can you try turning off or removing your shader mod and see what happens?

**Comment by Baughn** [comment]
Sorry, using shaders or optifine is just not supported, and won't be. I'd like to make that work for 1.10, but on 1.7 it's completely impractical.
