### ISSUE TITLE
rebalance of wireless antenna 

### ISSUE THREAD

**Issue by bomdia** [Electrical-Age/ElectricalAge#82]
i think the receiver antenna doesn't explode without any absorbment and the antenna can have 2 mode directional (actuall transmission mode) and (radiusly (with channel name) the max range is directional range / 2)
and the antenna can be placed on any late of a block (ex vertical transmission of energy)

**Comment by Dolu1990** [comment]
Hi.
Hmm maybe the antenna must be a little bit more directional and could track his target, it's not false. But for the moment wireless transmition is not our priority, we have to mutch to do all around into the mod :(
About vertical transmission, it's now fixed, in next update r31, you can place with less pain on any side.

Is the setup into the tutorial map understandable ?

**Comment by bomdia** [comment]
yes only after 2 try i have done it correctly :D mmm and for explosion? is a very shit !

**Comment by Dolu1990** [comment]
Cool ^^
Hmmm for explosion, that happend without any reason ? or it was because transmition antenna emit on a unconnected receiver antenna ?

**Comment by bomdia** [comment]
unconnected receiver  or connected on a item that want low power (w)

**Comment by Dolu1990** [comment]
oky, It's very imortant to put some capacitor or batteries to the receiver antenna. maybe i must put a little condensator integrated into the receiver antenna ?

**Comment by bomdia** [comment]
or do a more expensive (diamond) antenna that doesn't explode?

**Comment by Dolu1990** [comment]
lot of receipe need to be reworked, i must start to work on that now ^^

**Comment by Dolu1990** [comment]
I have added a tag to disable explosion (next update)
