### ISSUE TITLE
Cable Brushes Used in Creative Mode

### ISSUE THREAD

**Issue by jrddunbr** [Electrical-Age/ElectricalAge#823]
I think it's an error, but cable painting brushes can be completely used in Creative mode.

It would make more sense if there was no limit to the number of blocks you could paint while in Creative mode, so that one does not need to keep getting a new brush from the creative menu or NEI after 32 blocks are painted.

![2017-12-16_23 04 34](https://user-images.githubusercontent.com/14130505/34076439-81eecae8-e2b5-11e7-933e-21c828df57e8.png)

**Comment by AMIDIBOSS** [comment]
dup.

**Comment by jrddunbr** [comment]
By "dup", do you mean duplicate? I can't find a duplicate issue like this one.

**Comment by pooing1234** [comment]
@AMIDIBOSS When will the next update for this mod be released?

**Comment by AMIDIBOSS** [comment]
Never xD

**Comment by jrddunbr** [comment]
@pooing1234 - It is discouraged to just make comments on an issue unrelated to the issue. If you have a question of that caliber, it is best you ask in the IRC channel (#electricalage on Rizon) or [the gitter support page](https://gitter.im/Electrical-Age/Support) (which echo's the chat to the IRC channel bidirectionally), or if you can't do any of that, make a new issue.

The real answer is sometime this spring I would guess. The next release is on hold for technical reasons, which I do not know when will be resolved. @Baughn may be able to give you a more direct answer on that timeline.

In the meantime, If you want the latest stuff available for MC 1.7.10 *right now*, go clone down develop, and then merge feature/t2-poles into it. That will get you most of the new stuff out there. If you have a problem doing that, [read up online](https://git-scm.com/docs/gittutorial) on how one uses Git.
