### ISSUE TITLE
No ampere

### ISSUE THREAD

**Issue by haldor8** [Electrical-Age/ElectricalAge#827]
When I go to the tutorial map, everything works
But when I go to somewhere else it doesn't work, I tried many differents versions of the mod, I disabled some, disabled everything and still nothing is produced. I have nearly 200 mods active but I play in 1.7.10

**Comment by Baughn** [comment]
Please paste/link to the log from your client's logs/ directory. Also, be more specific: Exactly how does it not work?

**Comment by haldor8** [comment]
I tested all the productions and there's no ampere produced, there's just the voltage

**Comment by haldor8** [comment]
[2017-12-23-2.log.gz](https://github.com/Electrical-Age/ElectricalAge/files/1584147/2017-12-23-2.log.gz)

**Comment by haldor8** [comment]
Solved
