### ISSUE TITLE
enchanchement signal processor

### ISSUE THREAD

**Issue by bomdia** [Electrical-Age/ElectricalAge#83]
add if (if(A=50){10})

**Comment by Dolu1990** [comment]
It's already possible with (A > 0.5) \* 10
the A > 0.5 test if A is bigger than 50% and return 1 if true, else 0

**Comment by bomdia** [comment]
how write this statament if(A=50v){B}else{C}

**Comment by Dolu1990** [comment]
(A > 0.5) \* (B-C)+C
I aggree it's not very nice XD

**Comment by Dolu1990** [comment]
But, i can add a function like that :
if(A > 0.5,B,C)
it's very easy for me to add this kind of function, do you want ?

**Comment by bomdia** [comment]
mmm this more simple

**Comment by bomdia** [comment]
than actual solution

**Comment by Dolu1990** [comment]
i add that, that come in r31

**Comment by Dolu1990** [comment]
^^ thanks, it's a good idea

**Comment by Dolu1990** [comment]
it's now released in r31
