### ISSUE TITLE
crash at initializing 

### ISSUE THREAD

**Issue by tonimark** [Electrical-Age/ElectricalAge#836]
I got a crash at initializing here:
[notes.txt](https://github.com/Electrical-Age/ElectricalAge/files/1649656/notes.txt)
it says id: 67 already registered this caused by a mob or item or block having the same id with other mod

**Comment by AMIDIBOSS** [comment]
Do you have Matter Overdrive? Can you try removing it and then testing?

**Comment by Baughn** [comment]
This is a straightforward configuration error. You need to make sure there are no ID clashes between entities from different mods, and we do provide a configuration file for this.
