### ISSUE TITLE
Example Mod Naming[BUG]

### ISSUE THREAD

**Issue by AntonBoch1244** [Electrical-Age/ElectricalAge#84]
![examplemodeln](https://cloud.githubusercontent.com/assets/2631432/3794236/08aa4f66-1baa-11e4-8f88-72474353c559.png)

**Comment by Dolu1990** [comment]
Hi,
It's because we override these information into the java code. but i must fix that.
Thanks for issue

**Comment by AntonBoch1244** [comment]
@Dolu1990 Thanks for Patch this bug.

**Comment by Dolu1990** [comment]
XD in r30 i have do stupid error, it's ok in r31
