### ISSUE TITLE
Lamp Supply not working

### ISSUE THREAD

**Issue by zhiyan114** [Electrical-Age/ElectricalAge#844]
So i haven't use this mod for a while but i notice that the Lamp Supply does not want to turn the lights on for some reason.

On the 1.13 it works but 1.14.2 it does not and i use the same method to power on the lamp so how do i fix this? or is this just my configuration for it incorrect (i most likely believe it a error).

**Comment by jrddunbr** [comment]
Take some screenshots?

Did you attach a button and name the channels?

sent from Jared's phone

**Comment by zhiyan114** [comment]
Thanks so here is the 3 image that i used to setup the thing 
![error1](https://user-images.githubusercontent.com/20156291/38461501-cc4e3c94-3a9f-11e8-91fa-aff2ed1a805c.PNG)
![error2](https://user-images.githubusercontent.com/20156291/38461502-cc604556-3a9f-11e8-9869-e93e1558d4f1.PNG)
![error3](https://user-images.githubusercontent.com/20156291/38461503-cc6f09b0-3a9f-11e8-980c-4f58cca82889.PNG)

**Comment by AMIDIBOSS** [comment]
Change the second channel name to "test_signal" Add a wireless switch and put it on channel "test_signal". This switch now toggles the lights.

**Comment by zhiyan114** [comment]
Ok thanks cause the older version does not need the switch to use but that fixed my problem
