### ISSUE TITLE
Gas Turbine Fuels

### ISSUE THREAD

**Issue by ethamitc** [Electrical-Age/ElectricalAge#846]
I want to fuel a gas turbine, but I have no clue what fuels I can use. Is there any that come with Electrical Age?

**Comment by BinaryDust** [comment]
@ethamitc to generate power with a gaz turbine, you need to have at least one of the mods listed on the wiki:
https://wiki.electrical-age.net/index.php?title=Gas_turbine
and then use the proper fuel from mods you just install

**Comment by jrddunbr** [comment]
No fuels come with electrical age. I've seen most bases powered from Buildcraft fuel and I think syngas.
