### ISSUE TITLE
Electric Meter and Advanced Electric Meter

### ISSUE THREAD

**Issue by hayzefr** [Electrical-Age/ElectricalAge#847]
Hi, i want to do a electical network for a town and, to do more "realistic" i need them.
So, i can't connect the Electrical Meter it's doesn't work with any cables, so can you help me about that. Thanks :)

**Comment by BinaryDust** [comment]
@hayzefr pour utiliser le compteur (normal et avancé) tu doit utiliser des câbles fait pour le transport d'énergie (les bleus, verts, oranges ou rouges). Pour connecter le compteur au réseau, il ne faut pas oublier d'ajouter un câble supplémentaire ( de préférence le même utilisé dans le reste du réseau) dans l'interface du compteur, tu dois normalement avoir une case vide "Electrical Cable Slot"

**Comment by Baughn** [comment]
This bug tracker is not intended for user support, only bugs. If you need help, please visit https://electrical-age.net and look at the wiki or support page.
