### ISSUE TITLE
Some recipes don't work

### ISSUE THREAD

**Issue by andrew32167** [Electrical-Age/ElectricalAge#85]
Recipes like Cheap chip or another chip don't work, or 50V heating corp recipe makes copper legins instead.

**Comment by Dolu1990** [comment]
Hi,
I must take a look to that, which version of the mod you has ?

**Comment by andrew32167** [comment]
1.2.0b - mod version
1.6.4 - minecraft version

**Comment by Dolu1990** [comment]
Hooo, it's a sooooooooo outdated version.
The mod is already in beta, now we are into 1.8_r30 :) but only 1.7.x minecraft compatible.

**Comment by Dolu1990** [comment]
These issue was fixed some time ago. We can't maintain 1.6.4 because of to mutch change with 1.7.2 :(
Any way, thanks for issue :)
I recommand if you can to go with last version of the mod
