### ISSUE TITLE
Suggestion for the mod: Transistors

### ISSUE THREAD

**Issue by luke-a-childs** [Electrical-Age/ElectricalAge#855]
I've noticed this mod is missing a most crucial component and that is the transistor which means their is no way to have fast switches for high voltage components

**Comment by bloxgate** [comment]
See #161, #585, #791

**Comment by Baughn** [comment]
The relays already switch at the simulation rate. Short of overhauling the core simulator (and adding a GPU dependency, likely enough), there's no way to improve the speed.

The other transistor feature request is more for its intermediate states between open/closed, rather than speed.
