### ISSUE TITLE
Wireless Network Viewer

### ISSUE THREAD

**Issue by jrddunbr** [Electrical-Age/ElectricalAge#858]
Was poking around at a larger setup that made a lot of use of the wireless signals..

It would be nice if we could have a handheld device that tells us what wireless networks are in range of where we are standng - both the signal networks, and the power networks, as well as what voltage they are at.

Probably pretty easy to make such an item.

**Comment by Baughn** [comment]
There already is such an item -- the wireless analyzer. It only works for wireless networks, mind you.

It's a bit tricky to use. You have to right-click a block, and it'll tell you signal strengths at that block. We should probably might right-clicking the air an option.

**Comment by jrddunbr** [comment]
Wow, I must be blind. Thanks!
