### ISSUE TITLE
[new item][enchanchement]new thermal cable

### ISSUE THREAD

**Issue by bomdia** [Electrical-Age/ElectricalAge#86]
there be a new thermal cable that connect to electrical cable to cool down it!
or  trasmission of high power (kw) is impossible all cable explode after second

**Comment by Dolu1990** [comment]
Hi,
Maybe one possibilities is to add new items, that are "Cable dissipator" and when you right click with it on a cable => that put a small dissipator on it ?
(i think add new cables for heat dissipation can do some bad case where you have 2 lines (one elctric, one thermal) and at every block they interconnect)

**Comment by bomdia** [comment]
Mmm good idea or do a new tipe of electrical cable that already have dissipation (a mix of dissipator texture and cable texture)

**Comment by bomdia** [comment]
Like thermal dissipated low /medium /high voltage cable

**Comment by cm0x4D** [comment]
Is this still an issue as we have now the 3kV cable? It feels a little strange to cool cables...

**Comment by bomdia** [comment]
I need more time to correct test new cable :D

**Comment by bomdia** [comment]
mmm i have tested and the very high cable explode lol the problem is if you want to use 20kW there isn't any cable to use the maximus of cable is 15kW this is incoherent you have to extend to 20kW the cable
