### ISSUE TITLE
New BUG

### ISSUE THREAD

**Issue by Gerson1813** [Electrical-Age/ElectricalAge#862]
The lights are flickering and causing lag problems. I have about 30 lights, and the voltage is stable at 223 volts.

Here is a video demonstrating the lighting bug as well:
https://www.youtube.com/watch?v=C0asqGgFEJk&feature=youtu.be

**Comment by Baughn** [comment]
All right.

It's an old bug I've never been able to track down. I'm going to close this for now, because I've rewritten the lighting code for 1.10 anyhow, but please do reopen if it's still there once the port is out.
