### ISSUE TITLE
1.12 or 1.13 support

### ISSUE THREAD

**Issue by Dragonox77** [Electrical-Age/ElectricalAge#866]
Hi,
I'm asking you,please to update this mod for minecraft 1.12 or minecraft 1.13.

I love this mod so much but I really would like to play with minecraft 1.12 or 1.13 because I want to play with others mods.

If you update this mod, this will be insane !

Thanks a lot for reading me.

**Comment by jrddunbr** [comment]
Update in progress to 1.12 since January. Not quite there yet.

**Comment by Dragonox77** [comment]
Oh ok thank you :D.
