### ISSUE TITLE
Help. Computercraft

### ISSUE THREAD

**Issue by J09** [Electrical-Age/ElectricalAge#868]
Hello, I wanted to make vaults meter with computercraft. Can you show me an example with code to work with a cc monitor. Thanks

**Comment by OmegaHaxors** [comment]
Use the ELN probes to get your signals, then pass them over to the Signal->Computer converter, then you pull the values out of that using your computer.

You'll have to figure out the API involved, but it shouldn't be too difficult.

**Comment by J09** [comment]
Thanks!

**Comment by OmegaHaxors** [comment]
The wiki article will be very helpful in learning how to use the block.

https://wiki.electrical-age.net/index.php?title=Eln_Computer_Probe
