### ISSUE TITLE
Project ownership

### ISSUE THREAD

**Issue by Baughn** [Electrical-Age/ElectricalAge#876]
Paging @cm0x4D / @Dolu1990 / @lambdaShade.

Currently I'm set as a project member, not owner, which is problematic when I'm trying to set up releases and integration with the FOSSA license scanner. Any chance we could change that?

**Comment by Baughn** [comment]
@Dolu1990? You're the most active of the admin trio.

**Comment by cm0x4D** [comment]
I am a contributor at best, so it should be either @Dolu1990's or @lambdaShade's final decision...
I would vote for a Yes.

**Comment by Dolu1990** [comment]
+1

**Comment by Dolu1990** [comment]
@Baughn You are now set as owner in the ElectricalAge organisation, is it ok  ?

**Comment by Baughn** [comment]
Yup, thanks muchly.
