### ISSUE TITLE
Various Issues and Feature Requests

### ISSUE THREAD

**Issue by Zeinder** [Electrical-Age/ElectricalAge#88]
Issues:
*1 Dimension moving between Aroma1997's Dimensional World (possibly others) causes ELN blocks to become ghost enties and be destroyed upon breaking and fail to operate correctly. Update: Chunk loading doesn't fully prevent issue.

*2 Biofuel bucket from MFR in Stone Heat Furnace destroys bucket.

Feature requests:
*1 800v Power Provider (Perhaps reactor or large turbine)
*2 Liquid Fueled Heat Generator
*3 Ticks remaining on current fuel in Stone heat furnace
*4 Mod ore processing in macerator, preferably with extra output capability
*5 Miner second pipe slot and the ability to upgrade with forture/silk touch. Also support for other containers like chests from the iron chests mod.

**Comment by Dolu1990** [comment]
issue
*1 Can you reproduct this bug with nether ? What is the Aroma1997 dimention id ? ( i have very very rarly tested other dimention with the mod) XD
Are block into Aroma corrupted ? Are block into normal world corrupted ?
*2 I juste fix that now. Thanks ^^ now if the item has the "
bucket" in the name it's not consumed
requests
*1 we are to few on the project for the moment :(
*2 Using other mod liquid pipe ? or using lava ?
*3 I must do that
*4 I don't understood, can you be more specific ?

**Comment by Zeinder** [comment]
*1 Not so far with the nether, but I'll keep testing. I have the Aroma1997 id set to 38 currently
Only aroma blocks seem to be breaking. 

requests
*2 Primarily other mod liquid pipes, possibly make it bucket insertion capable. More efficient for lava to make it worthwhile.
*4 Well it won't even macerate ores from other mods. As for the extra output I mean for example Ferrous ore from ThermalExpansion has a 10% chance of shiny dust as well, An extra output slot would be useful even for the purposes of macerating a whole stack.

**Comment by Zeinder** [comment]
Just a thought for request *1, How about make a 800v turbine, basically a 200v turbine, but 800v and say 1kw output, and then the reactor could be for simplicity's sake a placehold box, it could output thermal energy, but instead of standard fuels, it could operate off of Cinnabar Rods, crafted from putting cinnabar dust in a compressor.

**Comment by Dolu1990** [comment]
*4 i think it's a good idea to have some randome from macerate blocks and multiple loot :) 
So for 800V machine, for the moment only transporter and autominer are 800V.

Actualy the gameplay is start 50V base, upgrade it to 200V, use 800V for range interconnect.
For the moment we are to few to begin very high power part of the mod :(

**Comment by Dolu1990** [comment]
I try now to reproduct the bug with aroma.
(factory machine have now 4 slots)

**Comment by Dolu1990** [comment]
I don't have sucessfuly reproduct the bug :(
Could you reproduct it each easly ? (100% bug success) ?
Could you say to me a exact procedure to do to product the bug ?

**Comment by Zeinder** [comment]
Video reproduction of the bug. This only took 1 try to do.
https://www.youtube.com/watch?v=H4BF-HN1Iao&feature=youtu.be

**Comment by Dolu1990** [comment]
Hooo thanks. i have watch and reproduct :)
veeeeeeery interresting bug. i must fix that !

**Comment by Dolu1990** [comment]
Oky i have understood why XD
It's because when you return to dimention 6 to 0, for example, the dimention 6 is unloaded. but my mod keep World instance in cache, and when you go from 0 to 6 a new world is created !
XDXDXD
.. XDXD... XDXDXDXD     XD
Thanks for issue : D i fix that now

**Comment by Dolu1990** [comment]
it's now released in r34
