### ISSUE TITLE
Blocks have full block bounding boxes

### ISSUE THREAD

**Issue by DrummingFish** [Electrical-Age/ElectricalAge#9]
Most of the blocks that are not full sized blocks need bounding boxes that fit more with the block.

![2014-03-12_17 06 17](https://f.cloud.github.com/assets/6238934/2400291/b95610b6-aa08-11e3-8434-f64b0a3d0ee2.png)

This causes problems with "multiblock" features as you can only access the latest block added to the block space:

![2014-03-12_17 07 56](https://f.cloud.github.com/assets/6238934/2400307/e397d5a8-aa08-11e3-98a2-ac1a8f4852f9.png)

**Comment by Dolu1990** [comment]
I must explore how make that better, but i don't want for each model define with and the bounding box. it to mutch work :(

maybe i reduct the actual big 1_1_1 box to 6 smaller part depending if one something is placed ?

**Comment by cm0x4D** [comment]
Do these bounds have to be boxes? How about a pyramid with a surface of 1x1 and the hight 0.5 for just all six node elements? I guess in the most cases it would be ok to select elements using this bounding mechanism and they would never overlap, even when you place six of them in a box of 1x1x1.

**Comment by DrummingFish** [comment]
To be honest I think that the work should be done to have accurate bounding boxes. This way it looks nicer and Multipart features will screw up less.

**Comment by Dolu1990** [comment]
Yes in any case the ideal solution is the accurate bounding boxes.  i must take a look how that work in minecraft source ^^

**Comment by DrummingFish** [comment]
I think it's actually quite simple. I'll have a look too.

**Comment by Dolu1990** [comment]
It's now fixed into BETA-1.6_r13
Thanks for issue :)
