### ISSUE TITLE
Signal relay and signal switch

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#90]
Relay: Just like the ones for power, but for signal cables.
Switch: I know there's a switch, but not that type, like the power ones.

That will be really useful for systems like the one I'm making.

**Comment by Dolu1990** [comment]
Relay: Just like the ones for power, but for signal cables.    => tri-state driver ? 
http://www.ni.com/cms/images/devzone/tut/a/af8afe69155.gif
I aggree :)

Switch: oky i add that

**Comment by ivangouba** [comment]
Relay: yes, a thing that allows the pass of the signal depending on the intensity of the signal it receives.
Thank you. :D

**Comment by Dolu1990** [comment]
But just, what are you doing ?
(Signal Processor can do things not far than that, just  a litle bit heavy XD)

**Comment by ivangouba** [comment]
I have a heat furnace controlled externally by a voltage probe, and I'd like to put a relay on the cable from the voltage probe to the furnace to choose from distance if I want to use manual control or automatic control.
Yes, the signal processor is way too complicated for me

Anyway, I realised that it doesn't make sense to use manual control when the automatic control is perfect, but it might be useful for other things.

**Comment by Dolu1990** [comment]
Ahh oky,
Manual control with trimmer block ?  where you have the track bar ?

**Comment by Dolu1990** [comment]
just with the signal processor, it's      if(A,B,C)      where A is if you want to do manual controle B is the value of the manual controle, C is the automatic controle from voltage probe.

**Comment by Dolu1990** [comment]
(you need recent mod release to use the if function into signal processor

**Comment by ivangouba** [comment]
Ok, thank you
