### ISSUE TITLE
BETA-1.8_r34: Water Turbine Cable [Graphical Error]

### ISSUE THREAD

**Issue by BlayZett** [Electrical-Age/ElectricalAge#92]
The cable doesn't connect properly to the Water Turbine. The corner is missing where it connects.
![2014-08-09_07 49 07](https://cloud.githubusercontent.com/assets/8340715/3866016/3c4480e8-1fbb-11e4-9080-97726c7cf2fd.png)

**Comment by cm0x4D** [comment]
![2014-08-24_22 55 44](https://cloud.githubusercontent.com/assets/6661117/4024583/559f1d06-2bd1-11e4-92a9-c12799a7a62f.png)
![2014-08-24_22 55 52](https://cloud.githubusercontent.com/assets/6661117/4024584/55a3d4b8-2bd1-11e4-904a-ce5d48150d58.png)
