### ISSUE TITLE
Implement Griefing Protection / World Guard Compatibility for Electrical Age on Servers [Long Term]

### ISSUE THREAD

**Issue by ellingtonisland** [Electrical-Age/ElectricalAge#920]
Implement Griefing Protection / World Guard Compatibility for Electrical Age on Servers [Long Term]

Porting EA to MCreator might be the key to pulling this off if you can get the external parts and translate the solver that Electrical Age uses into procedures in MCreator so that if world guard placed a block it would also restore the state of the block.

**Comment by Baughn** [comment]
We do not support any non-Forge systems. This is not happening, and *can't* happen.

(Do you have any idea how much work what you're proposing would be? It would take a year of full-time work, if it's even possible.)
