### ISSUE TITLE
Kotlin in the Java source dir

### ISSUE THREAD

**Issue by Sanduhr32** [Electrical-Age/ElectricalAge#924]
This bug-tracker is for bugs, feature requests and development tracking, not general support. Please see the [support page](https://electrical-age.net/contact/) for support and discussion.

- [ ] Bug report
- [ ] Feature request
- [x] Bad practise

## Issue description
One man does simply not put kotlin source outside of the standard naming scheme `src/main/<lang>/...` for any java application. It's considered bad practise.

**Comment by Baughn** [comment]
Actually, we do. It's just fine. Our code is organized by function, not language.
