### ISSUE TITLE
Modbus Rtu

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#93]
Hello !
Can somebody help me how to use this I cant figure it out :(
How do I configure it,can I use this to control (turn on or off) signal processor from a control room ?
(I write a nother issue in the " help" section to,please help me with that to)

**Comment by cm0x4D** [comment]
The modbus RTU can be used to access the signals (local and wireless) in Minecraft from the real world using the ModbusTCP protocol. This would enable you to control and monitor those signals using a real world PLC or SCADA system. It is pretty useless if you want to access it inside Minecraft. The ModbusTCP server is deactivated by default in the configuration file.
