### ISSUE TITLE
Possible Issue with RF api

### ISSUE THREAD

**Issue by BrizzleMFD** [Electrical-Age/ElectricalAge#94]
Im getting a Mod cycle issue involving the RF API seems your mod wants to get loaded before COFH core because of this, and i guess thats not a good thing! No sure if it you or if its another mod just thought i would inform you guys!

**Comment by Dolu1990** [comment]
Hi,
I think it's my mod, but why it could be bad if electrical age load api before COFH ? it use juste interface and nothing else.
I don't have experience into problems that could appear with API and this kind of behavoral, do you see a case where that could make some problem ?

**Comment by BrizzleMFD** [comment]
I think is because cofh handles the the energy with a slightly different way 

This is possibly of help https://github.com/CoFH/ThermalExpansion/issues/49

**Comment by BrizzleMFD** [comment]
your not the only one
http://gyazo.com/0ee2a770b7d3bfaf8f981bf86fdaedf4
but yeah heres the latest log
http://pastebin.com/cue9qP9N

**Comment by Dolu1990** [comment]
Ahhhh it's what forge has aded into very last release ? 
So basicly i juste must add   "dependencies": ["CoFHCore"]
into the modinfo ?

**Comment by McyD** [comment]
You shouldn't have API's in your mod at all.  I don't understand why so many mod authors cannot, understand this.  The API is only for you to code against, if COFHcore is required to run your mod, then having the API included only causes issues, when your included version becomes obselete.

**Comment by BrizzleMFD** [comment]
I should state that the latest build fixed it I think

**Comment by Dolu1990** [comment]
Oky, it's was the RF api update that solve this issue :) thanks for closing + feed back.

McyD => The reason is that COFH is not "owner" of RF. It's a API that any mod can implement to transfer energy and COFH is not needed. for example enderIO mod has cable that handle RF.

I don't put IC2, buildcraft, OC,CC api. but RF yes. I'm false ?

**Comment by BrizzleMFD** [comment]
No problem I love the mod keep me up to date. The modpack users just got it in and update yesterday!
