### ISSUE TITLE
Can you please port the Mod to 1.10.2?

### ISSUE THREAD

**Issue by NyboTV** [Electrical-Age/ElectricalAge#944]
Can you please Add the Mod for 1.10.2? I love your Mod but other Mods are Only for 1.10.2 and they have no Support to ask for another Version

**Comment by jrddunbr** [comment]
It's getting ported to 1.12, but it's taking a long time. Odds are unless we get many more competent developers that this mod won't be on 1.10.

**Comment by AMIDIBOSS** [comment]
Believe me, we're on it
