### ISSUE TITLE
Transporter Teleports to Random Location

### ISSUE THREAD

**Issue by 09jlardinois** [Electrical-Age/ElectricalAge#946]
## Issue description
The transporter I setup is configured to send to another, but it just teleports me to a random location. It's actually pretty fun and also was a hilarious surprise, but I still thought I should let you guys know.

### Steps to reproduce
Made a power plant to run three 800 volt lines into the transporter, set to 9000w ish consumption, configured the names and destination names. Pressed Start. 

### Electrical Age version
1.14.2

**Comment by Baughn** [comment]
Working as intended.

This is what happens if your transporter runs out of power during transport.

**Comment by 09jlardinois** [comment]
Aah, sorry about that. I read that in the Wiki but I thought it meant it would transport you randomly along the line between the start and end points. I didn't realize it meant randomly in any direction.

**Comment by Baughn** [comment]
It *would* make more sense if it was inside an arc pointed at your destination, wouldn't it?

**Comment by jrddunbr** [comment]
I would re-open this as a feature request, it does make a lot of sense. There may be precedence for that sort of thing from the TARDIS mod too, no?
