### ISSUE TITLE
800v turbine?

### ISSUE THREAD

**Issue by tvk1372** [Electrical-Age/ElectricalAge#95]
Hi!
Can you make a 800v turbine?
My issue is,when I use 200v turbines to generate power for my city I have to use a lot of those,and I think a 800v turbine can handle it much much better whit less heat power. 
The 200v turbines are very weak for generate that much power,when the lights are turning on,the voltage is dropping very fast.
And I have a very bad question,but I wanted to know: Can I change the configuration of my 200v generator in my minecraft/eln mod to put out more voltage ho handle that much energie consumption?
which folder is the configuration file for that 
And sorry for the bad question again!
(please made a 800v turbine to)

**Comment by Dolu1990** [comment]
Hi,
Generator with higher power are planned but for the future, actualy we stabilise all. we are to few on the project :(
Juste to know, what is the consommation of your city ? in watt ?

**Comment by tvk1372** [comment]
I dont know sure but I use 5 piece of 32 life hour 200v light bulb / house, and I can only power ~12house with 6x200v generator  and the voltage is ~ max130v at the last bulb,and my out put voltage is on the generator is 223v  :(
So thats why I write you that message to bulid a red 800v or 1kv generator,because when I use extreme load of power it doesnt work very good,and when I want to over Voltage it,it blows up because it reaches ~400 celsius :(
I would change the configuration file for my own risk but I dont know,how to over voltage it.
I think a much stronger 800v or 1kv generator would help some people not just me.

**Comment by Dolu1990** [comment]
it's not a power production problem, it's a power distribution problem. you can use transformer block to rise the voltage to 800V and transport it with a loooot less voltage drop. and when you are near the house you reput a transformer to reduct the voltage to 200V.

realy, it's not a power problem, it's a network problem :)

**Comment by Dolu1990** [comment]
(you can rise the life of lamp into eln.cfg :) )

**Comment by tvk1372** [comment]
Thank you for the help :)
