### ISSUE TITLE
Add features to X-ray scanner.

### ISSUE THREAD

**Issue by JalapenoPepper** [Electrical-Age/ElectricalAge#955]
- [ ] Feature request

## Issue description
I'd like to ask, if its possible to add custom color discriminating paletts to X-ray scanner, or adding a special upgrade to tune it on a various types of ore. It can be done with upgrading a existing scanner with discriminator upgrade, that will add a slot into scanner's menu, where you need to place an ore sample to detect. Or, you can switch between standard palett and different ones for various type of ores, like on thermal imaging cameras.
![image](https://user-images.githubusercontent.com/61760242/85873404-bfb02600-b7d9-11ea-91ee-f0c24d9af4c4.png)
Also, it will be nice to add a Thermal Imaging Scanner, that will display traces of natural heat sources(lava blocks/lakes, fire, magma, entities, animals, etc., or heat-radiated objects like thermal transferring cables, electrical wiring, machinery
![image](https://secureservercdn.net/50.62.172.113/a93.412.myftpupload.com/wp-content/uploads/2014/08/infrared_ir_thermography_in.gif)
but this is a least, what to do now

### Electrical Age version
Future planned releases or 1.17.1

If you need some help with this, I can try to help you with designing GUI or making custom textures for anything, just ask me)

**Comment by Caeleron** [comment]
This version of ELN is not being developed further. Development is now going towards ELN2 (https://github.com/eln2/eln2)

**Comment by JalapenoPepper** [comment]
But ELN2 is for 1.15.2, right? I've experienced severe performance drops on 1.12.2 server, and I moved back to 1.7.10, and I fear, that 1.15.2 will be laggy as 1.12.2

**Comment by Caeleron** [comment]
Correct, ELN2 is going to be on 1.15.2. There will be no development for the 1.7.10 version.

**Comment by JalapenoPepper** [comment]
> Correct, ELN2 is going to be on 1.15.2. There will be no development for the 1.7.10 version.

:(
