### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by alexhorner** [Electrical-Age/ElectricalAge#963]
I know I am now following the guidelines for raising an issue here, but I think that's okay in this circumstance.

Is this mod completely dead?

**Comment by AMIDIBOSS** [comment]
No, it's still very much alive
[https://github.com/age-series/ElectricalAge](https://github.com/age-series/ElectricalAge) 
Also, electrical Age 2 is in development.

**Comment by alexhorner** [comment]
> No, it's still very much alive https://github.com/age-series/ElectricalAge Also, electrical Age 2 is in development.

Would definitely say its worth pointing to this in this repo's readme with big letters!
