### ISSUE TITLE
What happened to the diodes?

### ISSUE THREAD

**Issue by ivangouba** [Electrical-Age/ElectricalAge#97]
They are not in the wiki and they are not in creative, though I can take the ones I already have in my world with the scroll wheel and use them.

**Comment by Dolu1990** [comment]
Hi,
i'm mitigated with diodes, (because simulation model is not very good and that could add some instability if i do a realistic simulation model)

in which case you use it in your map ?

**Comment by ivangouba** [comment]
In my house, I have 2 turbines, 4 solar panels and 4 Cost-Oriented batteries, and I want to put it between the solar panels with the batteries and the turbines, so batteries don't get charged with electricity from the turbines.

**Comment by Dolu1990** [comment]
Ahh oky, So for this kind of network the actual diod simulation model fit wheel, so i restore it in next release :)

**Comment by ivangouba** [comment]
Thank you :D
